<?php
			$optionsArray = array( 'master' => array( 'identitas_pasien' => array( 'preview' => true ),
'users' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'lama_perkawinan_1',
'lama_perkawinan_2',
'lama_perkawinan_3',
'anak_perkawinan_1',
'anak_perkawinan_2',
'anak_perkawinan_3',
'Libido',
'Frekwensi_koitus',
'Dispareuni',
'Orgasmus',
'Reflux_Post_Coital',
'Ejakulasi_Dini',
'Ejakulasi_Nocturnal',
'Ejakulasi_Nyeri',
'Puber',
'Masturbasi',
'Koitus_pranikah',
'Lain_lain',
'Peny_Hub_Seksual',
'Hernia',
'Hidrokel',
'Trauma',
'Kelainan_bawaan',
'Penyakit_Paru_kronis',
'Penyakit_hidung_kronis',
'Tuberkulosa',
'Diabetes_mellitus',
'Gondongan_parotitis',
'Penyakit_Saraf',
'Panas_dlm_6_bln',
'Saudara_kandung_suami',
'Saudara_kandung_istri',
'Pekerjaan',
'Keluarga',
'Rokok',
'Alkohol',
'Obat',
'Celana ketat',
'Bahan_kimia',
'KU',
'TB',
'CM',
'BB',
'KG',
'Tensi',
'Pertumbuhan_distribusi_rambut',
'Kumis',
'Jenggot',
'Mata',
'Hidung',
'Leher',
'ginecomastia',
'PERUT',
'INGUINAL',
'kubitus (valganus / varus)',
'Rentangan tangan',
' Rambut axilla',
'Cor',
'Hepar',
'Pulmo',
'Lien',
'Penis',
'Muara_Urethra',
'Skrotum',
'Pubis',
'Pola_Pubis',
'Interna_Kanan',
'Interna_Kiri',
'Posisi_Testis',
'Volume',
'Konsistensi',
'Nyeri',
'VAS_DEFERENS',
'FUNICULUS',
'EPIDIDYMIS_Ukuran',
'EPIDIDYMIS_Konsistensi',
'EPIDIDYMIS_Kistik',
'EPIDIDYMIS_Nyeri',
'EPIDIDYMIS_Permukaan',
'VARIKOKEL',
'Prostat',
'V_Seminalis',
'lab_ke',
'lab_tgl',
'no_reg_lab',
'kesan_lab',
'Diagnosis_Banding',
'Rencana',
'id_pasien',
'id_user',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'lama_perkawinan_1' => array( 'integrated_edit_field' ),
'lama_perkawinan_2' => array( 'integrated_edit_field1' ),
'lama_perkawinan_3' => array( 'integrated_edit_field2' ),
'anak_perkawinan_1' => array( 'integrated_edit_field3' ),
'anak_perkawinan_2' => array( 'integrated_edit_field4' ),
'anak_perkawinan_3' => array( 'integrated_edit_field5' ),
'Libido' => array( 'integrated_edit_field6' ),
'Frekwensi_koitus' => array( 'integrated_edit_field7' ),
'Dispareuni' => array( 'integrated_edit_field8' ),
'Orgasmus' => array( 'integrated_edit_field9' ),
'Reflux_Post_Coital' => array( 'integrated_edit_field10' ),
'Ejakulasi_Dini' => array( 'integrated_edit_field11' ),
'Ejakulasi_Nocturnal' => array( 'integrated_edit_field12' ),
'Ejakulasi_Nyeri' => array( 'integrated_edit_field13' ),
'Puber' => array( 'integrated_edit_field14' ),
'Masturbasi' => array( 'integrated_edit_field15' ),
'Koitus_pranikah' => array( 'integrated_edit_field16' ),
'Lain_lain' => array( 'integrated_edit_field17' ),
'Peny_Hub_Seksual' => array( 'integrated_edit_field18' ),
'Hernia' => array( 'integrated_edit_field19' ),
'Hidrokel' => array( 'integrated_edit_field20' ),
'Trauma' => array( 'integrated_edit_field21' ),
'Kelainan_bawaan' => array( 'integrated_edit_field22' ),
'Penyakit_Paru_kronis' => array( 'integrated_edit_field23' ),
'Penyakit_hidung_kronis' => array( 'integrated_edit_field24' ),
'Tuberkulosa' => array( 'integrated_edit_field25' ),
'Diabetes_mellitus' => array( 'integrated_edit_field26' ),
'Gondongan_parotitis' => array( 'integrated_edit_field27' ),
'Penyakit_Saraf' => array( 'integrated_edit_field28' ),
'Panas_dlm_6_bln' => array( 'integrated_edit_field29' ),
'Saudara_kandung_suami' => array( 'integrated_edit_field31' ),
'Saudara_kandung_istri' => array( 'integrated_edit_field32' ),
'Pekerjaan' => array( 'integrated_edit_field34' ),
'Keluarga' => array( 'integrated_edit_field35' ),
'Rokok' => array( 'integrated_edit_field36' ),
'Alkohol' => array( 'integrated_edit_field37' ),
'Obat' => array( 'integrated_edit_field38' ),
'Celana ketat' => array( 'integrated_edit_field39' ),
'Bahan_kimia' => array( 'integrated_edit_field40' ),
'KU' => array( 'integrated_edit_field41' ),
'TB' => array( 'integrated_edit_field42' ),
'CM' => array( 'integrated_edit_field43' ),
'BB' => array( 'integrated_edit_field44' ),
'KG' => array( 'integrated_edit_field45' ),
'Tensi' => array( 'integrated_edit_field46' ),
'Pertumbuhan_distribusi_rambut' => array( 'integrated_edit_field47' ),
'Kumis' => array( 'integrated_edit_field48' ),
'Jenggot' => array( 'integrated_edit_field49' ),
'Mata' => array( 'integrated_edit_field50' ),
'Hidung' => array( 'integrated_edit_field51' ),
'Leher' => array( 'integrated_edit_field52' ),
'ginecomastia' => array( 'integrated_edit_field54' ),
'PERUT' => array( 'integrated_edit_field55' ),
'INGUINAL' => array( 'integrated_edit_field56' ),
'kubitus (valganus / varus)' => array( 'integrated_edit_field57' ),
'Rentangan tangan' => array( 'integrated_edit_field58' ),
' Rambut axilla' => array( 'integrated_edit_field59' ),
'Cor' => array( 'integrated_edit_field60' ),
'Hepar' => array( 'integrated_edit_field61' ),
'Pulmo' => array( 'integrated_edit_field62' ),
'Lien' => array( 'integrated_edit_field63' ),
'Penis' => array( 'integrated_edit_field64' ),
'Muara_Urethra' => array( 'integrated_edit_field65' ),
'Skrotum' => array( 'integrated_edit_field66' ),
'Pubis' => array( 'integrated_edit_field67' ),
'Pola_Pubis' => array( 'integrated_edit_field68' ),
'Interna_Kanan' => array( 'integrated_edit_field69' ),
'Interna_Kiri' => array( 'integrated_edit_field70' ),
'Posisi_Testis' => array( 'integrated_edit_field71' ),
'Volume' => array( 'integrated_edit_field72' ),
'Konsistensi' => array( 'integrated_edit_field73' ),
'Nyeri' => array( 'integrated_edit_field74' ),
'VAS_DEFERENS' => array( 'integrated_edit_field75' ),
'FUNICULUS' => array( 'integrated_edit_field76' ),
'EPIDIDYMIS_Ukuran' => array( 'integrated_edit_field77' ),
'EPIDIDYMIS_Konsistensi' => array( 'integrated_edit_field78' ),
'EPIDIDYMIS_Kistik' => array( 'integrated_edit_field79' ),
'EPIDIDYMIS_Nyeri' => array( 'integrated_edit_field80' ),
'EPIDIDYMIS_Permukaan' => array( 'integrated_edit_field81' ),
'VARIKOKEL' => array( 'integrated_edit_field82' ),
'Prostat' => array( 'integrated_edit_field83' ),
'V_Seminalis' => array( 'integrated_edit_field84' ),
'lab_ke' => array( 'integrated_edit_field85' ),
'lab_tgl' => array( 'integrated_edit_field86' ),
'no_reg_lab' => array( 'integrated_edit_field87' ),
'kesan_lab' => array( 'integrated_edit_field88' ),
'Diagnosis_Banding' => array( 'integrated_edit_field89' ),
'Rencana' => array( 'integrated_edit_field90' ),
'id_pasien' => array( 'integrated_edit_field30' ),
'id_user' => array( 'integrated_edit_field33' ),
'Nomor_Rm' => array( 'integrated_edit_field53' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'master_info',
'integrated_edit_field53',
'tabs',
'integrated_edit_field33',
'integrated_edit_field30' ),
'section' => array( 'section',
'section2',
'section5',
'section1',
'section3',
'section4' ),
'section1' => array( 'section6',
'section7',
'section8',
'section9',
'section10' ),
'section2' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ),
'section3' => array( 'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17' ),
'section4' => array( 'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29' ),
'section5' => array( 'integrated_edit_field31',
'integrated_edit_field32' ),
'section6' => array( 'integrated_edit_field34',
'integrated_edit_field35' ),
'section7' => array( 'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40' ),
'section8' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46' ),
'section9' => array( 'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field47' ),
'section10' => array( 'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52' ),
'section11' => array( 'integrated_edit_field54' ),
'section12' => array( 'integrated_edit_field55',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59' ),
'section13' => array( 'section11',
'section14',
'integrated_edit_field75',
'integrated_edit_field76',
'section12',
'section13',
'integrated_edit_field82',
'section15' ),
'section14' => array( 'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68' ),
'section15' => array( 'integrated_edit_field69',
'integrated_edit_field70' ),
'section16' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74' ),
'section17' => array( 'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'section18' => array( 'integrated_edit_field83',
'integrated_edit_field84' ),
'section19' => array( 'integrated_edit_field85',
'integrated_edit_field87',
'integrated_edit_field86',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'master_info' => 'grid',
'integrated_edit_field53' => 'grid',
'tabs' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field30' => 'grid',
'section' => 'section',
'section2' => 'section',
'section5' => 'section',
'section1' => 'section',
'section3' => 'section',
'section4' => 'section',
'section6' => 'section1',
'section7' => 'section1',
'section8' => 'section1',
'section9' => 'section1',
'section10' => 'section1',
'integrated_edit_field' => 'section2',
'integrated_edit_field1' => 'section2',
'integrated_edit_field2' => 'section2',
'integrated_edit_field3' => 'section2',
'integrated_edit_field4' => 'section2',
'integrated_edit_field5' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field10' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field12' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field14' => 'section3',
'integrated_edit_field15' => 'section3',
'integrated_edit_field16' => 'section3',
'integrated_edit_field17' => 'section3',
'integrated_edit_field18' => 'section4',
'integrated_edit_field19' => 'section4',
'integrated_edit_field20' => 'section4',
'integrated_edit_field21' => 'section4',
'integrated_edit_field22' => 'section4',
'integrated_edit_field23' => 'section4',
'integrated_edit_field24' => 'section4',
'integrated_edit_field25' => 'section4',
'integrated_edit_field26' => 'section4',
'integrated_edit_field27' => 'section4',
'integrated_edit_field28' => 'section4',
'integrated_edit_field29' => 'section4',
'integrated_edit_field31' => 'section5',
'integrated_edit_field32' => 'section5',
'integrated_edit_field34' => 'section6',
'integrated_edit_field35' => 'section6',
'integrated_edit_field36' => 'section7',
'integrated_edit_field37' => 'section7',
'integrated_edit_field38' => 'section7',
'integrated_edit_field39' => 'section7',
'integrated_edit_field40' => 'section7',
'integrated_edit_field41' => 'section8',
'integrated_edit_field42' => 'section8',
'integrated_edit_field43' => 'section8',
'integrated_edit_field44' => 'section8',
'integrated_edit_field45' => 'section8',
'integrated_edit_field46' => 'section8',
'integrated_edit_field48' => 'section9',
'integrated_edit_field49' => 'section9',
'integrated_edit_field47' => 'section9',
'integrated_edit_field50' => 'section10',
'integrated_edit_field51' => 'section10',
'integrated_edit_field52' => 'section10',
'integrated_edit_field54' => 'section11',
'integrated_edit_field55' => 'section12',
'integrated_edit_field60' => 'section12',
'integrated_edit_field61' => 'section12',
'integrated_edit_field62' => 'section12',
'integrated_edit_field63' => 'section12',
'integrated_edit_field56' => 'section12',
'integrated_edit_field57' => 'section12',
'integrated_edit_field58' => 'section12',
'integrated_edit_field59' => 'section12',
'section11' => 'section13',
'section14' => 'section13',
'integrated_edit_field75' => 'section13',
'integrated_edit_field76' => 'section13',
'section12' => 'section13',
'section13' => 'section13',
'integrated_edit_field82' => 'section13',
'section15' => 'section13',
'integrated_edit_field64' => 'section14',
'integrated_edit_field65' => 'section14',
'integrated_edit_field66' => 'section14',
'integrated_edit_field67' => 'section14',
'integrated_edit_field68' => 'section14',
'integrated_edit_field69' => 'section15',
'integrated_edit_field70' => 'section15',
'integrated_edit_field71' => 'section16',
'integrated_edit_field72' => 'section16',
'integrated_edit_field73' => 'section16',
'integrated_edit_field74' => 'section16',
'integrated_edit_field77' => 'section17',
'integrated_edit_field78' => 'section17',
'integrated_edit_field79' => 'section17',
'integrated_edit_field80' => 'section17',
'integrated_edit_field81' => 'section17',
'integrated_edit_field83' => 'section18',
'integrated_edit_field84' => 'section18',
'integrated_edit_field85' => 'section19',
'integrated_edit_field87' => 'section19',
'integrated_edit_field86' => 'section19',
'integrated_edit_field88' => 'section19',
'integrated_edit_field89' => 'section19',
'integrated_edit_field90' => 'section19' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section' => array( 'location' => 'section',
'cellId' => 'c' ),
'section2' => array( 'location' => 'section',
'cellId' => 'c' ),
'section5' => array( 'location' => 'section',
'cellId' => 'c' ),
'section1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'section3' => array( 'location' => 'section',
'cellId' => 'c1' ),
'section4' => array( 'location' => 'section',
'cellId' => 'c1' ),
'section6' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'section7' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'section8' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'section9' => array( 'location' => 'section1',
'cellId' => 'c' ),
'section10' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field10' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field31' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field36' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field45' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field46' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field48' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field49' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field50' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field51' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field52' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field55' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field60' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field61' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field62' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field63' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field56' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field57' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field58' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field59' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'section11' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'section14' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field75' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'integrated_edit_field76' => array( 'location' => 'section13',
'cellId' => 'c1' ),
'section12' => array( 'location' => 'section13',
'cellId' => 'c' ),
'section13' => array( 'location' => 'section13',
'cellId' => 'c' ),
'integrated_edit_field82' => array( 'location' => 'section13',
'cellId' => 'c' ),
'section15' => array( 'location' => 'section13',
'cellId' => 'c' ),
'integrated_edit_field64' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field65' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field66' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field67' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field68' => array( 'location' => 'section14',
'cellId' => 'c1' ),
'integrated_edit_field69' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'integrated_edit_field70' => array( 'location' => 'section15',
'cellId' => 'c1' ),
'integrated_edit_field71' => array( 'location' => 'section16',
'cellId' => 'c1' ),
'integrated_edit_field72' => array( 'location' => 'section16',
'cellId' => 'c1' ),
'integrated_edit_field73' => array( 'location' => 'section16',
'cellId' => 'c1' ),
'integrated_edit_field74' => array( 'location' => 'section16',
'cellId' => 'c1' ),
'integrated_edit_field77' => array( 'location' => 'section17',
'cellId' => 'c1' ),
'integrated_edit_field78' => array( 'location' => 'section17',
'cellId' => 'c1' ),
'integrated_edit_field79' => array( 'location' => 'section17',
'cellId' => 'c1' ),
'integrated_edit_field80' => array( 'location' => 'section17',
'cellId' => 'c1' ),
'integrated_edit_field81' => array( 'location' => 'section17',
'cellId' => 'c1' ),
'integrated_edit_field83' => array( 'location' => 'section18',
'cellId' => 'c1' ),
'integrated_edit_field84' => array( 'location' => 'section18',
'cellId' => 'c1' ),
'integrated_edit_field85' => array( 'location' => 'section19',
'cellId' => 'c1' ),
'integrated_edit_field87' => array( 'location' => 'section19',
'cellId' => 'c1' ),
'integrated_edit_field86' => array( 'location' => 'section19',
'cellId' => 'c1' ),
'integrated_edit_field88' => array( 'location' => 'section19',
'cellId' => 'c1' ),
'integrated_edit_field89' => array( 'location' => 'section19',
'cellId' => 'c1' ),
'integrated_edit_field90' => array( 'location' => 'section19',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field53' ),
'tabs' => array( 'tabs' ),
'section' => array( 'section',
'section1',
'section2',
'section3',
'section4',
'section5',
'section6',
'section7',
'section8',
'section9',
'section10',
'section11',
'section12',
'section13',
'section14',
'section15' ),
'edit_field' => array( 'integrated_edit_field30',
'integrated_edit_field33' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'integrated_edit_field53',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ),
'section' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'section2',
'section5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1',
'section3',
'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section6',
'section7',
'section8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section9',
'section10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34',
'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field47' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section11' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section12' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section13' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section11',
'section14',
'integrated_edit_field75',
'integrated_edit_field76' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section12',
'section13',
'integrated_edit_field82',
'section15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section14' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section15' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field69',
'integrated_edit_field70' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section16' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section17' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section18' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field83',
'integrated_edit_field84' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section19' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field85',
'integrated_edit_field87',
'integrated_edit_field86',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'integrated_edit_field53',
'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ),
array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'section',
'section2',
'section5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c3',
'items' => array( 'section1',
'section3',
'section4' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section6',
'section7',
'section8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section9',
'section10' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34',
'integrated_edit_field35' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field47' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field54' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section12' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section13' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section11',
'section14',
'integrated_edit_field75',
'integrated_edit_field76' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section12',
'section13',
'integrated_edit_field82',
'section15' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section14' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section15' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field69',
'integrated_edit_field70' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section16' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section17' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section18' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field83',
'integrated_edit_field84' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section19' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field85',
'integrated_edit_field87',
'integrated_edit_field86',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field' => array( 'field' => 'lama_perkawinan_1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'lama_perkawinan_2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'lama_perkawinan_3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'anak_perkawinan_1',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'anak_perkawinan_2',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'anak_perkawinan_3',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'Libido',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'Frekwensi_koitus',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'Dispareuni',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'Orgasmus',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'Reflux_Post_Coital',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'Ejakulasi_Dini',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'Ejakulasi_Nocturnal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'Ejakulasi_Nyeri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'Puber',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'Masturbasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'Koitus_pranikah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'Lain_lain',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'Peny_Hub_Seksual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'Hernia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'Hidrokel',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'Trauma',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'Kelainan_bawaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'Penyakit_Paru_kronis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'Penyakit_hidung_kronis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'Tuberkulosa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'Diabetes_mellitus',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'Gondongan_parotitis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'Penyakit_Saraf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'Panas_dlm_6_bln',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'Saudara_kandung_suami',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'Saudara_kandung_istri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'Pekerjaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'Keluarga',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'Rokok',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'Alkohol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'Obat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'Celana ketat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'Bahan_kimia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'KU',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'KU',
'table' => 'andrologi',
'type' => 3 ) ),
'integrated_edit_field42' => array( 'field' => 'TB',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'CM',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'BB',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'KG',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'Tensi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'Pertumbuhan_distribusi_rambut',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'Kumis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'Jenggot',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'Mata',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'Hidung',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field52' => array( 'field' => 'Leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'ginecomastia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'PERUT',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'INGUINAL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field57' => array( 'field' => 'kubitus (valganus / varus)',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field58' => array( 'field' => 'Rentangan tangan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => ' Rambut axilla',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'Cor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'Hepar',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field62' => array( 'field' => 'Pulmo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field63' => array( 'field' => 'Lien',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field64' => array( 'field' => 'Penis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field65' => array( 'field' => 'Muara_Urethra',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field66' => array( 'field' => 'Skrotum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field67' => array( 'field' => 'Pubis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field68' => array( 'field' => 'Pola_Pubis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field69' => array( 'field' => 'Interna_Kanan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field70' => array( 'field' => 'Interna_Kiri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field71' => array( 'field' => 'Posisi_Testis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'Volume',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'Konsistensi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'Nyeri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'VAS_DEFERENS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'FUNICULUS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'EPIDIDYMIS_Ukuran',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'EPIDIDYMIS_Konsistensi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'EPIDIDYMIS_Kistik',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'EPIDIDYMIS_Nyeri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'EPIDIDYMIS_Permukaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field82' => array( 'field' => 'VARIKOKEL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field83' => array( 'field' => 'Prostat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field84' => array( 'field' => 'V_Seminalis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field85' => array( 'field' => 'lab_ke',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field86' => array( 'field' => 'lab_tgl',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field87' => array( 'field' => 'no_reg_lab',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field88' => array( 'field' => 'kesan_lab',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field89' => array( 'field' => 'Diagnosis_Banding',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field90' => array( 'field' => 'Rencana',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Anamnesis',
'type' => 0 ),
array( 'text' => 'Status Saat ini',
'type' => 0 ),
array( 'text' => 'Genitalia',
'type' => 0 ),
array( 'text' => 'Laboratorium',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section13',
'section19' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Perkawinan',
'type' => 0 ),
'location' => 'section2' ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Perkembangan Seksual',
'type' => 0 ),
'location' => 'section3' ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Riwayat Penyakit',
'type' => 0 ),
'location' => 'section4' ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Status Keluarga',
'type' => 0 ),
'location' => 'section5' ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Lingkungan Sosial',
'type' => 0 ),
'location' => 'section6' ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Lain-Lain',
'type' => 0 ),
'location' => 'section7' ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'Penampilan',
'type' => 0 ),
'location' => 'section8' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'Gizi',
'type' => 0 ),
'location' => 'section9' ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'Kepala',
'type' => 0 ),
'location' => 'section10' ),
'section9' => array( 'type' => 'section',
'title' => array( 'text' => 'Dada',
'type' => 0 ),
'location' => 'section11' ),
'section10' => array( 'type' => 'section',
'title' => array( 'text' => 'Status Lainnya',
'type' => 0 ),
'location' => 'section12' ),
'section11' => array( 'type' => 'section',
'title' => array( 'text' => 'Eksterna',
'type' => 0 ),
'location' => 'section14' ),
'section12' => array( 'type' => 'section',
'title' => array( 'text' => 'Interna',
'type' => 0 ),
'location' => 'section15' ),
'section13' => array( 'type' => 'section',
'title' => array( 'text' => 'Testis',
'type' => 0 ),
'location' => 'section16' ),
'section14' => array( 'type' => 'section',
'title' => array( 'text' => 'Epididymis',
'type' => 0 ),
'location' => 'section17' ),
'section15' => array( 'type' => 'section',
'title' => array( 'text' => 'Rectal Taucher',
'type' => 0 ),
'location' => 'section18' ),
'integrated_edit_field30' => array( 'field' => 'id_pasien',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field33' => array( 'field' => 'id_user',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true',
'users' => 'true' ) ),
'integrated_edit_field53' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>