<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'lama_perkawinan_1',
'lama_perkawinan_2',
'lama_perkawinan_3',
'anak_perkawinan_1',
'anak_perkawinan_2',
'anak_perkawinan_3',
'Libido',
'Frekwensi_koitus',
'Dispareuni',
'Orgasmus',
'Reflux_Post_Coital',
'Ejakulasi_Dini',
'Ejakulasi_Nocturnal',
'Ejakulasi_Nyeri',
'Puber',
'Masturbasi',
'Koitus_pranikah',
'Lain_lain',
'Peny_Hub_Seksual',
'Hernia',
'Hidrokel',
'Trauma',
'Kelainan_bawaan',
'Penyakit_Paru_kronis',
'Penyakit_hidung_kronis',
'Tuberkulosa',
'Diabetes_mellitus',
'Gondongan_parotitis',
'Penyakit_Saraf',
'Panas_dlm_6_bln',
'Status_keluarga',
'Saudara_kandung_suami',
'Saudara_kandung_istri',
'Lingkungan_sosial',
'Pekerjaan',
'Keluarga',
'Rokok',
'Alkohol',
'Obat',
'Celana ketat',
'Bahan_kimia',
'KU',
'TB',
'CM',
'BB',
'KG',
'Tensi',
'Pertumbuhan_distribusi_rambut',
'Kumis',
'Jenggot',
'Mata',
'Hidung',
'Leher',
'Dada',
'ginecomastia',
'PERUT',
'INGUINAL',
'kubitus (valganus / varus)',
'Rentangan tangan',
' Rambut axilla',
'Cor',
'Hepar',
'Pulmo',
'Lien',
'Penis',
'Muara_Urethra',
'Skrotum',
'Pubis',
'Pola_Pubis',
'Interna_Kanan',
'Interna_Kiri',
'Posisi_Testis',
'Volume',
'Konsistensi',
'Nyeri',
'VAS_DEFERENS',
'FUNICULUS',
'EPIDIDYMIS_Ukuran',
'EPIDIDYMIS_Konsistensi',
'EPIDIDYMIS_Kistik',
'EPIDIDYMIS_Nyeri',
'EPIDIDYMIS_Permukaan',
'VARIKOKEL',
'Prostat',
'V_Seminalis',
'lab_ke',
'lab_tgl',
'no_reg_lab',
'kesan_lab',
'Diagnosis_Banding',
'Rencana',
'id_pasien',
'id_user',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'lama_perkawinan_1' => array( 'import_field1' ),
'lama_perkawinan_2' => array( 'import_field2' ),
'lama_perkawinan_3' => array( 'import_field3' ),
'anak_perkawinan_1' => array( 'import_field4' ),
'anak_perkawinan_2' => array( 'import_field5' ),
'anak_perkawinan_3' => array( 'import_field6' ),
'Libido' => array( 'import_field7' ),
'Frekwensi_koitus' => array( 'import_field8' ),
'Dispareuni' => array( 'import_field9' ),
'Orgasmus' => array( 'import_field10' ),
'Reflux_Post_Coital' => array( 'import_field11' ),
'Ejakulasi_Dini' => array( 'import_field12' ),
'Ejakulasi_Nocturnal' => array( 'import_field13' ),
'Ejakulasi_Nyeri' => array( 'import_field14' ),
'Puber' => array( 'import_field15' ),
'Masturbasi' => array( 'import_field16' ),
'Koitus_pranikah' => array( 'import_field17' ),
'Lain_lain' => array( 'import_field18' ),
'Peny_Hub_Seksual' => array( 'import_field19' ),
'Hernia' => array( 'import_field20' ),
'Hidrokel' => array( 'import_field21' ),
'Trauma' => array( 'import_field22' ),
'Kelainan_bawaan' => array( 'import_field23' ),
'Penyakit_Paru_kronis' => array( 'import_field24' ),
'Penyakit_hidung_kronis' => array( 'import_field25' ),
'Tuberkulosa' => array( 'import_field26' ),
'Diabetes_mellitus' => array( 'import_field27' ),
'Gondongan_parotitis' => array( 'import_field28' ),
'Penyakit_Saraf' => array( 'import_field29' ),
'Panas_dlm_6_bln' => array( 'import_field30' ),
'Status_keluarga' => array( 'import_field31' ),
'Saudara_kandung_suami' => array( 'import_field32' ),
'Saudara_kandung_istri' => array( 'import_field33' ),
'Lingkungan_sosial' => array( 'import_field34' ),
'Pekerjaan' => array( 'import_field35' ),
'Keluarga' => array( 'import_field36' ),
'Rokok' => array( 'import_field37' ),
'Alkohol' => array( 'import_field38' ),
'Obat' => array( 'import_field39' ),
'Celana ketat' => array( 'import_field40' ),
'Bahan_kimia' => array( 'import_field41' ),
'KU' => array( 'import_field42' ),
'TB' => array( 'import_field43' ),
'CM' => array( 'import_field44' ),
'BB' => array( 'import_field45' ),
'KG' => array( 'import_field46' ),
'Tensi' => array( 'import_field47' ),
'Pertumbuhan_distribusi_rambut' => array( 'import_field48' ),
'Kumis' => array( 'import_field49' ),
'Jenggot' => array( 'import_field50' ),
'Mata' => array( 'import_field51' ),
'Hidung' => array( 'import_field52' ),
'Leher' => array( 'import_field53' ),
'Dada' => array( 'import_field54' ),
'ginecomastia' => array( 'import_field55' ),
'PERUT' => array( 'import_field56' ),
'INGUINAL' => array( 'import_field57' ),
'kubitus (valganus / varus)' => array( 'import_field58' ),
'Rentangan tangan' => array( 'import_field59' ),
' Rambut axilla' => array( 'import_field60' ),
'Cor' => array( 'import_field61' ),
'Hepar' => array( 'import_field62' ),
'Pulmo' => array( 'import_field63' ),
'Lien' => array( 'import_field64' ),
'Penis' => array( 'import_field65' ),
'Muara_Urethra' => array( 'import_field66' ),
'Skrotum' => array( 'import_field67' ),
'Pubis' => array( 'import_field68' ),
'Pola_Pubis' => array( 'import_field69' ),
'Interna_Kanan' => array( 'import_field70' ),
'Interna_Kiri' => array( 'import_field71' ),
'Posisi_Testis' => array( 'import_field72' ),
'Volume' => array( 'import_field73' ),
'Konsistensi' => array( 'import_field74' ),
'Nyeri' => array( 'import_field75' ),
'VAS_DEFERENS' => array( 'import_field76' ),
'FUNICULUS' => array( 'import_field77' ),
'EPIDIDYMIS_Ukuran' => array( 'import_field78' ),
'EPIDIDYMIS_Konsistensi' => array( 'import_field79' ),
'EPIDIDYMIS_Kistik' => array( 'import_field80' ),
'EPIDIDYMIS_Nyeri' => array( 'import_field81' ),
'EPIDIDYMIS_Permukaan' => array( 'import_field82' ),
'VARIKOKEL' => array( 'import_field83' ),
'Prostat' => array( 'import_field84' ),
'V_Seminalis' => array( 'import_field85' ),
'lab_ke' => array( 'import_field86' ),
'lab_tgl' => array( 'import_field87' ),
'no_reg_lab' => array( 'import_field88' ),
'kesan_lab' => array( 'import_field89' ),
'Diagnosis_Banding' => array( 'import_field90' ),
'Rencana' => array( 'import_field91' ),
'id_pasien' => array( 'import_field' ),
'id_user' => array( 'import_field92' ),
'Nomor_Rm' => array( 'import_field93' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field',
'import_field92',
'import_field93' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid',
'import_field63' => 'grid',
'import_field64' => 'grid',
'import_field65' => 'grid',
'import_field66' => 'grid',
'import_field67' => 'grid',
'import_field68' => 'grid',
'import_field69' => 'grid',
'import_field70' => 'grid',
'import_field71' => 'grid',
'import_field72' => 'grid',
'import_field73' => 'grid',
'import_field74' => 'grid',
'import_field75' => 'grid',
'import_field76' => 'grid',
'import_field77' => 'grid',
'import_field78' => 'grid',
'import_field79' => 'grid',
'import_field80' => 'grid',
'import_field81' => 'grid',
'import_field82' => 'grid',
'import_field83' => 'grid',
'import_field84' => 'grid',
'import_field85' => 'grid',
'import_field86' => 'grid',
'import_field87' => 'grid',
'import_field88' => 'grid',
'import_field89' => 'grid',
'import_field90' => 'grid',
'import_field91' => 'grid',
'import_field' => 'grid',
'import_field92' => 'grid',
'import_field93' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field',
'import_field92',
'import_field93' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68',
'import_field69',
'import_field70',
'import_field71',
'import_field72',
'import_field73',
'import_field74',
'import_field75',
'import_field76',
'import_field77',
'import_field78',
'import_field79',
'import_field80',
'import_field81',
'import_field82',
'import_field83',
'import_field84',
'import_field85',
'import_field86',
'import_field87',
'import_field88',
'import_field89',
'import_field90',
'import_field91',
'import_field',
'import_field92',
'import_field93' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'lama_perkawinan_1',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'lama_perkawinan_2',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'lama_perkawinan_3',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'anak_perkawinan_1',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'anak_perkawinan_2',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'anak_perkawinan_3',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Libido',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Frekwensi_koitus',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Dispareuni',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Orgasmus',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Reflux_Post_Coital',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Ejakulasi_Dini',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Ejakulasi_Nocturnal',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Ejakulasi_Nyeri',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Puber',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Masturbasi',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Koitus_pranikah',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Lain_lain',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Peny_Hub_Seksual',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Hernia',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'Hidrokel',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'Trauma',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'Kelainan_bawaan',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'Penyakit_Paru_kronis',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'Penyakit_hidung_kronis',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'Tuberkulosa',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Diabetes_mellitus',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Gondongan_parotitis',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Penyakit_Saraf',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'Panas_dlm_6_bln',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'Status_keluarga',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'Saudara_kandung_suami',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Saudara_kandung_istri',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'Lingkungan_sosial',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Pekerjaan',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Keluarga',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'Rokok',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'Alkohol',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'Obat',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'Celana ketat',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'Bahan_kimia',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'KU',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'TB',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'CM',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'BB',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'KG',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'Tensi',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'Pertumbuhan_distribusi_rambut',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'Kumis',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'Jenggot',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'Mata',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'Hidung',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'Leher',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'Dada',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'ginecomastia',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'PERUT',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'INGUINAL',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'kubitus (valganus / varus)',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'Rentangan tangan',
'type' => 'import_field' ),
'import_field60' => array( 'field' => ' Rambut axilla',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'Cor',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'Hepar',
'type' => 'import_field' ),
'import_field63' => array( 'field' => 'Pulmo',
'type' => 'import_field' ),
'import_field64' => array( 'field' => 'Lien',
'type' => 'import_field' ),
'import_field65' => array( 'field' => 'Penis',
'type' => 'import_field' ),
'import_field66' => array( 'field' => 'Muara_Urethra',
'type' => 'import_field' ),
'import_field67' => array( 'field' => 'Skrotum',
'type' => 'import_field' ),
'import_field68' => array( 'field' => 'Pubis',
'type' => 'import_field' ),
'import_field69' => array( 'field' => 'Pola_Pubis',
'type' => 'import_field' ),
'import_field70' => array( 'field' => 'Interna_Kanan',
'type' => 'import_field' ),
'import_field71' => array( 'field' => 'Interna_Kiri',
'type' => 'import_field' ),
'import_field72' => array( 'field' => 'Posisi_Testis',
'type' => 'import_field' ),
'import_field73' => array( 'field' => 'Volume',
'type' => 'import_field' ),
'import_field74' => array( 'field' => 'Konsistensi',
'type' => 'import_field' ),
'import_field75' => array( 'field' => 'Nyeri',
'type' => 'import_field' ),
'import_field76' => array( 'field' => 'VAS_DEFERENS',
'type' => 'import_field' ),
'import_field77' => array( 'field' => 'FUNICULUS',
'type' => 'import_field' ),
'import_field78' => array( 'field' => 'EPIDIDYMIS_Ukuran',
'type' => 'import_field' ),
'import_field79' => array( 'field' => 'EPIDIDYMIS_Konsistensi',
'type' => 'import_field' ),
'import_field80' => array( 'field' => 'EPIDIDYMIS_Kistik',
'type' => 'import_field' ),
'import_field81' => array( 'field' => 'EPIDIDYMIS_Nyeri',
'type' => 'import_field' ),
'import_field82' => array( 'field' => 'EPIDIDYMIS_Permukaan',
'type' => 'import_field' ),
'import_field83' => array( 'field' => 'VARIKOKEL',
'type' => 'import_field' ),
'import_field84' => array( 'field' => 'Prostat',
'type' => 'import_field' ),
'import_field85' => array( 'field' => 'V_Seminalis',
'type' => 'import_field' ),
'import_field86' => array( 'field' => 'lab_ke',
'type' => 'import_field' ),
'import_field87' => array( 'field' => 'lab_tgl',
'type' => 'import_field' ),
'import_field88' => array( 'field' => 'no_reg_lab',
'type' => 'import_field' ),
'import_field89' => array( 'field' => 'kesan_lab',
'type' => 'import_field' ),
'import_field90' => array( 'field' => 'Diagnosis_Banding',
'type' => 'import_field' ),
'import_field91' => array( 'field' => 'Rencana',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field92' => array( 'field' => 'id_user',
'type' => 'import_field' ),
'import_field93' => array( 'field' => 'Nomor_Rm',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>