<?php
			$optionsArray = array( 'totals' => array( 'Id_bedah' => array( 'totalsType' => '' ),
'Keluhan Utama' => array( 'totalsType' => '' ),
'Keluhan Tambahan' => array( 'totalsType' => '' ),
'Riwayat Penyakit Sekarang' => array( 'totalsType' => '' ),
'Riwayat Penyakit Dahulu' => array( 'totalsType' => '' ),
'Riwayat Penyakit Keluarga' => array( 'totalsType' => '' ),
'Riwayat Alergi' => array( 'totalsType' => '' ),
'Riwayat Pengobatan' => array( 'totalsType' => '' ),
'Riwayat Kebiasaan' => array( 'totalsType' => '' ),
'Pemeriksaan Umum' => array( 'totalsType' => '' ),
'Pemeriksaan Fisik' => array( 'totalsType' => '' ),
'Foto Klinis' => array( 'totalsType' => '' ),
'CT-SCAN' => array( 'totalsType' => '' ),
'MRI' => array( 'totalsType' => '' ),
'Patologi Anatomi' => array( 'totalsType' => '' ),
'status lokalis' => array( 'totalsType' => '' ),
'resume' => array( 'totalsType' => '' ),
'Diagnosis' => array( 'totalsType' => '' ),
'Diagnosis Banding' => array( 'totalsType' => '' ),
'Diagnosis Plan' => array( 'totalsType' => '' ),
'Terapi Medikamentosa' => array( 'totalsType' => '' ),
'Terapi Non Medikamentosa / Operatif' => array( 'totalsType' => '' ),
'Monitoring' => array( 'totalsType' => '' ),
'Edukasi' => array( 'totalsType' => '' ),
'Prognosis' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'nomor_rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Id_bedah',
'Keluhan Utama',
'Keluhan Tambahan',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Pemeriksaan Umum',
'Pemeriksaan Fisik',
'Diagnosis Plan',
'Monitoring',
'Edukasi',
'Prognosis',
'Foto Klinis',
'CT-SCAN',
'MRI',
'Patologi Anatomi',
'status lokalis',
'resume',
'Diagnosis',
'Diagnosis Banding',
'Terapi Medikamentosa',
'Terapi Non Medikamentosa / Operatif',
'id_pasien',
'id_user',
'nomor_rm' ),
'exportFields' => array( 'Keluhan Utama',
'Keluhan Tambahan',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'status lokalis',
'resume',
'Diagnosis',
'Diagnosis Banding',
'Terapi Medikamentosa',
'Terapi Non Medikamentosa / Operatif',
'Pemeriksaan Umum',
'Pemeriksaan Fisik',
'Diagnosis Plan',
'Monitoring',
'Edukasi',
'Prognosis',
'Foto Klinis',
'CT-SCAN',
'MRI',
'Patologi Anatomi',
'id_pasien',
'id_user',
'nomor_rm',
'Id_bedah' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Id_bedah' => array( 'export_field' ),
'Keluhan Utama' => array( 'export_field1' ),
'Keluhan Tambahan' => array( 'export_field2' ),
'Riwayat Penyakit Sekarang' => array( 'export_field3' ),
'Riwayat Penyakit Dahulu' => array( 'export_field4' ),
'Riwayat Penyakit Keluarga' => array( 'export_field5' ),
'Riwayat Alergi' => array( 'export_field6' ),
'Riwayat Pengobatan' => array( 'export_field7' ),
'Riwayat Kebiasaan' => array( 'export_field8' ),
'Pemeriksaan Umum' => array( 'export_field9' ),
'Pemeriksaan Fisik' => array( 'export_field10' ),
'Diagnosis Plan' => array( 'export_field11' ),
'Monitoring' => array( 'export_field12' ),
'Edukasi' => array( 'export_field13' ),
'Prognosis' => array( 'export_field14' ),
'Foto Klinis' => array( 'export_field15' ),
'CT-SCAN' => array( 'export_field16' ),
'MRI' => array( 'export_field17' ),
'Patologi Anatomi' => array( 'export_field18' ),
'status lokalis' => array( 'export_field24' ),
'resume' => array( 'export_field26' ),
'Diagnosis' => array( 'export_field27' ),
'Diagnosis Banding' => array( 'export_field28' ),
'Terapi Medikamentosa' => array( 'export_field29' ),
'Terapi Non Medikamentosa / Operatif' => array( 'export_field30' ),
'id_pasien' => array( 'export_field19' ),
'id_user' => array( 'export_field20' ),
'nomor_rm' => array( 'export_field21' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field24',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field24' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field24',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field19',
'export_field20',
'export_field21' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field24',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Id_bedah',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Keluhan Utama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Keluhan Tambahan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Riwayat Penyakit Sekarang',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Riwayat Penyakit Dahulu',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Riwayat Penyakit Keluarga',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Riwayat Alergi',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Riwayat Pengobatan',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Riwayat Kebiasaan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Pemeriksaan Umum',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Pemeriksaan Fisik',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Diagnosis Plan',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Monitoring',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Edukasi',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Prognosis',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Foto Klinis',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'CT-SCAN',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'MRI',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Patologi Anatomi',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'status lokalis',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'resume',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Diagnosis',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Diagnosis Banding',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Terapi Medikamentosa',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Terapi Non Medikamentosa / Operatif',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'id_pasien',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'id_user',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'nomor_rm',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>