<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Id_bedah',
'Keluhan Utama',
'Keluhan Tambahan',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Pemeriksaan Umum',
'Pemeriksaan Fisik',
'Diagnosis Plan',
'Monitoring',
'Edukasi',
'Prognosis',
'Foto Klinis',
'CT-SCAN',
'MRI',
'Patologi Anatomi',
'status lokalis',
'resume',
'Diagnosis',
'Diagnosis Banding',
'Terapi Medikamentosa',
'Terapi Non Medikamentosa / Operatif',
'id_pasien',
'id_user',
'nomor_rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Id_bedah' => array( 'import_field' ),
'Keluhan Utama' => array( 'import_field1' ),
'Keluhan Tambahan' => array( 'import_field2' ),
'Riwayat Penyakit Sekarang' => array( 'import_field3' ),
'Riwayat Penyakit Dahulu' => array( 'import_field4' ),
'Riwayat Penyakit Keluarga' => array( 'import_field5' ),
'Riwayat Alergi' => array( 'import_field6' ),
'Riwayat Pengobatan' => array( 'import_field7' ),
'Riwayat Kebiasaan' => array( 'import_field8' ),
'Pemeriksaan Umum' => array( 'import_field9' ),
'Pemeriksaan Fisik' => array( 'import_field10' ),
'Diagnosis Plan' => array( 'import_field11' ),
'Monitoring' => array( 'import_field12' ),
'Edukasi' => array( 'import_field13' ),
'Prognosis' => array( 'import_field14' ),
'Foto Klinis' => array( 'import_field15' ),
'CT-SCAN' => array( 'import_field16' ),
'MRI' => array( 'import_field17' ),
'Patologi Anatomi' => array( 'import_field18' ),
'status lokalis' => array( 'import_field24' ),
'resume' => array( 'import_field26' ),
'Diagnosis' => array( 'import_field27' ),
'Diagnosis Banding' => array( 'import_field28' ),
'Terapi Medikamentosa' => array( 'import_field29' ),
'Terapi Non Medikamentosa / Operatif' => array( 'import_field30' ),
'id_pasien' => array( 'import_field19' ),
'id_user' => array( 'import_field20' ),
'nomor_rm' => array( 'import_field21' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field24',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field24' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field24',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field19',
'import_field20',
'import_field21' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field24',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Id_bedah',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Keluhan Utama',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Keluhan Tambahan',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Riwayat Penyakit Sekarang',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Riwayat Penyakit Dahulu',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Riwayat Penyakit Keluarga',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Riwayat Alergi',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Riwayat Pengobatan',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Riwayat Kebiasaan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Pemeriksaan Umum',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Pemeriksaan Fisik',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Diagnosis Plan',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Monitoring',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Edukasi',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Prognosis',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Foto Klinis',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'CT-SCAN',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'MRI',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Patologi Anatomi',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'status lokalis',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'resume',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Diagnosis',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Diagnosis Banding',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Terapi Medikamentosa',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'Terapi Non Medikamentosa / Operatif',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'id_user',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'nomor_rm',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>