<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'identitas_pasien' => array( 'preview' => true ),
'users' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Id_bedah' => array( 'totalsType' => '' ),
'Keluhan Utama' => array( 'totalsType' => '' ),
'Keluhan Tambahan' => array( 'totalsType' => '' ),
'Riwayat Penyakit Sekarang' => array( 'totalsType' => '' ),
'Riwayat Penyakit Dahulu' => array( 'totalsType' => '' ),
'Riwayat Penyakit Keluarga' => array( 'totalsType' => '' ),
'Riwayat Alergi' => array( 'totalsType' => '' ),
'Riwayat Pengobatan' => array( 'totalsType' => '' ),
'Riwayat Kebiasaan' => array( 'totalsType' => '' ),
'Pemeriksaan Umum' => array( 'totalsType' => '' ),
'Pemeriksaan Fisik' => array( 'totalsType' => '' ),
'Foto Klinis' => array( 'totalsType' => '' ),
'CT-SCAN' => array( 'totalsType' => '' ),
'MRI' => array( 'totalsType' => '' ),
'Patologi Anatomi' => array( 'totalsType' => '' ),
'status lokalis' => array( 'totalsType' => '' ),
'resume' => array( 'totalsType' => '' ),
'Diagnosis' => array( 'totalsType' => '' ),
'Diagnosis Banding' => array( 'totalsType' => '' ),
'Diagnosis Plan' => array( 'totalsType' => '' ),
'Terapi Medikamentosa' => array( 'totalsType' => '' ),
'Terapi Non Medikamentosa / Operatif' => array( 'totalsType' => '' ),
'Monitoring' => array( 'totalsType' => '' ),
'Edukasi' => array( 'totalsType' => '' ),
'Prognosis' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'nomor_rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan Utama',
'nomor_rm',
'Id_bedah' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'CT-SCAN',
'Id_bedah',
'nomor_rm',
'id_user',
'id_pasien',
'status lokalis',
'resume',
'Terapi Non Medikamentosa / Operatif',
'Terapi Medikamentosa',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Keluarga',
'Riwayat Penyakit Dahulu',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Riwayat Alergi',
'Prognosis',
'Pemeriksaan Umum',
'Pemeriksaan Fisik',
'Patologi Anatomi',
'Monitoring',
'MRI',
'Keluhan Utama',
'Keluhan Tambahan',
'Foto Klinis',
'Edukasi',
'Diagnosis Plan',
'Diagnosis Banding',
'Diagnosis' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Keluhan Utama' => array( 'simple_grid_field1',
'simple_grid_field2' ),
'nomor_rm' => array( 'simple_grid_field21',
'simple_grid_field22' ),
'Id_bedah' => array( 'simple_grid_field',
'simple_grid_field3' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => true,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options' ),
'above-grid' => array( 'add',
'inline_add',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'master_info' ),
'grid' => array( 'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field22',
'simple_grid_field21',
'simple_grid_field3',
'simple_grid_field',
'grid_inline_cancel' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'master_info' => 'top',
'simple_grid_field2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field' => 'grid',
'grid_inline_cancel' => 'grid' ),
'itemLocations' => array( 'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'filter_panel' => 3,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'search_panel_field' => array( 'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field6',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field7',
'search_panel_field8',
'search_panel_field20',
'search_panel_field',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field12',
'search_panel_field1',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27' ),
'-' => array( '-3',
'-',
'-1',
'-2',
'-4' ),
'advsearch_link' => array( 'advsearch_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'filter_panel' => array( 'filter_panel' ),
'logo' => array( 'logo1' ),
'master_info' => array( 'master_info' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field21',
'simple_grid_field' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field22',
'simple_grid_field3' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Utama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'nomor_rm_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Id_bedah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'inline_cancel' ),
'items' => array( 'grid_inline_cancel' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Utama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'nomor_rm_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Id_bedah_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Keluhan Utama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Keluhan Utama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'nomor_rm',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'nomor_rm',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Id_bedah',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Id_bedah',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_inline_cancel' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'-4',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-3',
'export',
'-2',
'import' ) ),
'search_panel_field11' => array( 'field' => 'Patologi Anatomi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'Monitoring',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'MRI',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'Id_bedah',
'type' => 'search_panel_field',
'required' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field6',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field2' => array( 'field' => 'Diagnosis Banding',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'Diagnosis Plan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'Edukasi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'Foto Klinis',
'type' => 'search_panel_field',
'required' => false ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array(  ) ),
'search_panel_field7' => array( 'field' => 'Keluhan Tambahan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'Keluhan Utama',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'Riwayat Penyakit Sekarang',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field' => array( 'field' => 'CT-SCAN',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'Pemeriksaan Umum',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'Prognosis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'Riwayat Alergi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'Riwayat Kebiasaan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'Riwayat Pengobatan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'Riwayat Penyakit Dahulu',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'Riwayat Penyakit Keluarga',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'Pemeriksaan Fisik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'Diagnosis',
'type' => 'search_panel_field',
'required' => false ),
'logo1' => array( 'type' => 'logo' ),
'-4' => array( 'type' => '-' ),
'search_panel_field21' => array( 'field' => 'Terapi Medikamentosa',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'Terapi Non Medikamentosa / Operatif',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'resume',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'status lokalis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'id_pasien',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field26' => array( 'field' => 'id_user',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field27' => array( 'field' => 'nomor_rm',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true',
'users' => 'true' ) ),
'simple_grid_field1' => array( 'field' => 'Keluhan Utama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan Utama' ),
'simple_grid_field21' => array( 'field' => 'nomor_rm',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'nomor_rm' ),
'simple_grid_field' => array( 'field' => 'Id_bedah',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'Id_bedah' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>