<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'konseling',
'usul_pmrksaan',
'diagnosis',
'pmrksaan_pnunjang',
'cerviks_spekulum',
'dnding_vagina_spekulum',
'keluhan_tmbhan',
'rwyt_skrg',
'genital_ekterna',
'kavum_doglasi',
'adneksa_parametrium',
'korpus_uteri',
'rwyt_dulu',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_klg',
'rwyt_haid',
'rwyt_kebiasaan',
'rwyt_nikah',
'rwyt_sos',
'rwyt_prsalinan_satu',
'rwyt_prsalinan_dua',
'rwyt_prsalinan_tiga',
'rwyt_imunisasi',
'rwyt_prsalinan_empat',
'porsio',
'dnding_vagina_genital_interna',
'ekstremitas',
'abdomen',
'thorax',
'leher',
'kepala',
'temp',
'respi',
'nadi',
'TD',
'lila',
'bb',
'tb',
'gcs',
'ku',
'rwyt_kb',
'rwyt_mnyusui',
'keluhan_pertama',
'Nomor_Rm',
'name',
'username',
'email',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'konseling' => array( 'integrated_edit_field44' ),
'usul_pmrksaan' => array( 'integrated_edit_field43' ),
'diagnosis' => array( 'integrated_edit_field42' ),
'pmrksaan_pnunjang' => array( 'integrated_edit_field41' ),
'cerviks_spekulum' => array( 'integrated_edit_field39' ),
'dnding_vagina_spekulum' => array( 'integrated_edit_field37' ),
'keluhan_tmbhan' => array( 'integrated_edit_field2' ),
'rwyt_skrg' => array( 'integrated_edit_field3' ),
'genital_ekterna' => array( 'integrated_edit_field33' ),
'kavum_doglasi' => array( 'integrated_edit_field38' ),
'adneksa_parametrium' => array( 'integrated_edit_field34' ),
'korpus_uteri' => array( 'integrated_edit_field36' ),
'rwyt_dulu' => array( 'integrated_edit_field4' ),
'rwyt_alergi' => array( 'integrated_edit_field6' ),
'rwyt_pengobatan' => array( 'integrated_edit_field7' ),
'rwyt_klg' => array( 'integrated_edit_field5' ),
'rwyt_haid' => array( 'integrated_edit_field9' ),
'rwyt_kebiasaan' => array( 'integrated_edit_field8' ),
'rwyt_nikah' => array( 'integrated_edit_field10' ),
'rwyt_sos' => array( 'integrated_edit_field11' ),
'rwyt_prsalinan_satu' => array( 'integrated_edit_field12' ),
'rwyt_prsalinan_dua' => array( 'integrated_edit_field13' ),
'rwyt_prsalinan_tiga' => array( 'integrated_edit_field14' ),
'rwyt_imunisasi' => array( 'integrated_edit_field' ),
'rwyt_prsalinan_empat' => array( 'integrated_edit_field15' ),
'porsio' => array( 'integrated_edit_field35' ),
'dnding_vagina_genital_interna' => array( 'integrated_edit_field17' ),
'ekstremitas' => array( 'integrated_edit_field32' ),
'abdomen' => array( 'integrated_edit_field31' ),
'thorax' => array( 'integrated_edit_field30' ),
'leher' => array( 'integrated_edit_field29' ),
'kepala' => array( 'integrated_edit_field28' ),
'temp' => array( 'integrated_edit_field27' ),
'respi' => array( 'integrated_edit_field26' ),
'nadi' => array( 'integrated_edit_field25' ),
'TD' => array( 'integrated_edit_field24' ),
'lila' => array( 'integrated_edit_field23' ),
'bb' => array( 'integrated_edit_field22' ),
'tb' => array( 'integrated_edit_field21' ),
'gcs' => array( 'integrated_edit_field20' ),
'ku' => array( 'integrated_edit_field19' ),
'rwyt_kb' => array( 'integrated_edit_field18' ),
'rwyt_mnyusui' => array( 'integrated_edit_field16' ),
'keluhan_pertama' => array( 'integrated_edit_field1' ),
'Nomor_Rm' => array( 'integrated_edit_field47' ),
'name' => array( 'integrated_edit_field49' ),
'username' => array( 'integrated_edit_field50' ),
'email' => array( 'integrated_edit_field51' ),
'Nama' => array( 'integrated_edit_field53' ),
'Alamat' => array( 'integrated_edit_field54' ),
'Umur' => array( 'integrated_edit_field55' ),
'Status_Perkawinan' => array( 'integrated_edit_field56' ),
'Jenis Kelamin' => array( 'integrated_edit_field57' ),
'Suku_Ras' => array( 'integrated_edit_field58' ),
'Agama' => array( 'integrated_edit_field59' ),
'Kerja' => array( 'integrated_edit_field60' ),
'Tanggal_MRS' => array( 'integrated_edit_field61' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'master_info',
'section',
'section4',
'tabs' ),
'section1' => array( 'integrated_edit_field1',
'integrated_edit_field2' ),
'section9' => array( 'integrated_edit_field33' ),
'section2' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field18' ),
'section3' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'section4' => array( 'section2',
'section1',
'section3' ),
'section5' => array( 'integrated_edit_field41' ),
'section6' => array( 'integrated_edit_field42' ),
'section7' => array( 'integrated_edit_field43' ),
'section8' => array( 'integrated_edit_field44' ),
'section10' => array( 'integrated_edit_field17',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field34',
'integrated_edit_field38' ),
'section11' => array( 'integrated_edit_field37',
'integrated_edit_field39' ),
'section' => array( 'integrated_edit_field50',
'integrated_edit_field49',
'integrated_edit_field47',
'integrated_edit_field51' ),
'section12' => array( 'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field58',
'integrated_edit_field60',
'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field59',
'integrated_edit_field61' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'section' => 'grid',
'section4' => 'grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field33' => 'section9',
'integrated_edit_field3' => 'section2',
'integrated_edit_field4' => 'section2',
'integrated_edit_field5' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field9' => 'section2',
'integrated_edit_field' => 'section2',
'integrated_edit_field10' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field12' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field14' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field19' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field21' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field26' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field29' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field31' => 'section3',
'integrated_edit_field32' => 'section3',
'section2' => 'section4',
'section1' => 'section4',
'section3' => 'section4',
'integrated_edit_field41' => 'section5',
'integrated_edit_field42' => 'section6',
'integrated_edit_field43' => 'section7',
'integrated_edit_field44' => 'section8',
'integrated_edit_field17' => 'section10',
'integrated_edit_field35' => 'section10',
'integrated_edit_field36' => 'section10',
'integrated_edit_field34' => 'section10',
'integrated_edit_field38' => 'section10',
'integrated_edit_field37' => 'section11',
'integrated_edit_field39' => 'section11',
'integrated_edit_field50' => 'section',
'integrated_edit_field49' => 'section',
'integrated_edit_field47' => 'section',
'integrated_edit_field51' => 'section',
'integrated_edit_field53' => 'section12',
'integrated_edit_field54' => 'section12',
'integrated_edit_field56' => 'section12',
'integrated_edit_field58' => 'section12',
'integrated_edit_field60' => 'section12',
'integrated_edit_field55' => 'section12',
'integrated_edit_field57' => 'section12',
'integrated_edit_field59' => 'section12',
'integrated_edit_field61' => 'section12' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field31' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field32' => array( 'location' => 'section3',
'cellId' => 'c' ),
'section2' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section4',
'cellId' => 'c' ),
'section3' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field41' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field44' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field35' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field36' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field39' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field50' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field49' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field51' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field53' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field54' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field56' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field58' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field60' => array( 'location' => 'section12',
'cellId' => 'c1' ),
'integrated_edit_field55' => array( 'location' => 'section12',
'cellId' => 'c' ),
'integrated_edit_field57' => array( 'location' => 'section12',
'cellId' => 'c' ),
'integrated_edit_field59' => array( 'location' => 'section12',
'cellId' => 'c' ),
'integrated_edit_field61' => array( 'location' => 'section12',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'integrated_edit_field' => array( 'integrated_edit_field44',
'integrated_edit_field43',
'integrated_edit_field42',
'integrated_edit_field41',
'integrated_edit_field39',
'integrated_edit_field37',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field33',
'integrated_edit_field38',
'integrated_edit_field34',
'integrated_edit_field36',
'integrated_edit_field4',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field5',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field',
'integrated_edit_field15',
'integrated_edit_field35',
'integrated_edit_field17',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field16',
'integrated_edit_field1',
'integrated_edit_field47',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61' ),
'section' => array( 'section3',
'section1',
'section2',
'section',
'section4' ),
'tabs' => array( 'tabs' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'section',
'section4',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1',
'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field34',
'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section11' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37',
'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50',
'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47',
'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section12' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field58',
'integrated_edit_field60' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field59',
'integrated_edit_field61' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'section',
'section4',
'tabs' ) ),
'c' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section1',
'section3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field44' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field34',
'integrated_edit_field38' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37',
'integrated_edit_field39' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field50',
'integrated_edit_field49' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field47',
'integrated_edit_field51' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section12' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field56',
'integrated_edit_field58',
'integrated_edit_field60' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field59',
'integrated_edit_field61' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'ginekologi',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array(  ) ),
'integrated_edit_field44' => array( 'field' => 'konseling',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'usul_pmrksaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'usul_pmrksaan',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field42' => array( 'field' => 'diagnosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'pmrksaan_pnunjang',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pmrksaan_pnunjang',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field39' => array( 'field' => 'cerviks_spekulum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'dnding_vagina_spekulum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_tmbhan',
'table' => 'ginekologi',
'type' => 3 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Spekulum Vagina',
'type' => 0 ),
'location' => 'section11' ),
'integrated_edit_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_skrg',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field33' => array( 'field' => 'genital_ekterna',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Genitalia Eksterna',
'type' => 0 ),
'location' => 'section9',
'mobileDisplay' => '' ),
'integrated_edit_field38' => array( 'field' => 'kavum_doglasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'adneksa_parametrium',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'korpus_uteri',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_dulu',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_alergi',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_pengobatan',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_klg',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'rwyt_haid',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_haid',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kebiasaan',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'rwyt_nikah',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_nikah',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'rwyt_sos',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_sos',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'rwyt_prsalinan_satu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_prsalinan_satu',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'rwyt_prsalinan_satu',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field13' => array( 'field' => 'rwyt_prsalinan_dua',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_prsalinan_dua',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'rwyt_prsalinan_dua',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field14' => array( 'field' => 'rwyt_prsalinan_tiga',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_prsalinan_tiga',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'rwyt_prsalinan_tiga',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field' => array( 'field' => 'rwyt_imunisasi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_imunisasi',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'rwyt_prsalinan_empat',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_prsalinan_empat',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'rwyt_prsalinan_empat',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field35' => array( 'field' => 'porsio',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'porsio',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'dnding_vagina_genital_interna',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Genitalia Interna',
'type' => 0 ),
'location' => 'section10' ),
'integrated_edit_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'kepala',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'temp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'respi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'respi',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field25' => array( 'field' => 'nadi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'TD',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'lila',
'type' => 'integrated_edit_field',
'orientation' => 0,
'placeholder' => array( 'field' => 'lila',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field22' => array( 'field' => 'bb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'bb',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'bb',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field21' => array( 'field' => 'tb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tb',
'table' => 'ginekologi',
'type' => 3 ),
'placeholder' => array( 'field' => 'tb',
'table' => 'ginekologi',
'type' => 5 ) ),
'integrated_edit_field20' => array( 'field' => 'gcs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'gcs',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'ku',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ku',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field18' => array( 'field' => 'rwyt_kb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kb',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'rwyt_mnyusui',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_mnyusui',
'table' => 'ginekologi',
'type' => 3 ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'ANAMNESIS',
'type' => 0 ),
array( 'text' => 'RIWAYAT PENYAKIT',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN FISIK UMUM',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN GINEKOLOGI',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN PENUNJANG YANG LALU',
'type' => 0 ),
array( 'text' => 'DIAGNOSIS',
'type' => 0 ),
array( 'text' => 'RENCANA TATALAKSANA',
'type' => 0 ),
array( 'text' => 'KONSELING',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section3',
'section4',
'section5',
'section6',
'section7',
'section8' ) ),
'integrated_edit_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'integrated_edit_field47' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field53' => array( 'field' => 'Nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field54' => array( 'field' => 'Alamat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'Umur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field57' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field58' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field59' => array( 'field' => 'Agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'Kerja',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Informasi DM',
'type' => 0 ),
'location' => 'section' ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Identitas Pasien',
'type' => 0 ),
'location' => 'section12' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>