<?php
			$optionsArray = array( 'totals' => array( 'id_gine' => array( 'totalsType' => '' ),
'keluhan_pertama' => array( 'totalsType' => '' ),
'keluhan_tmbhan' => array( 'totalsType' => '' ),
'rwyt_skrg' => array( 'totalsType' => '' ),
'rwyt_dulu' => array( 'totalsType' => '' ),
'rwyt_klg' => array( 'totalsType' => '' ),
'rwyt_alergi' => array( 'totalsType' => '' ),
'rwyt_pengobatan' => array( 'totalsType' => '' ),
'rwyt_kebiasaan' => array( 'totalsType' => '' ),
'rwyt_haid' => array( 'totalsType' => '' ),
'rwyt_nikah' => array( 'totalsType' => '' ),
'rwyt_sos' => array( 'totalsType' => '' ),
'rwyt_prsalinan_satu' => array( 'totalsType' => '' ),
'rwyt_prsalinan_dua' => array( 'totalsType' => '' ),
'rwyt_prsalinan_tiga' => array( 'totalsType' => '' ),
'rwyt_prsalinan_empat' => array( 'totalsType' => '' ),
'rwyt_mnyusui' => array( 'totalsType' => '' ),
'rwyt_imunisasi' => array( 'totalsType' => '' ),
'rwyt_kb' => array( 'totalsType' => '' ),
'ku' => array( 'totalsType' => '' ),
'gcs' => array( 'totalsType' => '' ),
'tb' => array( 'totalsType' => '' ),
'bb' => array( 'totalsType' => '' ),
'lila' => array( 'totalsType' => '' ),
'TD' => array( 'totalsType' => '' ),
'nadi' => array( 'totalsType' => '' ),
'respi' => array( 'totalsType' => '' ),
'temp' => array( 'totalsType' => '' ),
'kepala' => array( 'totalsType' => '' ),
'leher' => array( 'totalsType' => '' ),
'thorax' => array( 'totalsType' => '' ),
'abdomen' => array( 'totalsType' => '' ),
'ekstremitas' => array( 'totalsType' => '' ),
'genital_ekterna' => array( 'totalsType' => '' ),
'dnding_vagina_genital_interna' => array( 'totalsType' => '' ),
'porsio' => array( 'totalsType' => '' ),
'kavum_doglasi' => array( 'totalsType' => '' ),
'korpus_uteri' => array( 'totalsType' => '' ),
'adneksa_parametrium' => array( 'totalsType' => '' ),
'dnding_vagina_spekulum' => array( 'totalsType' => '' ),
'cerviks_spekulum' => array( 'totalsType' => '' ),
'pmrksaan_pnunjang' => array( 'totalsType' => '' ),
'diagnosis' => array( 'totalsType' => '' ),
'usul_pmrksaan' => array( 'totalsType' => '' ),
'konseling' => array( 'totalsType' => '' ),
'id_mhs' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Kerja' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_haid',
'rwyt_nikah',
'rwyt_sos',
'rwyt_prsalinan_satu',
'rwyt_prsalinan_dua',
'rwyt_prsalinan_tiga',
'rwyt_prsalinan_empat',
'rwyt_mnyusui',
'rwyt_imunisasi',
'rwyt_kb',
'ku',
'gcs',
'tb',
'bb',
'lila',
'TD',
'nadi',
'respi',
'temp',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'genital_ekterna',
'adneksa_parametrium',
'porsio',
'korpus_uteri',
'dnding_vagina_spekulum',
'kavum_doglasi',
'cerviks_spekulum',
'pmrksaan_pnunjang',
'diagnosis',
'usul_pmrksaan',
'konseling',
'dnding_vagina_genital_interna',
'id_gine',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'exportFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_haid',
'rwyt_nikah',
'rwyt_sos',
'rwyt_prsalinan_satu',
'rwyt_prsalinan_dua',
'rwyt_prsalinan_tiga',
'rwyt_prsalinan_empat',
'rwyt_mnyusui',
'rwyt_imunisasi',
'rwyt_kb',
'ku',
'gcs',
'tb',
'bb',
'lila',
'TD',
'nadi',
'respi',
'temp',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'genital_ekterna',
'porsio',
'korpus_uteri',
'kavum_doglasi',
'pmrksaan_pnunjang',
'diagnosis',
'usul_pmrksaan',
'konseling',
'dnding_vagina_genital_interna',
'adneksa_parametrium',
'dnding_vagina_spekulum',
'cerviks_spekulum',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id_gine',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'export_field1' ),
'keluhan_tmbhan' => array( 'export_field2' ),
'rwyt_skrg' => array( 'export_field3' ),
'rwyt_dulu' => array( 'export_field4' ),
'rwyt_klg' => array( 'export_field5' ),
'rwyt_alergi' => array( 'export_field6' ),
'rwyt_pengobatan' => array( 'export_field7' ),
'rwyt_kebiasaan' => array( 'export_field8' ),
'rwyt_haid' => array( 'export_field9' ),
'rwyt_nikah' => array( 'export_field10' ),
'rwyt_sos' => array( 'export_field11' ),
'rwyt_prsalinan_satu' => array( 'export_field12' ),
'rwyt_prsalinan_dua' => array( 'export_field13' ),
'rwyt_prsalinan_tiga' => array( 'export_field14' ),
'rwyt_prsalinan_empat' => array( 'export_field15' ),
'rwyt_mnyusui' => array( 'export_field16' ),
'rwyt_imunisasi' => array( 'export_field17' ),
'rwyt_kb' => array( 'export_field18' ),
'ku' => array( 'export_field19' ),
'gcs' => array( 'export_field20' ),
'tb' => array( 'export_field21' ),
'bb' => array( 'export_field22' ),
'lila' => array( 'export_field23' ),
'TD' => array( 'export_field24' ),
'nadi' => array( 'export_field25' ),
'respi' => array( 'export_field26' ),
'temp' => array( 'export_field27' ),
'kepala' => array( 'export_field28' ),
'leher' => array( 'export_field29' ),
'thorax' => array( 'export_field30' ),
'abdomen' => array( 'export_field31' ),
'ekstremitas' => array( 'export_field32' ),
'genital_ekterna' => array( 'export_field33' ),
'adneksa_parametrium' => array( 'export_field34' ),
'porsio' => array( 'export_field35' ),
'korpus_uteri' => array( 'export_field36' ),
'dnding_vagina_spekulum' => array( 'export_field37' ),
'kavum_doglasi' => array( 'export_field38' ),
'cerviks_spekulum' => array( 'export_field39' ),
'pmrksaan_pnunjang' => array( 'export_field41' ),
'diagnosis' => array( 'export_field42' ),
'usul_pmrksaan' => array( 'export_field43' ),
'konseling' => array( 'export_field44' ),
'dnding_vagina_genital_interna' => array( 'export_field' ),
'id_gine' => array( 'export_field40' ),
'id_mhs' => array( 'export_field45' ),
'id_pasien' => array( 'export_field46' ),
'Nomor_Rm' => array( 'export_field47' ),
'id' => array( 'export_field48' ),
'name' => array( 'export_field49' ),
'username' => array( 'export_field50' ),
'email' => array( 'export_field51' ),
'Id_Pasien1' => array( 'export_field52' ),
'Nama' => array( 'export_field53' ),
'Alamat' => array( 'export_field54' ),
'Umur' => array( 'export_field55' ),
'Status_Perkawinan' => array( 'export_field56' ),
'Jenis Kelamin' => array( 'export_field57' ),
'Suku_Ras' => array( 'export_field58' ),
'Agama' => array( 'export_field59' ),
'Kerja' => array( 'export_field60' ),
'Tanggal_MRS' => array( 'export_field61' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field35',
'export_field36',
'export_field38',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field',
'export_field34',
'export_field37',
'export_field39',
'export_field45',
'export_field46',
'export_field47',
'export_field40',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field38' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field' => 'grid',
'export_field34' => 'grid',
'export_field37' => 'grid',
'export_field39' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field40' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field',
'export_field40',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field35',
'export_field36',
'export_field38',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field',
'export_field34',
'export_field37',
'export_field39',
'export_field45',
'export_field46',
'export_field47',
'export_field40',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'rwyt_klg',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'rwyt_haid',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'rwyt_nikah',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'rwyt_sos',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'rwyt_prsalinan_satu',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'rwyt_prsalinan_dua',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'rwyt_prsalinan_tiga',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'rwyt_prsalinan_empat',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'rwyt_mnyusui',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'rwyt_imunisasi',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'rwyt_kb',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'ku',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'gcs',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'tb',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'bb',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'lila',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'TD',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'nadi',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'respi',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'temp',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'kepala',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'leher',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'thorax',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'abdomen',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'ekstremitas',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'genital_ekterna',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'adneksa_parametrium',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'porsio',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'korpus_uteri',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'dnding_vagina_spekulum',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'kavum_doglasi',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'cerviks_spekulum',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'pmrksaan_pnunjang',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'diagnosis',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'usul_pmrksaan',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'konseling',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'dnding_vagina_genital_interna',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'id_gine',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'id_mhs',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'id_pasien',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'Nomor_Rm',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'name',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'username',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'Id_Pasien1',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'Nama',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'Alamat',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'Umur',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'Status_Perkawinan',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'Jenis Kelamin',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'Suku_Ras',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'Agama',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'Kerja',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'Tanggal_MRS',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false,
'fileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) );
		?>