<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'users' => array( 'preview' => true ),
'identitas_pasien' => array( 'preview' => true ) ),
'totals' => array( 'id_gine' => array( 'totalsType' => '' ),
'keluhan_pertama' => array( 'totalsType' => '' ),
'keluhan_tmbhan' => array( 'totalsType' => '' ),
'rwyt_skrg' => array( 'totalsType' => '' ),
'rwyt_dulu' => array( 'totalsType' => '' ),
'rwyt_klg' => array( 'totalsType' => '' ),
'rwyt_alergi' => array( 'totalsType' => '' ),
'rwyt_pengobatan' => array( 'totalsType' => '' ),
'rwyt_kebiasaan' => array( 'totalsType' => '' ),
'rwyt_haid' => array( 'totalsType' => '' ),
'rwyt_nikah' => array( 'totalsType' => '' ),
'rwyt_sos' => array( 'totalsType' => '' ),
'rwyt_prsalinan_satu' => array( 'totalsType' => '' ),
'rwyt_prsalinan_dua' => array( 'totalsType' => '' ),
'rwyt_prsalinan_tiga' => array( 'totalsType' => '' ),
'rwyt_prsalinan_empat' => array( 'totalsType' => '' ),
'rwyt_mnyusui' => array( 'totalsType' => '' ),
'rwyt_imunisasi' => array( 'totalsType' => '' ),
'rwyt_kb' => array( 'totalsType' => '' ),
'ku' => array( 'totalsType' => '' ),
'gcs' => array( 'totalsType' => '' ),
'tb' => array( 'totalsType' => '' ),
'bb' => array( 'totalsType' => '' ),
'lila' => array( 'totalsType' => '' ),
'TD' => array( 'totalsType' => '' ),
'nadi' => array( 'totalsType' => '' ),
'respi' => array( 'totalsType' => '' ),
'temp' => array( 'totalsType' => '' ),
'kepala' => array( 'totalsType' => '' ),
'leher' => array( 'totalsType' => '' ),
'thorax' => array( 'totalsType' => '' ),
'abdomen' => array( 'totalsType' => '' ),
'ekstremitas' => array( 'totalsType' => '' ),
'genital_ekterna' => array( 'totalsType' => '' ),
'dnding_vagina_genital_interna' => array( 'totalsType' => '' ),
'porsio' => array( 'totalsType' => '' ),
'kavum_doglasi' => array( 'totalsType' => '' ),
'korpus_uteri' => array( 'totalsType' => '' ),
'adneksa_parametrium' => array( 'totalsType' => '' ),
'dnding_vagina_spekulum' => array( 'totalsType' => '' ),
'cerviks_spekulum' => array( 'totalsType' => '' ),
'pmrksaan_pnunjang' => array( 'totalsType' => '' ),
'diagnosis' => array( 'totalsType' => '' ),
'usul_pmrksaan' => array( 'totalsType' => '' ),
'konseling' => array( 'totalsType' => '' ),
'id_mhs' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_haid',
'rwyt_nikah',
'rwyt_sos',
'rwyt_prsalinan_satu',
'rwyt_prsalinan_dua',
'rwyt_prsalinan_tiga',
'rwyt_prsalinan_empat',
'rwyt_mnyusui',
'rwyt_imunisasi',
'rwyt_kb',
'ku',
'gcs',
'tb',
'bb',
'lila',
'TD',
'nadi',
'respi',
'temp',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'genital_ekterna',
'porsio',
'korpus_uteri',
'kavum_doglasi',
'pmrksaan_pnunjang',
'diagnosis',
'usul_pmrksaan',
'konseling',
'dnding_vagina_genital_interna',
'adneksa_parametrium',
'dnding_vagina_spekulum',
'cerviks_spekulum',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id_gine' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'simple_grid_field1',
'simple_grid_field48' ),
'keluhan_tmbhan' => array( 'simple_grid_field2',
'simple_grid_field49' ),
'rwyt_skrg' => array( 'simple_grid_field3',
'simple_grid_field50' ),
'rwyt_dulu' => array( 'simple_grid_field4',
'simple_grid_field51' ),
'rwyt_klg' => array( 'simple_grid_field5',
'simple_grid_field52' ),
'rwyt_alergi' => array( 'simple_grid_field6',
'simple_grid_field53' ),
'rwyt_pengobatan' => array( 'simple_grid_field7',
'simple_grid_field54' ),
'rwyt_kebiasaan' => array( 'simple_grid_field8',
'simple_grid_field55' ),
'rwyt_haid' => array( 'simple_grid_field9',
'simple_grid_field56' ),
'rwyt_nikah' => array( 'simple_grid_field10',
'simple_grid_field57' ),
'rwyt_sos' => array( 'simple_grid_field11',
'simple_grid_field58' ),
'rwyt_prsalinan_satu' => array( 'simple_grid_field12',
'simple_grid_field59' ),
'rwyt_prsalinan_dua' => array( 'simple_grid_field13',
'simple_grid_field60' ),
'rwyt_prsalinan_tiga' => array( 'simple_grid_field14',
'simple_grid_field61' ),
'rwyt_prsalinan_empat' => array( 'simple_grid_field15',
'simple_grid_field62' ),
'rwyt_mnyusui' => array( 'simple_grid_field16',
'simple_grid_field63' ),
'rwyt_imunisasi' => array( 'simple_grid_field17',
'simple_grid_field64' ),
'rwyt_kb' => array( 'simple_grid_field18',
'simple_grid_field65' ),
'ku' => array( 'simple_grid_field19',
'simple_grid_field66' ),
'gcs' => array( 'simple_grid_field20',
'simple_grid_field67' ),
'tb' => array( 'simple_grid_field21',
'simple_grid_field68' ),
'bb' => array( 'simple_grid_field22',
'simple_grid_field69' ),
'lila' => array( 'simple_grid_field23',
'simple_grid_field70' ),
'TD' => array( 'simple_grid_field24',
'simple_grid_field71' ),
'nadi' => array( 'simple_grid_field25',
'simple_grid_field72' ),
'respi' => array( 'simple_grid_field26',
'simple_grid_field73' ),
'temp' => array( 'simple_grid_field27',
'simple_grid_field74' ),
'kepala' => array( 'simple_grid_field28',
'simple_grid_field75' ),
'leher' => array( 'simple_grid_field29',
'simple_grid_field76' ),
'thorax' => array( 'simple_grid_field30',
'simple_grid_field77' ),
'abdomen' => array( 'simple_grid_field31',
'simple_grid_field78' ),
'ekstremitas' => array( 'simple_grid_field32',
'simple_grid_field79' ),
'genital_ekterna' => array( 'simple_grid_field33',
'simple_grid_field80' ),
'porsio' => array( 'simple_grid_field35',
'simple_grid_field81' ),
'korpus_uteri' => array( 'simple_grid_field36',
'simple_grid_field82' ),
'kavum_doglasi' => array( 'simple_grid_field38',
'simple_grid_field83' ),
'pmrksaan_pnunjang' => array( 'simple_grid_field41',
'simple_grid_field84' ),
'diagnosis' => array( 'simple_grid_field42',
'simple_grid_field85' ),
'usul_pmrksaan' => array( 'simple_grid_field43',
'simple_grid_field86' ),
'konseling' => array( 'simple_grid_field44',
'simple_grid_field87' ),
'dnding_vagina_genital_interna' => array( 'simple_grid_field',
'simple_grid_field88' ),
'adneksa_parametrium' => array( 'simple_grid_field34',
'simple_grid_field89' ),
'dnding_vagina_spekulum' => array( 'simple_grid_field37',
'simple_grid_field90' ),
'cerviks_spekulum' => array( 'simple_grid_field39',
'simple_grid_field91' ),
'id_mhs' => array( 'simple_grid_field45',
'simple_grid_field92' ),
'id_pasien' => array( 'simple_grid_field46',
'simple_grid_field93' ),
'Nomor_Rm' => array( 'simple_grid_field47',
'simple_grid_field94' ),
'id_gine' => array( 'simple_grid_field40',
'simple_grid_field95' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info' ),
'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field48',
'simple_grid_field1',
'simple_grid_field49',
'simple_grid_field2',
'simple_grid_field50',
'simple_grid_field3',
'simple_grid_field51',
'simple_grid_field4',
'simple_grid_field52',
'simple_grid_field5',
'simple_grid_field53',
'simple_grid_field6',
'simple_grid_field54',
'simple_grid_field7',
'simple_grid_field55',
'simple_grid_field8',
'simple_grid_field56',
'simple_grid_field9',
'simple_grid_field57',
'simple_grid_field10',
'simple_grid_field58',
'simple_grid_field11',
'simple_grid_field59',
'simple_grid_field12',
'simple_grid_field60',
'simple_grid_field13',
'simple_grid_field61',
'simple_grid_field14',
'simple_grid_field62',
'simple_grid_field15',
'simple_grid_field63',
'simple_grid_field16',
'simple_grid_field64',
'simple_grid_field17',
'simple_grid_field65',
'simple_grid_field18',
'simple_grid_field66',
'simple_grid_field19',
'simple_grid_field67',
'simple_grid_field20',
'simple_grid_field68',
'simple_grid_field21',
'simple_grid_field69',
'simple_grid_field22',
'simple_grid_field70',
'simple_grid_field23',
'simple_grid_field71',
'simple_grid_field24',
'simple_grid_field72',
'simple_grid_field25',
'simple_grid_field73',
'simple_grid_field26',
'simple_grid_field74',
'simple_grid_field27',
'simple_grid_field75',
'simple_grid_field28',
'simple_grid_field76',
'simple_grid_field29',
'simple_grid_field77',
'simple_grid_field30',
'simple_grid_field78',
'simple_grid_field31',
'simple_grid_field79',
'simple_grid_field32',
'simple_grid_field80',
'simple_grid_field33',
'simple_grid_field81',
'simple_grid_field35',
'simple_grid_field82',
'simple_grid_field36',
'simple_grid_field83',
'simple_grid_field38',
'simple_grid_field84',
'simple_grid_field41',
'simple_grid_field85',
'simple_grid_field42',
'simple_grid_field86',
'simple_grid_field43',
'simple_grid_field87',
'simple_grid_field44',
'simple_grid_field88',
'simple_grid_field',
'simple_grid_field89',
'simple_grid_field34',
'simple_grid_field90',
'simple_grid_field37',
'simple_grid_field91',
'simple_grid_field39',
'simple_grid_field92',
'simple_grid_field45',
'simple_grid_field93',
'simple_grid_field46',
'simple_grid_field94',
'simple_grid_field47',
'simple_grid_field95',
'simple_grid_field40' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'simple_grid_field48' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field40' => 'grid' ),
'itemLocations' => array( 'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field47' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'master_info' => array( 'master_info' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field38',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field',
'simple_grid_field34',
'simple_grid_field37',
'simple_grid_field39',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field40' ),
'grid_field_label' => array( 'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'keluhan_pertama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'keluhan_tmbhan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_skrg_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_dulu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_klg_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_alergi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_pengobatan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_kebiasaan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_haid_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_nikah_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_sos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_prsalinan_satu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_prsalinan_dua_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_prsalinan_tiga_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_prsalinan_empat_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_mnyusui_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_imunisasi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_kb_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'ku_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'gcs_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'tb_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'bb_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'lila_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'TD_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'nadi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'respi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'temp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'kepala_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'leher_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'thorax_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'abdomen_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'ekstremitas_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'genital_ekterna_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'porsio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'korpus_uteri_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'kavum_doglasi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'pmrksaan_pnunjang_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'diagnosis_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'usul_pmrksaan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'konseling_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'dnding_vagina_genital_interna_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'adneksa_parametrium_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'dnding_vagina_spekulum_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'cerviks_spekulum_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'id_mhs_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'id_pasien_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 0 ),
'tags' => array( 'id_gine_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'keluhan_pertama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'keluhan_tmbhan_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_skrg_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_dulu_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_klg_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_alergi_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_pengobatan_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_kebiasaan_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_haid_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_nikah_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_sos_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_prsalinan_satu_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_prsalinan_dua_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_prsalinan_tiga_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_prsalinan_empat_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_mnyusui_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_imunisasi_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_kb_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'ku_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'gcs_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'tb_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'bb_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'lila_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'TD_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'nadi_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'respi_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'temp_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'kepala_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'leher_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'thorax_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'abdomen_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'ekstremitas_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'genital_ekterna_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'porsio_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'korpus_uteri_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'kavum_doglasi_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'pmrksaan_pnunjang_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'diagnosis_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'usul_pmrksaan_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'konseling_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'dnding_vagina_genital_interna_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'adneksa_parametrium_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'dnding_vagina_spekulum_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'cerviks_spekulum_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'id_mhs_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'id_pasien_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 1 ),
'tags' => array( 'id_gine_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 48,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field47' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ),
array( 'cell' => 'footcell_field47' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'keluhan_pertama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'keluhan_pertama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'keluhan_tmbhan',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'keluhan_tmbhan',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'rwyt_skrg',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'rwyt_skrg',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'rwyt_dulu',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'rwyt_dulu',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'rwyt_klg',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'rwyt_klg',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'rwyt_alergi',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'rwyt_alergi',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'rwyt_pengobatan',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'rwyt_pengobatan',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'rwyt_kebiasaan',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'rwyt_kebiasaan',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'rwyt_haid',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'rwyt_haid',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'rwyt_nikah',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'rwyt_nikah',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'rwyt_sos',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'rwyt_sos',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'rwyt_prsalinan_satu',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'rwyt_prsalinan_satu',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'rwyt_prsalinan_dua',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'rwyt_prsalinan_dua',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'rwyt_prsalinan_tiga',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'rwyt_prsalinan_tiga',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'rwyt_prsalinan_empat',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'rwyt_prsalinan_empat',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'rwyt_mnyusui',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'rwyt_mnyusui',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'rwyt_imunisasi',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'rwyt_imunisasi',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'rwyt_kb',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'rwyt_kb',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'ku',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'ku',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'gcs',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'gcs',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'tb',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'tb',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'bb',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'bb',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'lila',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'lila',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'TD',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'TD',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'nadi',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'nadi',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'respi',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'respi',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'temp',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'temp',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'kepala',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'kepala',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'leher',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'leher',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'thorax',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'thorax',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'abdomen',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'abdomen',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'ekstremitas',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'ekstremitas',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'genital_ekterna',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'genital_ekterna',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'porsio',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'porsio',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'korpus_uteri',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'korpus_uteri',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'kavum_doglasi',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'kavum_doglasi',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'pmrksaan_pnunjang',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'pmrksaan_pnunjang',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'diagnosis',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'diagnosis',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'usul_pmrksaan',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'usul_pmrksaan',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'konseling',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'konseling',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'dnding_vagina_genital_interna',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'dnding_vagina_genital_interna',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'adneksa_parametrium',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'adneksa_parametrium',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'dnding_vagina_spekulum',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'dnding_vagina_spekulum',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'cerviks_spekulum',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'cerviks_spekulum',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'id_mhs',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'id_mhs',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'id_pasien',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'id_pasien',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field47' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'id_gine',
'columnName' => 'field' ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'id_gine',
'columnName' => 'field' ),
'footcell_field47' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'users' => 'true',
'identitas_pasien' => 'true' ) ),
'simple_grid_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'keluhan_pertama' ),
'simple_grid_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'keluhan_tmbhan' ),
'simple_grid_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_skrg' ),
'simple_grid_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_dulu' ),
'simple_grid_field5' => array( 'field' => 'rwyt_klg',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_klg' ),
'simple_grid_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_alergi' ),
'simple_grid_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_pengobatan' ),
'simple_grid_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_kebiasaan' ),
'simple_grid_field9' => array( 'field' => 'rwyt_haid',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_haid' ),
'simple_grid_field10' => array( 'field' => 'rwyt_nikah',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_nikah' ),
'simple_grid_field11' => array( 'field' => 'rwyt_sos',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_sos' ),
'simple_grid_field12' => array( 'field' => 'rwyt_prsalinan_satu',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_prsalinan_satu' ),
'simple_grid_field13' => array( 'field' => 'rwyt_prsalinan_dua',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_prsalinan_dua' ),
'simple_grid_field14' => array( 'field' => 'rwyt_prsalinan_tiga',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_prsalinan_tiga' ),
'simple_grid_field15' => array( 'field' => 'rwyt_prsalinan_empat',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_prsalinan_empat' ),
'simple_grid_field16' => array( 'field' => 'rwyt_mnyusui',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_mnyusui' ),
'simple_grid_field17' => array( 'field' => 'rwyt_imunisasi',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_imunisasi' ),
'simple_grid_field18' => array( 'field' => 'rwyt_kb',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_kb' ),
'simple_grid_field19' => array( 'field' => 'ku',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'ku' ),
'simple_grid_field20' => array( 'field' => 'gcs',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'gcs' ),
'simple_grid_field21' => array( 'field' => 'tb',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'tb' ),
'simple_grid_field22' => array( 'field' => 'bb',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'bb' ),
'simple_grid_field23' => array( 'field' => 'lila',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'lila' ),
'simple_grid_field24' => array( 'field' => 'TD',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'TD' ),
'simple_grid_field25' => array( 'field' => 'nadi',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'nadi' ),
'simple_grid_field26' => array( 'field' => 'respi',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'respi' ),
'simple_grid_field27' => array( 'field' => 'temp',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'temp' ),
'simple_grid_field28' => array( 'field' => 'kepala',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'kepala' ),
'simple_grid_field29' => array( 'field' => 'leher',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'leher' ),
'simple_grid_field30' => array( 'field' => 'thorax',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'thorax' ),
'simple_grid_field31' => array( 'field' => 'abdomen',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'abdomen' ),
'simple_grid_field32' => array( 'field' => 'ekstremitas',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'ekstremitas' ),
'simple_grid_field33' => array( 'field' => 'genital_ekterna',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'genital_ekterna' ),
'simple_grid_field35' => array( 'field' => 'porsio',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'porsio' ),
'simple_grid_field36' => array( 'field' => 'korpus_uteri',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'korpus_uteri' ),
'simple_grid_field38' => array( 'field' => 'kavum_doglasi',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'kavum_doglasi' ),
'simple_grid_field41' => array( 'field' => 'pmrksaan_pnunjang',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'pmrksaan_pnunjang' ),
'simple_grid_field42' => array( 'field' => 'diagnosis',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'diagnosis' ),
'simple_grid_field43' => array( 'field' => 'usul_pmrksaan',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'usul_pmrksaan' ),
'simple_grid_field44' => array( 'field' => 'konseling',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'konseling' ),
'simple_grid_field' => array( 'field' => 'dnding_vagina_genital_interna',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'dnding_vagina_genital_interna' ),
'simple_grid_field34' => array( 'field' => 'adneksa_parametrium',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'adneksa_parametrium' ),
'simple_grid_field37' => array( 'field' => 'dnding_vagina_spekulum',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'dnding_vagina_spekulum' ),
'simple_grid_field39' => array( 'field' => 'cerviks_spekulum',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'cerviks_spekulum' ),
'simple_grid_field45' => array( 'field' => 'id_mhs',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'id_mhs' ),
'simple_grid_field46' => array( 'field' => 'id_pasien',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'id_pasien' ),
'simple_grid_field47' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'simple_grid_field40' => array( 'field' => 'id_gine',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'id_gine' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>