<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_haid',
'rwyt_nikah',
'rwyt_sos',
'rwyt_prsalinan_satu',
'rwyt_prsalinan_dua',
'rwyt_prsalinan_tiga',
'rwyt_prsalinan_empat',
'rwyt_mnyusui',
'rwyt_imunisasi',
'rwyt_kb',
'ku',
'gcs',
'tb',
'bb',
'lila',
'TD',
'nadi',
'respi',
'temp',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'genital_ekterna',
'adneksa_parametrium',
'porsio',
'korpus_uteri',
'dnding_vagina_spekulum',
'kavum_doglasi',
'cerviks_spekulum',
'pmrksaan_pnunjang',
'diagnosis',
'usul_pmrksaan',
'konseling',
'dnding_vagina_genital_interna',
'id_gine',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'import_field1' ),
'keluhan_tmbhan' => array( 'import_field2' ),
'rwyt_skrg' => array( 'import_field3' ),
'rwyt_dulu' => array( 'import_field4' ),
'rwyt_klg' => array( 'import_field5' ),
'rwyt_alergi' => array( 'import_field6' ),
'rwyt_pengobatan' => array( 'import_field7' ),
'rwyt_kebiasaan' => array( 'import_field8' ),
'rwyt_haid' => array( 'import_field9' ),
'rwyt_nikah' => array( 'import_field10' ),
'rwyt_sos' => array( 'import_field11' ),
'rwyt_prsalinan_satu' => array( 'import_field12' ),
'rwyt_prsalinan_dua' => array( 'import_field13' ),
'rwyt_prsalinan_tiga' => array( 'import_field14' ),
'rwyt_prsalinan_empat' => array( 'import_field15' ),
'rwyt_mnyusui' => array( 'import_field16' ),
'rwyt_imunisasi' => array( 'import_field17' ),
'rwyt_kb' => array( 'import_field18' ),
'ku' => array( 'import_field19' ),
'gcs' => array( 'import_field20' ),
'tb' => array( 'import_field21' ),
'bb' => array( 'import_field22' ),
'lila' => array( 'import_field23' ),
'TD' => array( 'import_field24' ),
'nadi' => array( 'import_field25' ),
'respi' => array( 'import_field26' ),
'temp' => array( 'import_field27' ),
'kepala' => array( 'import_field28' ),
'leher' => array( 'import_field29' ),
'thorax' => array( 'import_field30' ),
'abdomen' => array( 'import_field31' ),
'ekstremitas' => array( 'import_field32' ),
'genital_ekterna' => array( 'import_field33' ),
'adneksa_parametrium' => array( 'import_field34' ),
'porsio' => array( 'import_field35' ),
'korpus_uteri' => array( 'import_field36' ),
'dnding_vagina_spekulum' => array( 'import_field37' ),
'kavum_doglasi' => array( 'import_field38' ),
'cerviks_spekulum' => array( 'import_field39' ),
'pmrksaan_pnunjang' => array( 'import_field41' ),
'diagnosis' => array( 'import_field42' ),
'usul_pmrksaan' => array( 'import_field43' ),
'konseling' => array( 'import_field44' ),
'dnding_vagina_genital_interna' => array( 'import_field' ),
'id_gine' => array( 'import_field40' ),
'id_mhs' => array( 'import_field45' ),
'id_pasien' => array( 'import_field46' ),
'Nomor_Rm' => array( 'import_field47' ),
'id' => array( 'import_field48' ),
'name' => array( 'import_field49' ),
'username' => array( 'import_field50' ),
'email' => array( 'import_field51' ),
'Id_Pasien1' => array( 'import_field52' ),
'Nama' => array( 'import_field53' ),
'Alamat' => array( 'import_field54' ),
'Umur' => array( 'import_field55' ),
'Status_Perkawinan' => array( 'import_field56' ),
'Jenis Kelamin' => array( 'import_field57' ),
'Suku_Ras' => array( 'import_field58' ),
'Agama' => array( 'import_field59' ),
'Kerja' => array( 'import_field60' ),
'Tanggal_MRS' => array( 'import_field61' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field35',
'import_field36',
'import_field38',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field',
'import_field34',
'import_field37',
'import_field39',
'import_field45',
'import_field46',
'import_field47',
'import_field40',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field38' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field' => 'grid',
'import_field34' => 'grid',
'import_field37' => 'grid',
'import_field39' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field40' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field',
'import_field40',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field35',
'import_field36',
'import_field38',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field',
'import_field34',
'import_field37',
'import_field39',
'import_field45',
'import_field46',
'import_field47',
'import_field40',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'rwyt_klg',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'rwyt_haid',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'rwyt_nikah',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'rwyt_sos',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'rwyt_prsalinan_satu',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'rwyt_prsalinan_dua',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'rwyt_prsalinan_tiga',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'rwyt_prsalinan_empat',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'rwyt_mnyusui',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'rwyt_imunisasi',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'rwyt_kb',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'ku',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'gcs',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'tb',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'bb',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'lila',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'TD',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'nadi',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'respi',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'temp',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'kepala',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'leher',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'thorax',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'abdomen',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'ekstremitas',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'genital_ekterna',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'adneksa_parametrium',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'porsio',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'korpus_uteri',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'dnding_vagina_spekulum',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'kavum_doglasi',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'cerviks_spekulum',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'pmrksaan_pnunjang',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'diagnosis',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'usul_pmrksaan',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'konseling',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'dnding_vagina_genital_interna',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'id_gine',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'id_mhs',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'Nomor_Rm',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'name',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'username',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'Id_Pasien1',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'Nama',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'Alamat',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'Umur',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'Status_Perkawinan',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'Jenis Kelamin',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'Suku_Ras',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'Agama',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'Kerja',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'Tanggal_MRS',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>