<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'mata' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tht' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'andrologi' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'jiwa' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'resep' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'rujukan' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'kulit' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'pediatri' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'interna' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'ginekologi' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'resep_kacamata' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'mata1' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'obstetri' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'paru' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'bedah' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'neurologi' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'tht1' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Pekerjaan',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Nama' => array( 'integrated_edit_field1' ),
'Alamat' => array( 'integrated_edit_field2' ),
'Umur' => array( 'integrated_edit_field3' ),
'Status_Perkawinan' => array( 'integrated_edit_field4' ),
'Jenis Kelamin' => array( 'integrated_edit_field5' ),
'Suku_Ras' => array( 'integrated_edit_field6' ),
'Agama' => array( 'integrated_edit_field7' ),
'Pekerjaan' => array( 'integrated_edit_field8' ),
'Tanggal_MRS' => array( 'integrated_edit_field9' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'section',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'section' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid',
'details_preview3' => 'grid',
'details_preview4' => 'grid',
'details_preview5' => 'grid',
'details_preview6' => 'grid',
'details_preview7' => 'grid',
'details_preview8' => 'grid',
'details_preview9' => 'grid',
'details_preview10' => 'grid',
'details_preview11' => 'grid',
'details_preview12' => 'grid',
'details_preview13' => 'grid',
'details_preview14' => 'grid',
'details_preview15' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'view_pdf' => array( 'view_pdf' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'section' => array( 'section' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit',
'view_pdf' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field1' => array( 'field' => 'Nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'Alamat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'Umur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'Agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'Pekerjaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'view_pdf' => array( 'type' => 'view_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tht',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'mata',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'andrologi',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'jiwa',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'resep',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview5' => array( 'type' => 'details_preview',
'table' => 'rujukan',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview6' => array( 'type' => 'details_preview',
'table' => 'kulit',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview7' => array( 'type' => 'details_preview',
'table' => 'pediatri',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview8' => array( 'type' => 'details_preview',
'table' => 'interna',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview9' => array( 'type' => 'details_preview',
'table' => 'ginekologi',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview10' => array( 'type' => 'details_preview',
'table' => 'resep_kacamata',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview11' => array( 'type' => 'details_preview',
'table' => 'mata1',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview12' => array( 'type' => 'details_preview',
'table' => 'obstetri',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview13' => array( 'type' => 'details_preview',
'table' => 'paru',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview14' => array( 'type' => 'details_preview',
'table' => 'bedah',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'details_preview15' => array( 'type' => 'details_preview',
'table' => 'neurologi',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Identitas Pasien',
'type' => 0 ),
'location' => 'section' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>