<?php
			$optionsArray = array( 'details' => array( 'mata' => array( 'displayPreview' => 1 ),
'tht' => array( 'displayPreview' => 1 ),
'andrologi' => array( 'displayPreview' => 1 ),
'jiwa' => array( 'displayPreview' => 1 ),
'resep' => array( 'displayPreview' => 1 ),
'rujukan' => array( 'displayPreview' => 1 ),
'kulit' => array( 'displayPreview' => 1 ),
'pediatri' => array( 'displayPreview' => 1 ),
'interna' => array( 'displayPreview' => 1 ),
'ginekologi' => array( 'displayPreview' => 1 ),
'resep_kacamata' => array( 'displayPreview' => 1 ),
'mata1' => array( 'displayPreview' => 1 ),
'obstetri' => array( 'displayPreview' => 1 ),
'paru' => array( 'displayPreview' => 1 ),
'bedah' => array( 'displayPreview' => 1 ),
'neurologi' => array( 'displayPreview' => 1 ),
'tht1' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Pekerjaan',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'Nama' => array( 'integrated_edit_field' ),
'Alamat' => array( 'integrated_edit_field1' ),
'Umur' => array( 'integrated_edit_field2' ),
'Status_Perkawinan' => array( 'integrated_edit_field3' ),
'Jenis Kelamin' => array( 'integrated_edit_field4' ),
'Suku_Ras' => array( 'integrated_edit_field5' ),
'Agama' => array( 'integrated_edit_field6' ),
'Pekerjaan' => array( 'integrated_edit_field7' ),
'Tanggal_MRS' => array( 'integrated_edit_field8' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'details_preview2' => 'grid',
'details_preview3' => 'grid',
'details_preview4' => 'grid',
'details_preview5' => 'grid',
'details_preview6' => 'grid',
'details_preview7' => 'grid',
'details_preview8' => 'grid',
'details_preview9' => 'grid',
'details_preview10' => 'grid',
'details_preview11' => 'grid',
'details_preview12' => 'grid',
'details_preview13' => 'grid',
'details_preview14' => 'grid',
'details_preview15' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'details_preview15' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'details_preview',
'details_preview1',
'details_preview2',
'details_preview3',
'details_preview4',
'details_preview5',
'details_preview6',
'details_preview7',
'details_preview8',
'details_preview9',
'details_preview10',
'details_preview11',
'details_preview12',
'details_preview13',
'details_preview14',
'details_preview15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field' => array( 'field' => 'Nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'Alamat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'Umur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'Agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'Pekerjaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'tht',
'items' => array(  ),
'popup' => false ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'mata',
'items' => array(  ),
'popup' => false ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'andrologi',
'items' => array(  ),
'popup' => false ),
'details_preview3' => array( 'type' => 'details_preview',
'table' => 'jiwa',
'items' => array(  ),
'popup' => false ),
'details_preview4' => array( 'type' => 'details_preview',
'table' => 'resep',
'items' => array(  ),
'popup' => false ),
'details_preview5' => array( 'type' => 'details_preview',
'table' => 'rujukan',
'items' => array(  ),
'popup' => false ),
'details_preview6' => array( 'type' => 'details_preview',
'table' => 'kulit',
'items' => array(  ),
'popup' => false ),
'details_preview7' => array( 'type' => 'details_preview',
'table' => 'pediatri',
'items' => array(  ),
'popup' => false ),
'details_preview8' => array( 'type' => 'details_preview',
'table' => 'interna',
'items' => array(  ),
'popup' => false ),
'details_preview9' => array( 'type' => 'details_preview',
'table' => 'ginekologi',
'items' => array(  ),
'popup' => false ),
'details_preview10' => array( 'type' => 'details_preview',
'table' => 'resep_kacamata',
'items' => array(  ),
'popup' => false ),
'details_preview11' => array( 'type' => 'details_preview',
'table' => 'mata1',
'items' => array(  ),
'popup' => false ),
'details_preview12' => array( 'type' => 'details_preview',
'table' => 'obstetri',
'items' => array(  ),
'popup' => false ),
'details_preview13' => array( 'type' => 'details_preview',
'table' => 'paru',
'items' => array(  ),
'popup' => false ),
'details_preview14' => array( 'type' => 'details_preview',
'table' => 'bedah',
'items' => array(  ),
'popup' => false ),
'details_preview15' => array( 'type' => 'details_preview',
'table' => 'neurologi',
'items' => array(  ),
'popup' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>