<?php
			$optionsArray = array( 'totals' => array( 'id_interna' => array( 'totalsType' => '' ),
'keluhan_pertama' => array( 'totalsType' => '' ),
'keluhan_tmbhan' => array( 'totalsType' => '' ),
'rwyt_skrg' => array( 'totalsType' => '' ),
'rwyt_dulu' => array( 'totalsType' => '' ),
'rwyt_klg' => array( 'totalsType' => '' ),
'rwyt_alergi' => array( 'totalsType' => '' ),
'rwyt_pengobatan' => array( 'totalsType' => '' ),
'rwyt_kebiasaan' => array( 'totalsType' => '' ),
'rwyt_sos' => array( 'totalsType' => '' ),
'pem_umum_ku' => array( 'totalsType' => '' ),
'pem_umum_tb' => array( 'totalsType' => '' ),
'pem_umum_bb' => array( 'totalsType' => '' ),
'pem_umum_imt' => array( 'totalsType' => '' ),
'tanda_vital' => array( 'totalsType' => '' ),
'kepala' => array( 'totalsType' => '' ),
'leher' => array( 'totalsType' => '' ),
'thorax' => array( 'totalsType' => '' ),
'abdomen' => array( 'totalsType' => '' ),
'ekstremitas' => array( 'totalsType' => '' ),
'pmrksaan_pnunjang_lab' => array( 'totalsType' => '' ),
'pmrksaan_pnunjang_radiologi' => array( 'totalsType' => '' ),
'pmrksaan_pnunjang_lain' => array( 'totalsType' => '' ),
'id_mhs' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Kerja' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'pem_umum_ku',
'pem_umum_tb',
'rwyt_sos',
'pem_umum_bb',
'pem_umum_imt',
'tanda_vital',
'pmrksaan_pnunjang_lab',
'pmrksaan_pnunjang_radiologi',
'pmrksaan_pnunjang_lain',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'id_interna',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'exportFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_sos',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'pem_umum_ku',
'pem_umum_tb',
'pem_umum_bb',
'pem_umum_imt',
'tanda_vital',
'pmrksaan_pnunjang_lab',
'pmrksaan_pnunjang_radiologi',
'pmrksaan_pnunjang_lain',
'id_interna',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'export_field1' ),
'keluhan_tmbhan' => array( 'export_field2' ),
'rwyt_skrg' => array( 'export_field3' ),
'rwyt_dulu' => array( 'export_field4' ),
'rwyt_klg' => array( 'export_field5' ),
'rwyt_alergi' => array( 'export_field6' ),
'rwyt_pengobatan' => array( 'export_field7' ),
'rwyt_kebiasaan' => array( 'export_field8' ),
'pem_umum_ku' => array( 'export_field9' ),
'pem_umum_tb' => array( 'export_field10' ),
'rwyt_sos' => array( 'export_field11' ),
'pem_umum_bb' => array( 'export_field12' ),
'pem_umum_imt' => array( 'export_field13' ),
'tanda_vital' => array( 'export_field14' ),
'pmrksaan_pnunjang_lab' => array( 'export_field15' ),
'pmrksaan_pnunjang_radiologi' => array( 'export_field16' ),
'pmrksaan_pnunjang_lain' => array( 'export_field17' ),
'kepala' => array( 'export_field28' ),
'leher' => array( 'export_field29' ),
'thorax' => array( 'export_field30' ),
'abdomen' => array( 'export_field31' ),
'ekstremitas' => array( 'export_field32' ),
'id_interna' => array( 'export_field' ),
'id_mhs' => array( 'export_field18' ),
'id_pasien' => array( 'export_field19' ),
'Nomor_Rm' => array( 'export_field20' ),
'id' => array( 'export_field21' ),
'name' => array( 'export_field22' ),
'username' => array( 'export_field23' ),
'email' => array( 'export_field24' ),
'Id_Pasien1' => array( 'export_field25' ),
'Nama' => array( 'export_field26' ),
'Alamat' => array( 'export_field27' ),
'Umur' => array( 'export_field33' ),
'Status_Perkawinan' => array( 'export_field34' ),
'Jenis Kelamin' => array( 'export_field35' ),
'Suku_Ras' => array( 'export_field36' ),
'Agama' => array( 'export_field37' ),
'Kerja' => array( 'export_field38' ),
'Tanggal_MRS' => array( 'export_field39' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field9',
'export_field10',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field11' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field9',
'export_field10',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'rwyt_klg',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'pem_umum_ku',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'pem_umum_tb',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'rwyt_sos',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'pem_umum_bb',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'pem_umum_imt',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'tanda_vital',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'kepala',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'leher',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'thorax',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'abdomen',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'ekstremitas',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'id_interna',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'id_mhs',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'id_pasien',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Nomor_Rm',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'name',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'username',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Id_Pasien1',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Nama',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Alamat',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'Umur',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'Status_Perkawinan',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Jenis Kelamin',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'Suku_Ras',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'Agama',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'Kerja',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'Tanggal_MRS',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>