<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_interna',
'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_sos',
'pem_umum_ku',
'pem_umum_tb',
'pem_umum_bb',
'pem_umum_imt',
'tanda_vital',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'pmrksaan_pnunjang_lab',
'pmrksaan_pnunjang_radiologi',
'pmrksaan_pnunjang_lain',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_interna' => array( 'simple_grid_field',
'simple_grid_field40' ),
'keluhan_pertama' => array( 'simple_grid_field1',
'simple_grid_field41' ),
'keluhan_tmbhan' => array( 'simple_grid_field2',
'simple_grid_field42' ),
'rwyt_skrg' => array( 'simple_grid_field3',
'simple_grid_field43' ),
'rwyt_dulu' => array( 'simple_grid_field4',
'simple_grid_field44' ),
'rwyt_klg' => array( 'simple_grid_field5',
'simple_grid_field45' ),
'rwyt_alergi' => array( 'simple_grid_field6',
'simple_grid_field46' ),
'rwyt_pengobatan' => array( 'simple_grid_field7',
'simple_grid_field47' ),
'rwyt_kebiasaan' => array( 'simple_grid_field8',
'simple_grid_field48' ),
'rwyt_sos' => array( 'simple_grid_field9',
'simple_grid_field49' ),
'pem_umum_ku' => array( 'simple_grid_field10',
'simple_grid_field50' ),
'pem_umum_tb' => array( 'simple_grid_field11',
'simple_grid_field51' ),
'pem_umum_bb' => array( 'simple_grid_field12',
'simple_grid_field52' ),
'pem_umum_imt' => array( 'simple_grid_field13',
'simple_grid_field53' ),
'tanda_vital' => array( 'simple_grid_field14',
'simple_grid_field54' ),
'kepala' => array( 'simple_grid_field15',
'simple_grid_field55' ),
'leher' => array( 'simple_grid_field16',
'simple_grid_field56' ),
'thorax' => array( 'simple_grid_field17',
'simple_grid_field57' ),
'abdomen' => array( 'simple_grid_field18',
'simple_grid_field58' ),
'ekstremitas' => array( 'simple_grid_field19',
'simple_grid_field59' ),
'pmrksaan_pnunjang_lab' => array( 'simple_grid_field20',
'simple_grid_field60' ),
'pmrksaan_pnunjang_radiologi' => array( 'simple_grid_field21',
'simple_grid_field61' ),
'pmrksaan_pnunjang_lain' => array( 'simple_grid_field22',
'simple_grid_field62' ),
'id_mhs' => array( 'simple_grid_field23',
'simple_grid_field63' ),
'id_pasien' => array( 'simple_grid_field24',
'simple_grid_field64' ),
'Nomor_Rm' => array( 'simple_grid_field25',
'simple_grid_field65' ),
'id' => array( 'simple_grid_field26',
'simple_grid_field66' ),
'name' => array( 'simple_grid_field27',
'simple_grid_field67' ),
'username' => array( 'simple_grid_field28',
'simple_grid_field68' ),
'email' => array( 'simple_grid_field29',
'simple_grid_field69' ),
'Id_Pasien1' => array( 'simple_grid_field30',
'simple_grid_field70' ),
'Nama' => array( 'simple_grid_field31',
'simple_grid_field71' ),
'Alamat' => array( 'simple_grid_field32',
'simple_grid_field72' ),
'Umur' => array( 'simple_grid_field33',
'simple_grid_field73' ),
'Status_Perkawinan' => array( 'simple_grid_field34',
'simple_grid_field74' ),
'Jenis Kelamin' => array( 'simple_grid_field35',
'simple_grid_field75' ),
'Suku_Ras' => array( 'simple_grid_field36',
'simple_grid_field76' ),
'Agama' => array( 'simple_grid_field37',
'simple_grid_field77' ),
'Kerja' => array( 'simple_grid_field38',
'simple_grid_field78' ),
'Tanggal_MRS' => array( 'simple_grid_field39',
'simple_grid_field79' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'back_master',
'masterlist_header' ),
'above-grid' => array(  ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field40',
'simple_grid_field',
'simple_grid_field41',
'simple_grid_field1',
'simple_grid_field42',
'simple_grid_field2',
'simple_grid_field43',
'simple_grid_field3',
'simple_grid_field44',
'simple_grid_field4',
'simple_grid_field45',
'simple_grid_field5',
'simple_grid_field46',
'simple_grid_field6',
'simple_grid_field47',
'simple_grid_field7',
'simple_grid_field48',
'simple_grid_field8',
'simple_grid_field49',
'simple_grid_field9',
'simple_grid_field50',
'simple_grid_field10',
'simple_grid_field51',
'simple_grid_field11',
'simple_grid_field52',
'simple_grid_field12',
'simple_grid_field53',
'simple_grid_field13',
'simple_grid_field54',
'simple_grid_field14',
'simple_grid_field55',
'simple_grid_field15',
'simple_grid_field56',
'simple_grid_field16',
'simple_grid_field57',
'simple_grid_field17',
'simple_grid_field58',
'simple_grid_field18',
'simple_grid_field59',
'simple_grid_field19',
'simple_grid_field60',
'simple_grid_field20',
'simple_grid_field61',
'simple_grid_field21',
'simple_grid_field62',
'simple_grid_field22',
'simple_grid_field63',
'simple_grid_field23',
'simple_grid_field64',
'simple_grid_field24',
'simple_grid_field65',
'simple_grid_field25',
'simple_grid_field66',
'simple_grid_field26',
'simple_grid_field67',
'simple_grid_field27',
'simple_grid_field68',
'simple_grid_field28',
'simple_grid_field69',
'simple_grid_field29',
'simple_grid_field70',
'simple_grid_field30',
'simple_grid_field71',
'simple_grid_field31',
'simple_grid_field72',
'simple_grid_field32',
'simple_grid_field73',
'simple_grid_field33',
'simple_grid_field74',
'simple_grid_field34',
'simple_grid_field75',
'simple_grid_field35',
'simple_grid_field76',
'simple_grid_field36',
'simple_grid_field77',
'simple_grid_field37',
'simple_grid_field78',
'simple_grid_field38',
'simple_grid_field79',
'simple_grid_field39' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field40' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field39' => 'grid' ),
'itemLocations' => array( 'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39' ),
'grid_field_label' => array( 'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'id_interna_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'keluhan_pertama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'keluhan_tmbhan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_skrg_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_dulu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_klg_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_alergi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_pengobatan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_kebiasaan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'rwyt_sos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'pem_umum_ku_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'pem_umum_tb_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'pem_umum_bb_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'pem_umum_imt_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'tanda_vital_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'kepala_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'leher_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'thorax_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'abdomen_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'ekstremitas_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'pmrksaan_pnunjang_lab_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'pmrksaan_pnunjang_radiologi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'pmrksaan_pnunjang_lain_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'id_mhs_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'id_pasien_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'Id_Pasien1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'Nama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'Alamat_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'Umur_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'Status_Perkawinan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'Jenis_Kelamin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'Suku_Ras_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'Agama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'Kerja_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'Tanggal_MRS_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'id_interna_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'keluhan_pertama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'keluhan_tmbhan_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_skrg_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_dulu_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_klg_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_alergi_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_pengobatan_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_kebiasaan_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'rwyt_sos_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'pem_umum_ku_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'pem_umum_tb_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'pem_umum_bb_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'pem_umum_imt_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'tanda_vital_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'kepala_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'leher_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'thorax_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'abdomen_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'ekstremitas_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'pmrksaan_pnunjang_lab_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'pmrksaan_pnunjang_radiologi_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'pmrksaan_pnunjang_lain_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'id_mhs_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'id_pasien_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'name_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'username_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'Id_Pasien1_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'Nama_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'Alamat_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'Umur_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'Status_Perkawinan_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'Jenis_Kelamin_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'Suku_Ras_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'Agama_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'Kerja_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'Tanggal_MRS_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 40,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'id_interna',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id_interna',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'keluhan_pertama',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'keluhan_pertama',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'keluhan_tmbhan',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'keluhan_tmbhan',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'rwyt_skrg',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'rwyt_skrg',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'rwyt_dulu',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'rwyt_dulu',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'rwyt_klg',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'rwyt_klg',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'rwyt_alergi',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'rwyt_alergi',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'rwyt_pengobatan',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'rwyt_pengobatan',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'rwyt_kebiasaan',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'rwyt_kebiasaan',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'rwyt_sos',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'rwyt_sos',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'pem_umum_ku',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'pem_umum_ku',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'pem_umum_tb',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'pem_umum_tb',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'pem_umum_bb',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'pem_umum_bb',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'pem_umum_imt',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'pem_umum_imt',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'tanda_vital',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'tanda_vital',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'kepala',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'kepala',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'leher',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'leher',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'thorax',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'thorax',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'abdomen',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'abdomen',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'ekstremitas',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'ekstremitas',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'pmrksaan_pnunjang_lab',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'pmrksaan_pnunjang_lab',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'pmrksaan_pnunjang_radiologi',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'pmrksaan_pnunjang_radiologi',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'pmrksaan_pnunjang_lain',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'pmrksaan_pnunjang_lain',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'id_mhs',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'id_mhs',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'id_pasien',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'id_pasien',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'name',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'name',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'username',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'username',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'Nama',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'Nama',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'Umur',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Umur',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'Agama',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'Agama',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field' => array( 'field' => 'id_interna',
'type' => 'grid_field' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'id_interna' ),
'simple_grid_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'grid_field' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'keluhan_pertama' ),
'simple_grid_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'grid_field' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'keluhan_tmbhan' ),
'simple_grid_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'grid_field' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_skrg' ),
'simple_grid_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'grid_field' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_dulu' ),
'simple_grid_field5' => array( 'field' => 'rwyt_klg',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_klg' ),
'simple_grid_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_alergi' ),
'simple_grid_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_pengobatan' ),
'simple_grid_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_kebiasaan' ),
'simple_grid_field9' => array( 'field' => 'rwyt_sos',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'rwyt_sos' ),
'simple_grid_field10' => array( 'field' => 'pem_umum_ku',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'pem_umum_ku' ),
'simple_grid_field11' => array( 'field' => 'pem_umum_tb',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'pem_umum_tb' ),
'simple_grid_field12' => array( 'field' => 'pem_umum_bb',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'pem_umum_bb' ),
'simple_grid_field13' => array( 'field' => 'pem_umum_imt',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'pem_umum_imt' ),
'simple_grid_field14' => array( 'field' => 'tanda_vital',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'tanda_vital' ),
'simple_grid_field15' => array( 'field' => 'kepala',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'kepala' ),
'simple_grid_field16' => array( 'field' => 'leher',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'leher' ),
'simple_grid_field17' => array( 'field' => 'thorax',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'thorax' ),
'simple_grid_field18' => array( 'field' => 'abdomen',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'abdomen' ),
'simple_grid_field19' => array( 'field' => 'ekstremitas',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'ekstremitas' ),
'simple_grid_field20' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'pmrksaan_pnunjang_lab' ),
'simple_grid_field21' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'pmrksaan_pnunjang_radiologi' ),
'simple_grid_field22' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'pmrksaan_pnunjang_lain' ),
'simple_grid_field23' => array( 'field' => 'id_mhs',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'id_mhs' ),
'simple_grid_field24' => array( 'field' => 'id_pasien',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'id_pasien' ),
'simple_grid_field25' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'simple_grid_field26' => array( 'field' => 'id',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'simple_grid_field27' => array( 'field' => 'name',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'name' ),
'simple_grid_field28' => array( 'field' => 'username',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'username' ),
'simple_grid_field29' => array( 'field' => 'email',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'simple_grid_field30' => array( 'field' => 'Id_Pasien1',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'Id_Pasien1' ),
'simple_grid_field31' => array( 'field' => 'Nama',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'Nama' ),
'simple_grid_field32' => array( 'field' => 'Alamat',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'Alamat' ),
'simple_grid_field33' => array( 'field' => 'Umur',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'Umur' ),
'simple_grid_field34' => array( 'field' => 'Status_Perkawinan',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'Status_Perkawinan' ),
'simple_grid_field35' => array( 'field' => 'Jenis Kelamin',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'Jenis Kelamin' ),
'simple_grid_field36' => array( 'field' => 'Suku_Ras',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'Suku_Ras' ),
'simple_grid_field37' => array( 'field' => 'Agama',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'Agama' ),
'simple_grid_field38' => array( 'field' => 'Kerja',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'Kerja' ),
'simple_grid_field39' => array( 'field' => 'Tanggal_MRS',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'Tanggal_MRS' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>