<?php
			$optionsArray = array( 'details' => array( 'daftar_masalah_interna' => array( 'displayPreview' => 1 ) ),
'master' => array( 'users' => array( 'preview' => false ),
'identitas_pasien' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'pem_umum_bb',
'pem_umum_tb',
'rwyt_sos',
'pem_umum_imt',
'pmrksaan_pnunjang_radiologi',
'pmrksaan_pnunjang_lain',
'tanda_vital',
'pem_umum_ku',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'pmrksaan_pnunjang_lab',
'id_mhs',
'id_pasien',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'integrated_edit_field1' ),
'keluhan_tmbhan' => array( 'integrated_edit_field2' ),
'rwyt_skrg' => array( 'integrated_edit_field3' ),
'rwyt_dulu' => array( 'integrated_edit_field4' ),
'rwyt_klg' => array( 'integrated_edit_field5' ),
'rwyt_alergi' => array( 'integrated_edit_field6' ),
'rwyt_pengobatan' => array( 'integrated_edit_field7' ),
'rwyt_kebiasaan' => array( 'integrated_edit_field8' ),
'pem_umum_bb' => array( 'integrated_edit_field9' ),
'pem_umum_tb' => array( 'integrated_edit_field10' ),
'rwyt_sos' => array( 'integrated_edit_field11' ),
'pem_umum_imt' => array( 'integrated_edit_field12' ),
'pmrksaan_pnunjang_radiologi' => array( 'integrated_edit_field14' ),
'pmrksaan_pnunjang_lain' => array( 'integrated_edit_field15' ),
'tanda_vital' => array( 'integrated_edit_field16' ),
'pem_umum_ku' => array( 'integrated_edit_field' ),
'kepala' => array( 'integrated_edit_field28' ),
'leher' => array( 'integrated_edit_field29' ),
'thorax' => array( 'integrated_edit_field30' ),
'abdomen' => array( 'integrated_edit_field31' ),
'ekstremitas' => array( 'integrated_edit_field32' ),
'pmrksaan_pnunjang_lab' => array( 'integrated_edit_field13' ),
'id_mhs' => array( 'integrated_edit_field17' ),
'id_pasien' => array( 'integrated_edit_field18' ),
'Nomor_Rm' => array( 'integrated_edit_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message',
'deleted' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'master_info',
'tabs',
'integrated_edit_field13',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field19',
'details_preview' ),
'section1' => array( 'integrated_edit_field1',
'integrated_edit_field2' ),
'section2' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field11' ),
'section3' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field16',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'section5' => array( 'integrated_edit_field15',
'integrated_edit_field14' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'deleted' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'tabs' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field19' => 'grid',
'details_preview' => 'grid',
'integrated_edit_field1' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field3' => 'section2',
'integrated_edit_field4' => 'section2',
'integrated_edit_field5' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field7' => 'section2',
'integrated_edit_field8' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field' => 'section3',
'integrated_edit_field9' => 'section3',
'integrated_edit_field10' => 'section3',
'integrated_edit_field12' => 'section3',
'integrated_edit_field16' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field29' => 'section3',
'integrated_edit_field30' => 'section3',
'integrated_edit_field31' => 'section3',
'integrated_edit_field32' => 'section3',
'integrated_edit_field15' => 'section5',
'integrated_edit_field14' => 'section5' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field31' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field32' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field15' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section5',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field13',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19' ),
'tabs' => array( 'tabs' ),
'deleted' => array( 'deleted' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ),
'master_info' => array( 'master_info' ),
'details_preview' => array( 'details_preview' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13',
'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17',
'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15',
'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'deleted' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 2,
'rowspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c5',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'tabs' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13',
'integrated_edit_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17',
'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c5' => array( 'model' => 'c3',
'items' => array( 'details_preview' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15',
'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header',
'title' => array( 'page' => 'edit',
'table' => 'interna',
'type' => 7 ) ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save',
'label' => array( 'type' => 0,
'text' => 'Simpan' ) ),
'edit_back_list' => array( 'type' => 'edit_back_list',
'label' => array( 'type' => 0,
'text' => 'Kembali ke menu' ) ),
'edit_close' => array( 'type' => 'edit_close',
'buttonStyle' => 'danger',
'label' => array( 'type' => 0,
'text' => 'Batal' ) ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_pertama',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_tmbhan',
'table' => 'ginekologi',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_skrg',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_dulu',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_klg',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_alergi',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_pengobatan',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kebiasaan',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'pem_umum_bb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pem_umum_bb',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'pem_umum_tb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pem_umum_tb',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'rwyt_sos',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_sos',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'pem_umum_imt',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pem_umum_imt',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field14' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pmrksaan_pnunjang_lain',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'tanda_vital',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'ANAMNESIS',
'type' => 0 ),
array( 'text' => 'RIWAYAT PENYAKIT',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN FISIK UMUM',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN PENUNJANG YANG LALU',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section3',
'section5' ) ),
'integrated_edit_field' => array( 'field' => 'pem_umum_ku',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'pem_umum_ku',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field28' => array( 'field' => 'kepala',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'deleted' => array( 'type' => 'deleted',
'itemId' => 'integrated_edit_field13' ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'integrated_edit_field13' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'id_mhs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'id_pasien',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'integrated_edit_field19' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'daftar_masalah_interna',
'items' => array(  ),
'popup' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>