<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_Jiwa',
'Keluhan_Utama',
'Anamnesis',
'Autoanamnesis',
'Alloanamnesis',
'Riwayat_gangguan_sekarang',
'Riwayat_gangguan_dahulu',
'Riwayat_gangguan_psikiatri',
'Riwayat_gangguan_medis',
'Riwayat_penggunaan_zat_psikoaktif',
'Riwayat_prenatal_dan_perinatal',
'Riwayat_masa_kanak_awal',
'Riwayat_masa_kanak_pertengahan',
'Riwayat_masa_kanak_akhir_dan_remaja',
'Masa_Dewasa',
'Riwayat_pendidikan',
'Riwayat_pekerjaan',
'Riwayat_pernikahan',
'Riwayat_Agama',
'Riwayat_Psikoseksual',
'Riwayat_aktivitas_sosial',
'Riwayat_hukum',
'Riwayat_keluarga',
'Genogram_keluarga',
'Situasi_kehidupan_sekarang',
'Persepsi_tentang_diri_dan_kehidupannya',
'Persepsi_keluarga_tentang_diri_pasien',
'Fantasi',
'Penampilan',
'Perilaku_dan_aktivitas_psikomotor',
'Sikap_terhadap_pemeriksa',
'Irama',
'Kecepatan_bicara',
'Volume',
'Kelancaran',
'Mood',
'Afek',
'Keserasian',
'Auditorik',
'Visual',
'Taktil',
'Olfaktorik',
'Gustatorik',
'Ilusi',
'Depersonalisasi',
'Derealisasi',
'Blocking',
'Assosiasi_Longgar',
'Inkoheren',
'Flight_of_Idea',
'Sirkumstansia',
'Tangensial',
'Neologisme',
'Word_Salad',
'Hendaya_Berbahasa',
'Produktivitas',
'Preokupasi',
'Waham_bizarre',
'Waham_sistemik',
'Waham_nihilistik',
'Waham_paranoid',
'Waham_kebesaran',
'Waham_kejaran',
'Waham_rujukan',
'Waham_dikendalikan',
'Thought_of_withdrawl',
'Thought_of_insertion',
'Thought_of_broadcasting',
'Obsesi',
'Kompulsif',
'Fobia',
'Gagasan_untuk_bunuh_diri',
'Taraf_kesadaran_dan_kesiagaan',
'Orieantasi_Waktu',
'Orieantasi_Tempat',
'Orieantasi_Orang',
'Daya_ingat_Jangka_panjang',
'Daya_ingat_Jangka_sedang',
'Daya_ingat_Jangka_pendek',
'Daya_ingat_Jangka_segera',
'Konsentrasi_perhatian',
'Kemampuan_Membaca_Menulis',
'Kemampuan_visuospasial',
'Pikiran_abstrak',
'Inteligensia_dan_kemampuan_informasi',
'Kemampuan_mengendalikan_impuls',
'Daya_nilai_dan_tilikan',
'Daya_nilai_sosial',
'Uji_daya_nilai',
'Penilaian_Daya_Realita',
'Tilikan',
'Taraf_dipercaya',
'Keadaan_Umum',
'Kesadaran',
'Status_gizi',
'Tekanan_Darah',
'Frekuensi_Nadi',
'Frekuensi_Nafas',
'Suhu',
'Mata_dan_THT',
'Mulut_dan_Gigi',
'Thorax',
'Abdomen',
'Extremitas',
'Tanda_rangsang_Meningeal',
'Motorik',
'Sensorik',
'Diagnosis_Axis',
'Organobiologi',
'Psikologi',
'Lingkungan_dan_sosial_ekonomi',
'Quo_ad_Vitam',
'Quo_ad_Fungsionam',
'Quo_ad_Sanationam',
'Hal-hal_yang_mendukung',
'Hal-hal_yang_memberatkan',
'Farmakologi',
'Non_Farmakologi',
'id_pasien',
'id_user',
'id_resep',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_Jiwa' => array( 'integrated_search_field' ),
'Keluhan_Utama' => array( 'integrated_search_field1' ),
'Anamnesis' => array( 'integrated_search_field2' ),
'Autoanamnesis' => array( 'integrated_search_field3' ),
'Alloanamnesis' => array( 'integrated_search_field4' ),
'Riwayat_gangguan_sekarang' => array( 'integrated_search_field5' ),
'Riwayat_gangguan_dahulu' => array( 'integrated_search_field6' ),
'Riwayat_gangguan_psikiatri' => array( 'integrated_search_field7' ),
'Riwayat_gangguan_medis' => array( 'integrated_search_field8' ),
'Riwayat_penggunaan_zat_psikoaktif' => array( 'integrated_search_field9' ),
'Riwayat_prenatal_dan_perinatal' => array( 'integrated_search_field10' ),
'Riwayat_masa_kanak_awal' => array( 'integrated_search_field11' ),
'Riwayat_masa_kanak_pertengahan' => array( 'integrated_search_field12' ),
'Riwayat_masa_kanak_akhir_dan_remaja' => array( 'integrated_search_field13' ),
'Masa_Dewasa' => array( 'integrated_search_field14' ),
'Riwayat_pendidikan' => array( 'integrated_search_field15' ),
'Riwayat_pekerjaan' => array( 'integrated_search_field16' ),
'Riwayat_pernikahan' => array( 'integrated_search_field17' ),
'Riwayat_Agama' => array( 'integrated_search_field18' ),
'Riwayat_Psikoseksual' => array( 'integrated_search_field19' ),
'Riwayat_aktivitas_sosial' => array( 'integrated_search_field20' ),
'Riwayat_hukum' => array( 'integrated_search_field21' ),
'Riwayat_keluarga' => array( 'integrated_search_field22' ),
'Genogram_keluarga' => array( 'integrated_search_field23' ),
'Situasi_kehidupan_sekarang' => array( 'integrated_search_field24' ),
'Persepsi_tentang_diri_dan_kehidupannya' => array( 'integrated_search_field25' ),
'Persepsi_keluarga_tentang_diri_pasien' => array( 'integrated_search_field26' ),
'Fantasi' => array( 'integrated_search_field27' ),
'Penampilan' => array( 'integrated_search_field28' ),
'Perilaku_dan_aktivitas_psikomotor' => array( 'integrated_search_field29' ),
'Sikap_terhadap_pemeriksa' => array( 'integrated_search_field30' ),
'Irama' => array( 'integrated_search_field31' ),
'Kecepatan_bicara' => array( 'integrated_search_field32' ),
'Volume' => array( 'integrated_search_field33' ),
'Kelancaran' => array( 'integrated_search_field34' ),
'Mood' => array( 'integrated_search_field35' ),
'Afek' => array( 'integrated_search_field36' ),
'Keserasian' => array( 'integrated_search_field37' ),
'Auditorik' => array( 'integrated_search_field38' ),
'Visual' => array( 'integrated_search_field39' ),
'Taktil' => array( 'integrated_search_field40' ),
'Olfaktorik' => array( 'integrated_search_field41' ),
'Gustatorik' => array( 'integrated_search_field42' ),
'Ilusi' => array( 'integrated_search_field43' ),
'Depersonalisasi' => array( 'integrated_search_field44' ),
'Derealisasi' => array( 'integrated_search_field45' ),
'Blocking' => array( 'integrated_search_field46' ),
'Assosiasi_Longgar' => array( 'integrated_search_field47' ),
'Inkoheren' => array( 'integrated_search_field48' ),
'Flight_of_Idea' => array( 'integrated_search_field49' ),
'Sirkumstansia' => array( 'integrated_search_field50' ),
'Tangensial' => array( 'integrated_search_field51' ),
'Neologisme' => array( 'integrated_search_field52' ),
'Word_Salad' => array( 'integrated_search_field53' ),
'Hendaya_Berbahasa' => array( 'integrated_search_field54' ),
'Produktivitas' => array( 'integrated_search_field55' ),
'Preokupasi' => array( 'integrated_search_field56' ),
'Waham_bizarre' => array( 'integrated_search_field57' ),
'Waham_sistemik' => array( 'integrated_search_field58' ),
'Waham_nihilistik' => array( 'integrated_search_field59' ),
'Waham_paranoid' => array( 'integrated_search_field60' ),
'Waham_kebesaran' => array( 'integrated_search_field61' ),
'Waham_kejaran' => array( 'integrated_search_field62' ),
'Waham_rujukan' => array( 'integrated_search_field63' ),
'Waham_dikendalikan' => array( 'integrated_search_field64' ),
'Thought_of_withdrawl' => array( 'integrated_search_field65' ),
'Thought_of_insertion' => array( 'integrated_search_field66' ),
'Thought_of_broadcasting' => array( 'integrated_search_field67' ),
'Obsesi' => array( 'integrated_search_field68' ),
'Kompulsif' => array( 'integrated_search_field69' ),
'Fobia' => array( 'integrated_search_field70' ),
'Gagasan_untuk_bunuh_diri' => array( 'integrated_search_field71' ),
'Taraf_kesadaran_dan_kesiagaan' => array( 'integrated_search_field72' ),
'Orieantasi_Waktu' => array( 'integrated_search_field73' ),
'Orieantasi_Tempat' => array( 'integrated_search_field74' ),
'Orieantasi_Orang' => array( 'integrated_search_field75' ),
'Daya_ingat_Jangka_panjang' => array( 'integrated_search_field76' ),
'Daya_ingat_Jangka_sedang' => array( 'integrated_search_field77' ),
'Daya_ingat_Jangka_pendek' => array( 'integrated_search_field78' ),
'Daya_ingat_Jangka_segera' => array( 'integrated_search_field79' ),
'Konsentrasi_perhatian' => array( 'integrated_search_field80' ),
'Kemampuan_Membaca_Menulis' => array( 'integrated_search_field81' ),
'Kemampuan_visuospasial' => array( 'integrated_search_field82' ),
'Pikiran_abstrak' => array( 'integrated_search_field83' ),
'Inteligensia_dan_kemampuan_informasi' => array( 'integrated_search_field84' ),
'Kemampuan_mengendalikan_impuls' => array( 'integrated_search_field85' ),
'Daya_nilai_dan_tilikan' => array( 'integrated_search_field86' ),
'Daya_nilai_sosial' => array( 'integrated_search_field87' ),
'Uji_daya_nilai' => array( 'integrated_search_field88' ),
'Penilaian_Daya_Realita' => array( 'integrated_search_field89' ),
'Tilikan' => array( 'integrated_search_field90' ),
'Taraf_dipercaya' => array( 'integrated_search_field91' ),
'Keadaan_Umum' => array( 'integrated_search_field92' ),
'Kesadaran' => array( 'integrated_search_field93' ),
'Status_gizi' => array( 'integrated_search_field94' ),
'Tekanan_Darah' => array( 'integrated_search_field95' ),
'Frekuensi_Nadi' => array( 'integrated_search_field96' ),
'Frekuensi_Nafas' => array( 'integrated_search_field97' ),
'Suhu' => array( 'integrated_search_field98' ),
'Mata_dan_THT' => array( 'integrated_search_field99' ),
'Mulut_dan_Gigi' => array( 'integrated_search_field100' ),
'Thorax' => array( 'integrated_search_field101' ),
'Abdomen' => array( 'integrated_search_field102' ),
'Extremitas' => array( 'integrated_search_field103' ),
'Tanda_rangsang_Meningeal' => array( 'integrated_search_field104' ),
'Motorik' => array( 'integrated_search_field105' ),
'Sensorik' => array( 'integrated_search_field106' ),
'Diagnosis_Axis' => array( 'integrated_search_field107' ),
'Organobiologi' => array( 'integrated_search_field108' ),
'Psikologi' => array( 'integrated_search_field109' ),
'Lingkungan_dan_sosial_ekonomi' => array( 'integrated_search_field110' ),
'Quo_ad_Vitam' => array( 'integrated_search_field111' ),
'Quo_ad_Fungsionam' => array( 'integrated_search_field112' ),
'Quo_ad_Sanationam' => array( 'integrated_search_field113' ),
'Hal-hal_yang_mendukung' => array( 'integrated_search_field114' ),
'Hal-hal_yang_memberatkan' => array( 'integrated_search_field115' ),
'Farmakologi' => array( 'integrated_search_field116' ),
'Non_Farmakologi' => array( 'integrated_search_field117' ),
'id_pasien' => array( 'integrated_search_field118' ),
'id_user' => array( 'integrated_search_field119' ),
'id_resep' => array( 'integrated_search_field120' ),
'Nomor_Rm' => array( 'integrated_search_field121' ),
'id' => array( 'integrated_search_field122' ),
'name' => array( 'integrated_search_field123' ),
'username' => array( 'integrated_search_field124' ),
'email' => array( 'integrated_search_field125' ),
'Id_Pasien1' => array( 'integrated_search_field126' ),
'Nama' => array( 'integrated_search_field127' ),
'Alamat' => array( 'integrated_search_field128' ),
'Umur' => array( 'integrated_search_field129' ),
'Status_Perkawinan' => array( 'integrated_search_field130' ),
'Jenis Kelamin' => array( 'integrated_search_field131' ),
'Suku_Ras' => array( 'integrated_search_field132' ),
'Agama' => array( 'integrated_search_field133' ),
'Kerja' => array( 'integrated_search_field134' ),
'Tanggal_MRS' => array( 'integrated_search_field135' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid',
'integrated_search_field77' => 'grid',
'integrated_search_field78' => 'grid',
'integrated_search_field79' => 'grid',
'integrated_search_field80' => 'grid',
'integrated_search_field81' => 'grid',
'integrated_search_field82' => 'grid',
'integrated_search_field83' => 'grid',
'integrated_search_field84' => 'grid',
'integrated_search_field85' => 'grid',
'integrated_search_field86' => 'grid',
'integrated_search_field87' => 'grid',
'integrated_search_field88' => 'grid',
'integrated_search_field89' => 'grid',
'integrated_search_field90' => 'grid',
'integrated_search_field91' => 'grid',
'integrated_search_field92' => 'grid',
'integrated_search_field93' => 'grid',
'integrated_search_field94' => 'grid',
'integrated_search_field95' => 'grid',
'integrated_search_field96' => 'grid',
'integrated_search_field97' => 'grid',
'integrated_search_field98' => 'grid',
'integrated_search_field99' => 'grid',
'integrated_search_field100' => 'grid',
'integrated_search_field101' => 'grid',
'integrated_search_field102' => 'grid',
'integrated_search_field103' => 'grid',
'integrated_search_field104' => 'grid',
'integrated_search_field105' => 'grid',
'integrated_search_field106' => 'grid',
'integrated_search_field107' => 'grid',
'integrated_search_field108' => 'grid',
'integrated_search_field109' => 'grid',
'integrated_search_field110' => 'grid',
'integrated_search_field111' => 'grid',
'integrated_search_field112' => 'grid',
'integrated_search_field113' => 'grid',
'integrated_search_field114' => 'grid',
'integrated_search_field115' => 'grid',
'integrated_search_field116' => 'grid',
'integrated_search_field117' => 'grid',
'integrated_search_field118' => 'grid',
'integrated_search_field119' => 'grid',
'integrated_search_field120' => 'grid',
'integrated_search_field121' => 'grid',
'integrated_search_field122' => 'grid',
'integrated_search_field123' => 'grid',
'integrated_search_field124' => 'grid',
'integrated_search_field125' => 'grid',
'integrated_search_field126' => 'grid',
'integrated_search_field127' => 'grid',
'integrated_search_field128' => 'grid',
'integrated_search_field129' => 'grid',
'integrated_search_field130' => 'grid',
'integrated_search_field131' => 'grid',
'integrated_search_field132' => 'grid',
'integrated_search_field133' => 'grid',
'integrated_search_field134' => 'grid',
'integrated_search_field135' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field88' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field89' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field90' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field91' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field92' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field93' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field95' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field96' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field97' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field98' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field99' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field100' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field101' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field102' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field103' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field104' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field105' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field106' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field107' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field108' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field109' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field110' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field111' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field112' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field113' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field114' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field115' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field116' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field117' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field118' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field119' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field120' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field121' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field122' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field123' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field124' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field125' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field126' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field127' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field128' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field129' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field130' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field131' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field132' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field133' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field134' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field135' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87',
'integrated_search_field88',
'integrated_search_field89',
'integrated_search_field90',
'integrated_search_field91',
'integrated_search_field92',
'integrated_search_field93',
'integrated_search_field94',
'integrated_search_field95',
'integrated_search_field96',
'integrated_search_field97',
'integrated_search_field98',
'integrated_search_field99',
'integrated_search_field100',
'integrated_search_field101',
'integrated_search_field102',
'integrated_search_field103',
'integrated_search_field104',
'integrated_search_field105',
'integrated_search_field106',
'integrated_search_field107',
'integrated_search_field108',
'integrated_search_field109',
'integrated_search_field110',
'integrated_search_field111',
'integrated_search_field112',
'integrated_search_field113',
'integrated_search_field114',
'integrated_search_field115',
'integrated_search_field116',
'integrated_search_field117',
'integrated_search_field118',
'integrated_search_field119',
'integrated_search_field120',
'integrated_search_field121',
'integrated_search_field122',
'integrated_search_field123',
'integrated_search_field124',
'integrated_search_field125',
'integrated_search_field126',
'integrated_search_field127',
'integrated_search_field128',
'integrated_search_field129',
'integrated_search_field130',
'integrated_search_field131',
'integrated_search_field132',
'integrated_search_field133',
'integrated_search_field134',
'integrated_search_field135' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'id_Jiwa',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'Anamnesis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'Autoanamnesis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'Alloanamnesis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'Riwayat_gangguan_sekarang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'Riwayat_gangguan_dahulu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'Riwayat_gangguan_psikiatri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'Riwayat_gangguan_medis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'Riwayat_penggunaan_zat_psikoaktif',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'Riwayat_prenatal_dan_perinatal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'Riwayat_masa_kanak_awal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'Riwayat_masa_kanak_pertengahan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'Riwayat_masa_kanak_akhir_dan_remaja',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'Masa_Dewasa',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'Riwayat_pendidikan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'Riwayat_pekerjaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'Riwayat_pernikahan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'Riwayat_Agama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'Riwayat_Psikoseksual',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'Riwayat_aktivitas_sosial',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'Riwayat_hukum',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'Riwayat_keluarga',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'Genogram_keluarga',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'Situasi_kehidupan_sekarang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'Persepsi_tentang_diri_dan_kehidupannya',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'Persepsi_keluarga_tentang_diri_pasien',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'Fantasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'Penampilan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'Perilaku_dan_aktivitas_psikomotor',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'Sikap_terhadap_pemeriksa',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'Irama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'Kecepatan_bicara',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'Volume',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'Kelancaran',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'Mood',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'Afek',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'Keserasian',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'Auditorik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'Visual',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'Taktil',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'Olfaktorik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'Gustatorik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'Ilusi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'Depersonalisasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'Derealisasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'Blocking',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'Assosiasi_Longgar',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'Inkoheren',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'Flight_of_Idea',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'Sirkumstansia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'Tangensial',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'Neologisme',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'Word_Salad',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'Hendaya_Berbahasa',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'Produktivitas',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'Preokupasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'Waham_bizarre',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'Waham_sistemik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'Waham_nihilistik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'Waham_paranoid',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'Waham_kebesaran',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'Waham_kejaran',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'Waham_rujukan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'Waham_dikendalikan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'Thought_of_withdrawl',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'Thought_of_insertion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'Thought_of_broadcasting',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'Obsesi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'Kompulsif',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'Fobia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'Gagasan_untuk_bunuh_diri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'Taraf_kesadaran_dan_kesiagaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'Orieantasi_Waktu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'Orieantasi_Tempat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'Orieantasi_Orang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'Daya_ingat_Jangka_panjang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field77' => array( 'field' => 'Daya_ingat_Jangka_sedang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field78' => array( 'field' => 'Daya_ingat_Jangka_pendek',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field79' => array( 'field' => 'Daya_ingat_Jangka_segera',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field80' => array( 'field' => 'Konsentrasi_perhatian',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field81' => array( 'field' => 'Kemampuan_Membaca_Menulis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field82' => array( 'field' => 'Kemampuan_visuospasial',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field83' => array( 'field' => 'Pikiran_abstrak',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field84' => array( 'field' => 'Inteligensia_dan_kemampuan_informasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field85' => array( 'field' => 'Kemampuan_mengendalikan_impuls',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field86' => array( 'field' => 'Daya_nilai_dan_tilikan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field87' => array( 'field' => 'Daya_nilai_sosial',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field88' => array( 'field' => 'Uji_daya_nilai',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field89' => array( 'field' => 'Penilaian_Daya_Realita',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field90' => array( 'field' => 'Tilikan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field91' => array( 'field' => 'Taraf_dipercaya',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field92' => array( 'field' => 'Keadaan_Umum',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field93' => array( 'field' => 'Kesadaran',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field94' => array( 'field' => 'Status_gizi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field95' => array( 'field' => 'Tekanan_Darah',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field96' => array( 'field' => 'Frekuensi_Nadi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field97' => array( 'field' => 'Frekuensi_Nafas',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field98' => array( 'field' => 'Suhu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field99' => array( 'field' => 'Mata_dan_THT',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field100' => array( 'field' => 'Mulut_dan_Gigi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field101' => array( 'field' => 'Thorax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field102' => array( 'field' => 'Abdomen',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field103' => array( 'field' => 'Extremitas',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field104' => array( 'field' => 'Tanda_rangsang_Meningeal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field105' => array( 'field' => 'Motorik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field106' => array( 'field' => 'Sensorik',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field107' => array( 'field' => 'Diagnosis_Axis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field108' => array( 'field' => 'Organobiologi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field109' => array( 'field' => 'Psikologi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field110' => array( 'field' => 'Lingkungan_dan_sosial_ekonomi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field111' => array( 'field' => 'Quo_ad_Vitam',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field112' => array( 'field' => 'Quo_ad_Fungsionam',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field113' => array( 'field' => 'Quo_ad_Sanationam',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field114' => array( 'field' => 'Hal-hal_yang_mendukung',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field115' => array( 'field' => 'Hal-hal_yang_memberatkan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field116' => array( 'field' => 'Farmakologi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field117' => array( 'field' => 'Non_Farmakologi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field118' => array( 'field' => 'id_pasien',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field119' => array( 'field' => 'id_user',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field120' => array( 'field' => 'id_resep',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field121' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field122' => array( 'field' => 'id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field123' => array( 'field' => 'name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field124' => array( 'field' => 'username',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field125' => array( 'field' => 'email',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field126' => array( 'field' => 'Id_Pasien1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field127' => array( 'field' => 'Nama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field128' => array( 'field' => 'Alamat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field129' => array( 'field' => 'Umur',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field130' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field131' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field132' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field133' => array( 'field' => 'Agama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field134' => array( 'field' => 'Kerja',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field135' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>