<?php
			$optionsArray = array( 'totals' => array( 'id_Jiwa' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Anamnesis' => array( 'totalsType' => '' ),
'Autoanamnesis' => array( 'totalsType' => '' ),
'Alloanamnesis' => array( 'totalsType' => '' ),
'Riwayat_gangguan_sekarang' => array( 'totalsType' => '' ),
'Riwayat_gangguan_dahulu' => array( 'totalsType' => '' ),
'Riwayat_gangguan_psikiatri' => array( 'totalsType' => '' ),
'Riwayat_gangguan_medis' => array( 'totalsType' => '' ),
'Riwayat_penggunaan_zat_psikoaktif' => array( 'totalsType' => '' ),
'Riwayat_prenatal_dan_perinatal' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_awal' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_pertengahan' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_akhir_dan_remaja' => array( 'totalsType' => '' ),
'Masa_Dewasa' => array( 'totalsType' => '' ),
'Riwayat_pendidikan' => array( 'totalsType' => '' ),
'Riwayat_pekerjaan' => array( 'totalsType' => '' ),
'Riwayat_pernikahan' => array( 'totalsType' => '' ),
'Riwayat_Agama' => array( 'totalsType' => '' ),
'Riwayat_Psikoseksual' => array( 'totalsType' => '' ),
'Riwayat_aktivitas_sosial' => array( 'totalsType' => '' ),
'Riwayat_hukum' => array( 'totalsType' => '' ),
'Riwayat_keluarga' => array( 'totalsType' => '' ),
'Genogram_keluarga' => array( 'totalsType' => '' ),
'Situasi_kehidupan_sekarang' => array( 'totalsType' => '' ),
'Persepsi_tentang_diri_dan_kehidupannya' => array( 'totalsType' => '' ),
'Persepsi_keluarga_tentang_diri_pasien' => array( 'totalsType' => '' ),
'Fantasi' => array( 'totalsType' => '' ),
'Penampilan' => array( 'totalsType' => '' ),
'Perilaku_dan_aktivitas_psikomotor' => array( 'totalsType' => '' ),
'Sikap_terhadap_pemeriksa' => array( 'totalsType' => '' ),
'Irama' => array( 'totalsType' => '' ),
'Kecepatan_bicara' => array( 'totalsType' => '' ),
'Volume' => array( 'totalsType' => '' ),
'Kelancaran' => array( 'totalsType' => '' ),
'Mood' => array( 'totalsType' => '' ),
'Afek' => array( 'totalsType' => '' ),
'Keserasian' => array( 'totalsType' => '' ),
'Auditorik' => array( 'totalsType' => '' ),
'Visual' => array( 'totalsType' => '' ),
'Taktil' => array( 'totalsType' => '' ),
'Olfaktorik' => array( 'totalsType' => '' ),
'Gustatorik' => array( 'totalsType' => '' ),
'Ilusi' => array( 'totalsType' => '' ),
'Depersonalisasi' => array( 'totalsType' => '' ),
'Derealisasi' => array( 'totalsType' => '' ),
'Blocking' => array( 'totalsType' => '' ),
'Assosiasi_Longgar' => array( 'totalsType' => '' ),
'Inkoheren' => array( 'totalsType' => '' ),
'Flight_of_Idea' => array( 'totalsType' => '' ),
'Sirkumstansia' => array( 'totalsType' => '' ),
'Tangensial' => array( 'totalsType' => '' ),
'Neologisme' => array( 'totalsType' => '' ),
'Word_Salad' => array( 'totalsType' => '' ),
'Hendaya_Berbahasa' => array( 'totalsType' => '' ),
'Produktivitas' => array( 'totalsType' => '' ),
'Preokupasi' => array( 'totalsType' => '' ),
'Waham_bizarre' => array( 'totalsType' => '' ),
'Waham_sistemik' => array( 'totalsType' => '' ),
'Waham_nihilistik' => array( 'totalsType' => '' ),
'Waham_paranoid' => array( 'totalsType' => '' ),
'Waham_kebesaran' => array( 'totalsType' => '' ),
'Waham_kejaran' => array( 'totalsType' => '' ),
'Waham_rujukan' => array( 'totalsType' => '' ),
'Waham_dikendalikan' => array( 'totalsType' => '' ),
'Thought_of_withdrawl' => array( 'totalsType' => '' ),
'Thought_of_insertion' => array( 'totalsType' => '' ),
'Thought_of_broadcasting' => array( 'totalsType' => '' ),
'Obsesi' => array( 'totalsType' => '' ),
'Kompulsif' => array( 'totalsType' => '' ),
'Fobia' => array( 'totalsType' => '' ),
'Gagasan_untuk_bunuh_diri' => array( 'totalsType' => '' ),
'Taraf_kesadaran_dan_kesiagaan' => array( 'totalsType' => '' ),
'Orieantasi_Waktu' => array( 'totalsType' => '' ),
'Orieantasi_Tempat' => array( 'totalsType' => '' ),
'Orieantasi_Orang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_panjang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_sedang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_pendek' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_segera' => array( 'totalsType' => '' ),
'Konsentrasi_perhatian' => array( 'totalsType' => '' ),
'Kemampuan_Membaca_Menulis' => array( 'totalsType' => '' ),
'Kemampuan_visuospasial' => array( 'totalsType' => '' ),
'Pikiran_abstrak' => array( 'totalsType' => '' ),
'Inteligensia_dan_kemampuan_informasi' => array( 'totalsType' => '' ),
'Kemampuan_mengendalikan_impuls' => array( 'totalsType' => '' ),
'Daya_nilai_dan_tilikan' => array( 'totalsType' => '' ),
'Daya_nilai_sosial' => array( 'totalsType' => '' ),
'Uji_daya_nilai' => array( 'totalsType' => '' ),
'Penilaian_Daya_Realita' => array( 'totalsType' => '' ),
'Tilikan' => array( 'totalsType' => '' ),
'Taraf_dipercaya' => array( 'totalsType' => '' ),
'Keadaan_Umum' => array( 'totalsType' => '' ),
'Kesadaran' => array( 'totalsType' => '' ),
'Status_gizi' => array( 'totalsType' => '' ),
'Tekanan_Darah' => array( 'totalsType' => '' ),
'Frekuensi_Nadi' => array( 'totalsType' => '' ),
'Frekuensi_Nafas' => array( 'totalsType' => '' ),
'Suhu' => array( 'totalsType' => '' ),
'Mata_dan_THT' => array( 'totalsType' => '' ),
'Mulut_dan_Gigi' => array( 'totalsType' => '' ),
'Thorax' => array( 'totalsType' => '' ),
'Abdomen' => array( 'totalsType' => '' ),
'Extremitas' => array( 'totalsType' => '' ),
'Tanda_rangsang_Meningeal' => array( 'totalsType' => '' ),
'Motorik' => array( 'totalsType' => '' ),
'Sensorik' => array( 'totalsType' => '' ),
'Diagnosis_Axis' => array( 'totalsType' => '' ),
'Organobiologi' => array( 'totalsType' => '' ),
'Psikologi' => array( 'totalsType' => '' ),
'Lingkungan_dan_sosial_ekonomi' => array( 'totalsType' => '' ),
'Quo_ad_Vitam' => array( 'totalsType' => '' ),
'Quo_ad_Fungsionam' => array( 'totalsType' => '' ),
'Quo_ad_Sanationam' => array( 'totalsType' => '' ),
'Hal-hal_yang_mendukung' => array( 'totalsType' => '' ),
'Hal-hal_yang_memberatkan' => array( 'totalsType' => '' ),
'Farmakologi' => array( 'totalsType' => '' ),
'Non_Farmakologi' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'id_resep' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Anamnesis',
'Autoanamnesis',
'Alloanamnesis',
'Riwayat_gangguan_sekarang',
'Riwayat_gangguan_dahulu',
'Riwayat_gangguan_psikiatri',
'Riwayat_gangguan_medis',
'Riwayat_penggunaan_zat_psikoaktif',
'Riwayat_prenatal_dan_perinatal',
'Riwayat_masa_kanak_awal',
'Riwayat_masa_kanak_pertengahan',
'Riwayat_masa_kanak_akhir_dan_remaja',
'Masa_Dewasa',
'Riwayat_pendidikan',
'Riwayat_pekerjaan',
'Riwayat_pernikahan',
'Riwayat_Agama',
'Riwayat_Psikoseksual',
'Riwayat_aktivitas_sosial',
'Riwayat_hukum',
'Riwayat_keluarga',
'Genogram_keluarga',
'Situasi_kehidupan_sekarang',
'Persepsi_tentang_diri_dan_kehidupannya',
'Persepsi_keluarga_tentang_diri_pasien',
'Fantasi',
'Penampilan',
'Perilaku_dan_aktivitas_psikomotor',
'Sikap_terhadap_pemeriksa',
'Irama',
'Kecepatan_bicara',
'Volume',
'Kelancaran',
'Mood',
'Afek',
'Keserasian',
'Auditorik',
'Visual',
'Taktil',
'Olfaktorik',
'Gustatorik',
'Ilusi',
'Depersonalisasi',
'Derealisasi',
'Blocking',
'Assosiasi_Longgar',
'Inkoheren',
'Flight_of_Idea',
'Sirkumstansia',
'Tangensial',
'Neologisme',
'Word_Salad',
'Hendaya_Berbahasa',
'Produktivitas',
'Preokupasi',
'Waham_bizarre',
'Waham_sistemik',
'Waham_nihilistik',
'Waham_paranoid',
'Waham_kebesaran',
'Waham_kejaran',
'Waham_rujukan',
'Waham_dikendalikan',
'Thought_of_withdrawl',
'Thought_of_insertion',
'Thought_of_broadcasting',
'Obsesi',
'Kompulsif',
'Fobia',
'Gagasan_untuk_bunuh_diri',
'Taraf_kesadaran_dan_kesiagaan',
'Orieantasi_Waktu',
'Orieantasi_Tempat',
'Orieantasi_Orang',
'Daya_ingat_Jangka_panjang',
'Daya_ingat_Jangka_sedang',
'Daya_ingat_Jangka_pendek',
'Daya_ingat_Jangka_segera',
'Konsentrasi_perhatian',
'Kemampuan_Membaca_Menulis',
'Kemampuan_visuospasial',
'Pikiran_abstrak',
'Inteligensia_dan_kemampuan_informasi',
'Kemampuan_mengendalikan_impuls',
'Daya_nilai_dan_tilikan',
'Daya_nilai_sosial',
'Uji_daya_nilai',
'Penilaian_Daya_Realita',
'Tilikan',
'Taraf_dipercaya',
'Keadaan_Umum',
'Kesadaran',
'Status_gizi',
'Tekanan_Darah',
'Frekuensi_Nadi',
'Frekuensi_Nafas',
'Suhu',
'Mata_dan_THT',
'Mulut_dan_Gigi',
'Thorax',
'Abdomen',
'Extremitas',
'Tanda_rangsang_Meningeal',
'Motorik',
'Sensorik',
'Diagnosis_Axis',
'Organobiologi',
'Psikologi',
'Lingkungan_dan_sosial_ekonomi',
'Quo_ad_Vitam',
'Quo_ad_Fungsionam',
'Quo_ad_Sanationam',
'Hal-hal_yang_mendukung',
'Hal-hal_yang_memberatkan',
'Farmakologi',
'Non_Farmakologi',
'id_pasien',
'id_user',
'id_resep',
'Nomor_Rm' ),
'exportFields' => array( 'Keluhan_Utama',
'Anamnesis',
'Autoanamnesis',
'Alloanamnesis',
'Riwayat_gangguan_sekarang',
'Riwayat_gangguan_dahulu',
'Riwayat_gangguan_psikiatri',
'Riwayat_gangguan_medis',
'Riwayat_penggunaan_zat_psikoaktif',
'Riwayat_prenatal_dan_perinatal',
'Riwayat_masa_kanak_awal',
'Riwayat_masa_kanak_pertengahan',
'Riwayat_masa_kanak_akhir_dan_remaja',
'Masa_Dewasa',
'Riwayat_pendidikan',
'Riwayat_pekerjaan',
'Riwayat_pernikahan',
'Riwayat_Agama',
'Riwayat_Psikoseksual',
'Riwayat_aktivitas_sosial',
'Riwayat_hukum',
'Riwayat_keluarga',
'Genogram_keluarga',
'Situasi_kehidupan_sekarang',
'Persepsi_tentang_diri_dan_kehidupannya',
'Persepsi_keluarga_tentang_diri_pasien',
'Fantasi',
'Penampilan',
'Perilaku_dan_aktivitas_psikomotor',
'Sikap_terhadap_pemeriksa',
'Irama',
'Kecepatan_bicara',
'Volume',
'Kelancaran',
'Mood',
'Afek',
'Keserasian',
'Auditorik',
'Visual',
'Taktil',
'Olfaktorik',
'Gustatorik',
'Ilusi',
'Depersonalisasi',
'Derealisasi',
'Blocking',
'Assosiasi_Longgar',
'Inkoheren',
'Flight_of_Idea',
'Sirkumstansia',
'Tangensial',
'Neologisme',
'Word_Salad',
'Hendaya_Berbahasa',
'Produktivitas',
'Preokupasi',
'Waham_bizarre',
'Waham_sistemik',
'Waham_nihilistik',
'Waham_paranoid',
'Waham_kebesaran',
'Waham_kejaran',
'Waham_rujukan',
'Waham_dikendalikan',
'Thought_of_withdrawl',
'Thought_of_insertion',
'Thought_of_broadcasting',
'Obsesi',
'Kompulsif',
'Fobia',
'Gagasan_untuk_bunuh_diri',
'Taraf_kesadaran_dan_kesiagaan',
'Orieantasi_Waktu',
'Orieantasi_Tempat',
'Orieantasi_Orang',
'Daya_ingat_Jangka_panjang',
'Daya_ingat_Jangka_sedang',
'Daya_ingat_Jangka_pendek',
'Daya_ingat_Jangka_segera',
'Konsentrasi_perhatian',
'Kemampuan_Membaca_Menulis',
'Kemampuan_visuospasial',
'Pikiran_abstrak',
'Inteligensia_dan_kemampuan_informasi',
'Kemampuan_mengendalikan_impuls',
'Daya_nilai_dan_tilikan',
'Daya_nilai_sosial',
'Uji_daya_nilai',
'Penilaian_Daya_Realita',
'Tilikan',
'Taraf_dipercaya',
'Keadaan_Umum',
'Kesadaran',
'Status_gizi',
'Tekanan_Darah',
'Frekuensi_Nadi',
'Frekuensi_Nafas',
'Suhu',
'Mata_dan_THT',
'Mulut_dan_Gigi',
'Thorax',
'Abdomen',
'Extremitas',
'Tanda_rangsang_Meningeal',
'Motorik',
'Sensorik',
'Diagnosis_Axis',
'Organobiologi',
'Psikologi',
'Lingkungan_dan_sosial_ekonomi',
'Quo_ad_Vitam',
'Quo_ad_Fungsionam',
'Quo_ad_Sanationam',
'Hal-hal_yang_mendukung',
'Hal-hal_yang_memberatkan',
'Farmakologi',
'Non_Farmakologi',
'id_pasien',
'id_user',
'id_resep',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'export_field1' ),
'Anamnesis' => array( 'export_field2' ),
'Autoanamnesis' => array( 'export_field3' ),
'Alloanamnesis' => array( 'export_field4' ),
'Riwayat_gangguan_sekarang' => array( 'export_field5' ),
'Riwayat_gangguan_dahulu' => array( 'export_field6' ),
'Riwayat_gangguan_psikiatri' => array( 'export_field7' ),
'Riwayat_gangguan_medis' => array( 'export_field8' ),
'Riwayat_penggunaan_zat_psikoaktif' => array( 'export_field9' ),
'Riwayat_prenatal_dan_perinatal' => array( 'export_field10' ),
'Riwayat_masa_kanak_awal' => array( 'export_field11' ),
'Riwayat_masa_kanak_pertengahan' => array( 'export_field12' ),
'Riwayat_masa_kanak_akhir_dan_remaja' => array( 'export_field13' ),
'Masa_Dewasa' => array( 'export_field14' ),
'Riwayat_pendidikan' => array( 'export_field15' ),
'Riwayat_pekerjaan' => array( 'export_field16' ),
'Riwayat_pernikahan' => array( 'export_field17' ),
'Riwayat_Agama' => array( 'export_field18' ),
'Riwayat_Psikoseksual' => array( 'export_field19' ),
'Riwayat_aktivitas_sosial' => array( 'export_field20' ),
'Riwayat_hukum' => array( 'export_field21' ),
'Riwayat_keluarga' => array( 'export_field22' ),
'Genogram_keluarga' => array( 'export_field23' ),
'Situasi_kehidupan_sekarang' => array( 'export_field24' ),
'Persepsi_tentang_diri_dan_kehidupannya' => array( 'export_field25' ),
'Persepsi_keluarga_tentang_diri_pasien' => array( 'export_field26' ),
'Fantasi' => array( 'export_field27' ),
'Penampilan' => array( 'export_field28' ),
'Perilaku_dan_aktivitas_psikomotor' => array( 'export_field29' ),
'Sikap_terhadap_pemeriksa' => array( 'export_field30' ),
'Irama' => array( 'export_field31' ),
'Kecepatan_bicara' => array( 'export_field32' ),
'Volume' => array( 'export_field33' ),
'Kelancaran' => array( 'export_field34' ),
'Mood' => array( 'export_field35' ),
'Afek' => array( 'export_field36' ),
'Keserasian' => array( 'export_field37' ),
'Auditorik' => array( 'export_field38' ),
'Visual' => array( 'export_field39' ),
'Taktil' => array( 'export_field40' ),
'Olfaktorik' => array( 'export_field41' ),
'Gustatorik' => array( 'export_field42' ),
'Ilusi' => array( 'export_field43' ),
'Depersonalisasi' => array( 'export_field44' ),
'Derealisasi' => array( 'export_field45' ),
'Blocking' => array( 'export_field46' ),
'Assosiasi_Longgar' => array( 'export_field47' ),
'Inkoheren' => array( 'export_field48' ),
'Flight_of_Idea' => array( 'export_field49' ),
'Sirkumstansia' => array( 'export_field50' ),
'Tangensial' => array( 'export_field51' ),
'Neologisme' => array( 'export_field52' ),
'Word_Salad' => array( 'export_field53' ),
'Hendaya_Berbahasa' => array( 'export_field54' ),
'Produktivitas' => array( 'export_field55' ),
'Preokupasi' => array( 'export_field56' ),
'Waham_bizarre' => array( 'export_field57' ),
'Waham_sistemik' => array( 'export_field58' ),
'Waham_nihilistik' => array( 'export_field59' ),
'Waham_paranoid' => array( 'export_field60' ),
'Waham_kebesaran' => array( 'export_field61' ),
'Waham_kejaran' => array( 'export_field62' ),
'Waham_rujukan' => array( 'export_field63' ),
'Waham_dikendalikan' => array( 'export_field64' ),
'Thought_of_withdrawl' => array( 'export_field65' ),
'Thought_of_insertion' => array( 'export_field66' ),
'Thought_of_broadcasting' => array( 'export_field67' ),
'Obsesi' => array( 'export_field68' ),
'Kompulsif' => array( 'export_field69' ),
'Fobia' => array( 'export_field70' ),
'Gagasan_untuk_bunuh_diri' => array( 'export_field71' ),
'Taraf_kesadaran_dan_kesiagaan' => array( 'export_field72' ),
'Orieantasi_Waktu' => array( 'export_field73' ),
'Orieantasi_Tempat' => array( 'export_field74' ),
'Orieantasi_Orang' => array( 'export_field75' ),
'Daya_ingat_Jangka_panjang' => array( 'export_field76' ),
'Daya_ingat_Jangka_sedang' => array( 'export_field77' ),
'Daya_ingat_Jangka_pendek' => array( 'export_field78' ),
'Daya_ingat_Jangka_segera' => array( 'export_field79' ),
'Konsentrasi_perhatian' => array( 'export_field80' ),
'Kemampuan_Membaca_Menulis' => array( 'export_field81' ),
'Kemampuan_visuospasial' => array( 'export_field82' ),
'Pikiran_abstrak' => array( 'export_field83' ),
'Inteligensia_dan_kemampuan_informasi' => array( 'export_field84' ),
'Kemampuan_mengendalikan_impuls' => array( 'export_field85' ),
'Daya_nilai_dan_tilikan' => array( 'export_field86' ),
'Daya_nilai_sosial' => array( 'export_field87' ),
'Uji_daya_nilai' => array( 'export_field88' ),
'Penilaian_Daya_Realita' => array( 'export_field89' ),
'Tilikan' => array( 'export_field90' ),
'Taraf_dipercaya' => array( 'export_field91' ),
'Keadaan_Umum' => array( 'export_field92' ),
'Kesadaran' => array( 'export_field93' ),
'Status_gizi' => array( 'export_field94' ),
'Tekanan_Darah' => array( 'export_field95' ),
'Frekuensi_Nadi' => array( 'export_field96' ),
'Frekuensi_Nafas' => array( 'export_field97' ),
'Suhu' => array( 'export_field98' ),
'Mata_dan_THT' => array( 'export_field99' ),
'Mulut_dan_Gigi' => array( 'export_field100' ),
'Thorax' => array( 'export_field101' ),
'Abdomen' => array( 'export_field102' ),
'Extremitas' => array( 'export_field103' ),
'Tanda_rangsang_Meningeal' => array( 'export_field104' ),
'Motorik' => array( 'export_field105' ),
'Sensorik' => array( 'export_field106' ),
'Diagnosis_Axis' => array( 'export_field107' ),
'Organobiologi' => array( 'export_field108' ),
'Psikologi' => array( 'export_field109' ),
'Lingkungan_dan_sosial_ekonomi' => array( 'export_field110' ),
'Quo_ad_Vitam' => array( 'export_field111' ),
'Quo_ad_Fungsionam' => array( 'export_field112' ),
'Quo_ad_Sanationam' => array( 'export_field113' ),
'Hal-hal_yang_mendukung' => array( 'export_field114' ),
'Hal-hal_yang_memberatkan' => array( 'export_field115' ),
'Farmakologi' => array( 'export_field116' ),
'Non_Farmakologi' => array( 'export_field117' ),
'id_pasien' => array( 'export_field' ),
'id_user' => array( 'export_field118' ),
'id_resep' => array( 'export_field119' ),
'Nomor_Rm' => array( 'export_field120' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106',
'export_field107',
'export_field108',
'export_field109',
'export_field110',
'export_field111',
'export_field112',
'export_field113',
'export_field114',
'export_field115',
'export_field116',
'export_field117',
'export_field',
'export_field118',
'export_field119',
'export_field120' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field62' => 'grid',
'export_field63' => 'grid',
'export_field64' => 'grid',
'export_field65' => 'grid',
'export_field66' => 'grid',
'export_field67' => 'grid',
'export_field68' => 'grid',
'export_field69' => 'grid',
'export_field70' => 'grid',
'export_field71' => 'grid',
'export_field72' => 'grid',
'export_field73' => 'grid',
'export_field74' => 'grid',
'export_field75' => 'grid',
'export_field76' => 'grid',
'export_field77' => 'grid',
'export_field78' => 'grid',
'export_field79' => 'grid',
'export_field80' => 'grid',
'export_field81' => 'grid',
'export_field82' => 'grid',
'export_field83' => 'grid',
'export_field84' => 'grid',
'export_field85' => 'grid',
'export_field86' => 'grid',
'export_field87' => 'grid',
'export_field88' => 'grid',
'export_field89' => 'grid',
'export_field90' => 'grid',
'export_field91' => 'grid',
'export_field92' => 'grid',
'export_field93' => 'grid',
'export_field94' => 'grid',
'export_field95' => 'grid',
'export_field96' => 'grid',
'export_field97' => 'grid',
'export_field98' => 'grid',
'export_field99' => 'grid',
'export_field100' => 'grid',
'export_field101' => 'grid',
'export_field102' => 'grid',
'export_field103' => 'grid',
'export_field104' => 'grid',
'export_field105' => 'grid',
'export_field106' => 'grid',
'export_field107' => 'grid',
'export_field108' => 'grid',
'export_field109' => 'grid',
'export_field110' => 'grid',
'export_field111' => 'grid',
'export_field112' => 'grid',
'export_field113' => 'grid',
'export_field114' => 'grid',
'export_field115' => 'grid',
'export_field116' => 'grid',
'export_field117' => 'grid',
'export_field' => 'grid',
'export_field118' => 'grid',
'export_field119' => 'grid',
'export_field120' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106',
'export_field107',
'export_field108',
'export_field109',
'export_field110',
'export_field111',
'export_field112',
'export_field113',
'export_field114',
'export_field115',
'export_field116',
'export_field117',
'export_field',
'export_field118',
'export_field119',
'export_field120' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68',
'export_field69',
'export_field70',
'export_field71',
'export_field72',
'export_field73',
'export_field74',
'export_field75',
'export_field76',
'export_field77',
'export_field78',
'export_field79',
'export_field80',
'export_field81',
'export_field82',
'export_field83',
'export_field84',
'export_field85',
'export_field86',
'export_field87',
'export_field88',
'export_field89',
'export_field90',
'export_field91',
'export_field92',
'export_field93',
'export_field94',
'export_field95',
'export_field96',
'export_field97',
'export_field98',
'export_field99',
'export_field100',
'export_field101',
'export_field102',
'export_field103',
'export_field104',
'export_field105',
'export_field106',
'export_field107',
'export_field108',
'export_field109',
'export_field110',
'export_field111',
'export_field112',
'export_field113',
'export_field114',
'export_field115',
'export_field116',
'export_field117',
'export_field',
'export_field118',
'export_field119',
'export_field120' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Anamnesis',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Autoanamnesis',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Alloanamnesis',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Riwayat_gangguan_sekarang',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Riwayat_gangguan_dahulu',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Riwayat_gangguan_psikiatri',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Riwayat_gangguan_medis',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Riwayat_penggunaan_zat_psikoaktif',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Riwayat_prenatal_dan_perinatal',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Riwayat_masa_kanak_awal',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Riwayat_masa_kanak_pertengahan',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Riwayat_masa_kanak_akhir_dan_remaja',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Masa_Dewasa',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Riwayat_pendidikan',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Riwayat_pekerjaan',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Riwayat_pernikahan',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Riwayat_Agama',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Riwayat_Psikoseksual',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Riwayat_aktivitas_sosial',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Riwayat_hukum',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Riwayat_keluarga',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Genogram_keluarga',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Situasi_kehidupan_sekarang',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Persepsi_tentang_diri_dan_kehidupannya',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Persepsi_keluarga_tentang_diri_pasien',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Fantasi',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Penampilan',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Perilaku_dan_aktivitas_psikomotor',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Sikap_terhadap_pemeriksa',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'Irama',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'Kecepatan_bicara',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'Volume',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'Kelancaran',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Mood',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'Afek',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'Keserasian',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'Auditorik',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'Visual',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'Taktil',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'Olfaktorik',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'Gustatorik',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'Ilusi',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'Depersonalisasi',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'Derealisasi',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'Blocking',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'Assosiasi_Longgar',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'Inkoheren',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'Flight_of_Idea',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'Sirkumstansia',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'Tangensial',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'Neologisme',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'Word_Salad',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'Hendaya_Berbahasa',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'Produktivitas',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'Preokupasi',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'Waham_bizarre',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'Waham_sistemik',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'Waham_nihilistik',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'Waham_paranoid',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'Waham_kebesaran',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'Waham_kejaran',
'type' => 'export_field' ),
'export_field63' => array( 'field' => 'Waham_rujukan',
'type' => 'export_field' ),
'export_field64' => array( 'field' => 'Waham_dikendalikan',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'Thought_of_withdrawl',
'type' => 'export_field' ),
'export_field66' => array( 'field' => 'Thought_of_insertion',
'type' => 'export_field' ),
'export_field67' => array( 'field' => 'Thought_of_broadcasting',
'type' => 'export_field' ),
'export_field68' => array( 'field' => 'Obsesi',
'type' => 'export_field' ),
'export_field69' => array( 'field' => 'Kompulsif',
'type' => 'export_field' ),
'export_field70' => array( 'field' => 'Fobia',
'type' => 'export_field' ),
'export_field71' => array( 'field' => 'Gagasan_untuk_bunuh_diri',
'type' => 'export_field' ),
'export_field72' => array( 'field' => 'Taraf_kesadaran_dan_kesiagaan',
'type' => 'export_field' ),
'export_field73' => array( 'field' => 'Orieantasi_Waktu',
'type' => 'export_field' ),
'export_field74' => array( 'field' => 'Orieantasi_Tempat',
'type' => 'export_field' ),
'export_field75' => array( 'field' => 'Orieantasi_Orang',
'type' => 'export_field' ),
'export_field76' => array( 'field' => 'Daya_ingat_Jangka_panjang',
'type' => 'export_field' ),
'export_field77' => array( 'field' => 'Daya_ingat_Jangka_sedang',
'type' => 'export_field' ),
'export_field78' => array( 'field' => 'Daya_ingat_Jangka_pendek',
'type' => 'export_field' ),
'export_field79' => array( 'field' => 'Daya_ingat_Jangka_segera',
'type' => 'export_field' ),
'export_field80' => array( 'field' => 'Konsentrasi_perhatian',
'type' => 'export_field' ),
'export_field81' => array( 'field' => 'Kemampuan_Membaca_Menulis',
'type' => 'export_field' ),
'export_field82' => array( 'field' => 'Kemampuan_visuospasial',
'type' => 'export_field' ),
'export_field83' => array( 'field' => 'Pikiran_abstrak',
'type' => 'export_field' ),
'export_field84' => array( 'field' => 'Inteligensia_dan_kemampuan_informasi',
'type' => 'export_field' ),
'export_field85' => array( 'field' => 'Kemampuan_mengendalikan_impuls',
'type' => 'export_field' ),
'export_field86' => array( 'field' => 'Daya_nilai_dan_tilikan',
'type' => 'export_field' ),
'export_field87' => array( 'field' => 'Daya_nilai_sosial',
'type' => 'export_field' ),
'export_field88' => array( 'field' => 'Uji_daya_nilai',
'type' => 'export_field' ),
'export_field89' => array( 'field' => 'Penilaian_Daya_Realita',
'type' => 'export_field' ),
'export_field90' => array( 'field' => 'Tilikan',
'type' => 'export_field' ),
'export_field91' => array( 'field' => 'Taraf_dipercaya',
'type' => 'export_field' ),
'export_field92' => array( 'field' => 'Keadaan_Umum',
'type' => 'export_field' ),
'export_field93' => array( 'field' => 'Kesadaran',
'type' => 'export_field' ),
'export_field94' => array( 'field' => 'Status_gizi',
'type' => 'export_field' ),
'export_field95' => array( 'field' => 'Tekanan_Darah',
'type' => 'export_field' ),
'export_field96' => array( 'field' => 'Frekuensi_Nadi',
'type' => 'export_field' ),
'export_field97' => array( 'field' => 'Frekuensi_Nafas',
'type' => 'export_field' ),
'export_field98' => array( 'field' => 'Suhu',
'type' => 'export_field' ),
'export_field99' => array( 'field' => 'Mata_dan_THT',
'type' => 'export_field' ),
'export_field100' => array( 'field' => 'Mulut_dan_Gigi',
'type' => 'export_field' ),
'export_field101' => array( 'field' => 'Thorax',
'type' => 'export_field' ),
'export_field102' => array( 'field' => 'Abdomen',
'type' => 'export_field' ),
'export_field103' => array( 'field' => 'Extremitas',
'type' => 'export_field' ),
'export_field104' => array( 'field' => 'Tanda_rangsang_Meningeal',
'type' => 'export_field' ),
'export_field105' => array( 'field' => 'Motorik',
'type' => 'export_field' ),
'export_field106' => array( 'field' => 'Sensorik',
'type' => 'export_field' ),
'export_field107' => array( 'field' => 'Diagnosis_Axis',
'type' => 'export_field' ),
'export_field108' => array( 'field' => 'Organobiologi',
'type' => 'export_field' ),
'export_field109' => array( 'field' => 'Psikologi',
'type' => 'export_field' ),
'export_field110' => array( 'field' => 'Lingkungan_dan_sosial_ekonomi',
'type' => 'export_field' ),
'export_field111' => array( 'field' => 'Quo_ad_Vitam',
'type' => 'export_field' ),
'export_field112' => array( 'field' => 'Quo_ad_Fungsionam',
'type' => 'export_field' ),
'export_field113' => array( 'field' => 'Quo_ad_Sanationam',
'type' => 'export_field' ),
'export_field114' => array( 'field' => 'Hal-hal_yang_mendukung',
'type' => 'export_field' ),
'export_field115' => array( 'field' => 'Hal-hal_yang_memberatkan',
'type' => 'export_field' ),
'export_field116' => array( 'field' => 'Farmakologi',
'type' => 'export_field' ),
'export_field117' => array( 'field' => 'Non_Farmakologi',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'id_pasien',
'type' => 'export_field' ),
'export_field118' => array( 'field' => 'id_user',
'type' => 'export_field' ),
'export_field119' => array( 'field' => 'id_resep',
'type' => 'export_field' ),
'export_field120' => array( 'field' => 'Nomor_Rm',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>