<?php
			$optionsArray = array( 'master' => array( 'identitas_pasien' => array( 'preview' => true ),
'users' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Anamnesis',
'Autoanamnesis',
'Alloanamnesis',
'Riwayat_gangguan_sekarang',
'Riwayat_gangguan_dahulu',
'Riwayat_gangguan_psikiatri',
'Riwayat_gangguan_medis',
'Riwayat_penggunaan_zat_psikoaktif',
'Riwayat_prenatal_dan_perinatal',
'Riwayat_masa_kanak_awal',
'Riwayat_masa_kanak_pertengahan',
'Riwayat_masa_kanak_akhir_dan_remaja',
'Masa_Dewasa',
'Riwayat_pendidikan',
'Riwayat_pekerjaan',
'Riwayat_pernikahan',
'Riwayat_Agama',
'Riwayat_Psikoseksual',
'Riwayat_aktivitas_sosial',
'Riwayat_hukum',
'Riwayat_keluarga',
'Genogram_keluarga',
'Situasi_kehidupan_sekarang',
'Persepsi_tentang_diri_dan_kehidupannya',
'Persepsi_keluarga_tentang_diri_pasien',
'Fantasi',
'Penampilan',
'Perilaku_dan_aktivitas_psikomotor',
'Sikap_terhadap_pemeriksa',
'Irama',
'Kecepatan_bicara',
'Volume',
'Kelancaran',
'Mood',
'Afek',
'Keserasian',
'Auditorik',
'Visual',
'Taktil',
'Olfaktorik',
'Gustatorik',
'Ilusi',
'Depersonalisasi',
'Derealisasi',
'Blocking',
'Assosiasi_Longgar',
'Inkoheren',
'Flight_of_Idea',
'Sirkumstansia',
'Tangensial',
'Neologisme',
'Word_Salad',
'Hendaya_Berbahasa',
'Produktivitas',
'Preokupasi',
'Waham_bizarre',
'Waham_sistemik',
'Waham_nihilistik',
'Waham_paranoid',
'Waham_kebesaran',
'Waham_kejaran',
'Waham_rujukan',
'Waham_dikendalikan',
'Thought_of_withdrawl',
'Thought_of_insertion',
'Thought_of_broadcasting',
'Obsesi',
'Kompulsif',
'Fobia',
'Gagasan_untuk_bunuh_diri',
'Taraf_kesadaran_dan_kesiagaan',
'Orieantasi_Waktu',
'Orieantasi_Tempat',
'Orieantasi_Orang',
'Daya_ingat_Jangka_panjang',
'Daya_ingat_Jangka_sedang',
'Daya_ingat_Jangka_pendek',
'Daya_ingat_Jangka_segera',
'Konsentrasi_perhatian',
'Kemampuan_Membaca_Menulis',
'Kemampuan_visuospasial',
'Pikiran_abstrak',
'Inteligensia_dan_kemampuan_informasi',
'Kemampuan_mengendalikan_impuls',
'Daya_nilai_dan_tilikan',
'Daya_nilai_sosial',
'Uji_daya_nilai',
'Penilaian_Daya_Realita',
'Tilikan',
'Taraf_dipercaya',
'Keadaan_Umum',
'Kesadaran',
'Status_gizi',
'Tekanan_Darah',
'Frekuensi_Nadi',
'Frekuensi_Nafas',
'Suhu',
'Mata_dan_THT',
'Mulut_dan_Gigi',
'Thorax',
'Abdomen',
'Extremitas',
'Tanda_rangsang_Meningeal',
'Motorik',
'Sensorik',
'Diagnosis_Axis',
'Organobiologi',
'Psikologi',
'Lingkungan_dan_sosial_ekonomi',
'Quo_ad_Vitam',
'Quo_ad_Fungsionam',
'Quo_ad_Sanationam',
'Hal-hal_yang_mendukung',
'Hal-hal_yang_memberatkan',
'Farmakologi',
'Non_Farmakologi',
'id_pasien',
'id_user',
'id_resep',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'integrated_edit_field' ),
'Anamnesis' => array( 'integrated_edit_field1' ),
'Autoanamnesis' => array( 'integrated_edit_field2' ),
'Alloanamnesis' => array( 'integrated_edit_field3' ),
'Riwayat_gangguan_sekarang' => array( 'integrated_edit_field4' ),
'Riwayat_gangguan_dahulu' => array( 'integrated_edit_field5' ),
'Riwayat_gangguan_psikiatri' => array( 'integrated_edit_field6' ),
'Riwayat_gangguan_medis' => array( 'integrated_edit_field7' ),
'Riwayat_penggunaan_zat_psikoaktif' => array( 'integrated_edit_field8' ),
'Riwayat_prenatal_dan_perinatal' => array( 'integrated_edit_field9' ),
'Riwayat_masa_kanak_awal' => array( 'integrated_edit_field10' ),
'Riwayat_masa_kanak_pertengahan' => array( 'integrated_edit_field11' ),
'Riwayat_masa_kanak_akhir_dan_remaja' => array( 'integrated_edit_field12' ),
'Masa_Dewasa' => array( 'integrated_edit_field13' ),
'Riwayat_pendidikan' => array( 'integrated_edit_field14' ),
'Riwayat_pekerjaan' => array( 'integrated_edit_field15' ),
'Riwayat_pernikahan' => array( 'integrated_edit_field16' ),
'Riwayat_Agama' => array( 'integrated_edit_field17' ),
'Riwayat_Psikoseksual' => array( 'integrated_edit_field18' ),
'Riwayat_aktivitas_sosial' => array( 'integrated_edit_field19' ),
'Riwayat_hukum' => array( 'integrated_edit_field20' ),
'Riwayat_keluarga' => array( 'integrated_edit_field21' ),
'Genogram_keluarga' => array( 'integrated_edit_field22' ),
'Situasi_kehidupan_sekarang' => array( 'integrated_edit_field23' ),
'Persepsi_tentang_diri_dan_kehidupannya' => array( 'integrated_edit_field24' ),
'Persepsi_keluarga_tentang_diri_pasien' => array( 'integrated_edit_field25' ),
'Fantasi' => array( 'integrated_edit_field26' ),
'Penampilan' => array( 'integrated_edit_field27' ),
'Perilaku_dan_aktivitas_psikomotor' => array( 'integrated_edit_field28' ),
'Sikap_terhadap_pemeriksa' => array( 'integrated_edit_field29' ),
'Irama' => array( 'integrated_edit_field30' ),
'Kecepatan_bicara' => array( 'integrated_edit_field31' ),
'Volume' => array( 'integrated_edit_field32' ),
'Kelancaran' => array( 'integrated_edit_field33' ),
'Mood' => array( 'integrated_edit_field34' ),
'Afek' => array( 'integrated_edit_field35' ),
'Keserasian' => array( 'integrated_edit_field36' ),
'Auditorik' => array( 'integrated_edit_field37' ),
'Visual' => array( 'integrated_edit_field38' ),
'Taktil' => array( 'integrated_edit_field39' ),
'Olfaktorik' => array( 'integrated_edit_field40' ),
'Gustatorik' => array( 'integrated_edit_field41' ),
'Ilusi' => array( 'integrated_edit_field42' ),
'Depersonalisasi' => array( 'integrated_edit_field43' ),
'Derealisasi' => array( 'integrated_edit_field44' ),
'Blocking' => array( 'integrated_edit_field45' ),
'Assosiasi_Longgar' => array( 'integrated_edit_field46' ),
'Inkoheren' => array( 'integrated_edit_field47' ),
'Flight_of_Idea' => array( 'integrated_edit_field48' ),
'Sirkumstansia' => array( 'integrated_edit_field49' ),
'Tangensial' => array( 'integrated_edit_field50' ),
'Neologisme' => array( 'integrated_edit_field51' ),
'Word_Salad' => array( 'integrated_edit_field52' ),
'Hendaya_Berbahasa' => array( 'integrated_edit_field53' ),
'Produktivitas' => array( 'integrated_edit_field54' ),
'Preokupasi' => array( 'integrated_edit_field55' ),
'Waham_bizarre' => array( 'integrated_edit_field56' ),
'Waham_sistemik' => array( 'integrated_edit_field57' ),
'Waham_nihilistik' => array( 'integrated_edit_field58' ),
'Waham_paranoid' => array( 'integrated_edit_field59' ),
'Waham_kebesaran' => array( 'integrated_edit_field60' ),
'Waham_kejaran' => array( 'integrated_edit_field61' ),
'Waham_rujukan' => array( 'integrated_edit_field62' ),
'Waham_dikendalikan' => array( 'integrated_edit_field63' ),
'Thought_of_withdrawl' => array( 'integrated_edit_field64' ),
'Thought_of_insertion' => array( 'integrated_edit_field65' ),
'Thought_of_broadcasting' => array( 'integrated_edit_field66' ),
'Obsesi' => array( 'integrated_edit_field67' ),
'Kompulsif' => array( 'integrated_edit_field68' ),
'Fobia' => array( 'integrated_edit_field69' ),
'Gagasan_untuk_bunuh_diri' => array( 'integrated_edit_field70' ),
'Taraf_kesadaran_dan_kesiagaan' => array( 'integrated_edit_field71' ),
'Orieantasi_Waktu' => array( 'integrated_edit_field72' ),
'Orieantasi_Tempat' => array( 'integrated_edit_field73' ),
'Orieantasi_Orang' => array( 'integrated_edit_field74' ),
'Daya_ingat_Jangka_panjang' => array( 'integrated_edit_field75' ),
'Daya_ingat_Jangka_sedang' => array( 'integrated_edit_field76' ),
'Daya_ingat_Jangka_pendek' => array( 'integrated_edit_field77' ),
'Daya_ingat_Jangka_segera' => array( 'integrated_edit_field78' ),
'Konsentrasi_perhatian' => array( 'integrated_edit_field79' ),
'Kemampuan_Membaca_Menulis' => array( 'integrated_edit_field80' ),
'Kemampuan_visuospasial' => array( 'integrated_edit_field81' ),
'Pikiran_abstrak' => array( 'integrated_edit_field82' ),
'Inteligensia_dan_kemampuan_informasi' => array( 'integrated_edit_field83' ),
'Kemampuan_mengendalikan_impuls' => array( 'integrated_edit_field84' ),
'Daya_nilai_dan_tilikan' => array( 'integrated_edit_field85' ),
'Daya_nilai_sosial' => array( 'integrated_edit_field86' ),
'Uji_daya_nilai' => array( 'integrated_edit_field87' ),
'Penilaian_Daya_Realita' => array( 'integrated_edit_field88' ),
'Tilikan' => array( 'integrated_edit_field89' ),
'Taraf_dipercaya' => array( 'integrated_edit_field90' ),
'Keadaan_Umum' => array( 'integrated_edit_field91' ),
'Kesadaran' => array( 'integrated_edit_field92' ),
'Status_gizi' => array( 'integrated_edit_field93' ),
'Tekanan_Darah' => array( 'integrated_edit_field94' ),
'Frekuensi_Nadi' => array( 'integrated_edit_field95' ),
'Frekuensi_Nafas' => array( 'integrated_edit_field96' ),
'Suhu' => array( 'integrated_edit_field97' ),
'Mata_dan_THT' => array( 'integrated_edit_field98' ),
'Mulut_dan_Gigi' => array( 'integrated_edit_field99' ),
'Thorax' => array( 'integrated_edit_field100' ),
'Abdomen' => array( 'integrated_edit_field101' ),
'Extremitas' => array( 'integrated_edit_field102' ),
'Tanda_rangsang_Meningeal' => array( 'integrated_edit_field103' ),
'Motorik' => array( 'integrated_edit_field104' ),
'Sensorik' => array( 'integrated_edit_field105' ),
'Diagnosis_Axis' => array( 'integrated_edit_field106' ),
'Organobiologi' => array( 'integrated_edit_field107' ),
'Psikologi' => array( 'integrated_edit_field108' ),
'Lingkungan_dan_sosial_ekonomi' => array( 'integrated_edit_field109' ),
'Quo_ad_Vitam' => array( 'integrated_edit_field110' ),
'Quo_ad_Fungsionam' => array( 'integrated_edit_field111' ),
'Quo_ad_Sanationam' => array( 'integrated_edit_field112' ),
'Hal-hal_yang_mendukung' => array( 'integrated_edit_field113' ),
'Hal-hal_yang_memberatkan' => array( 'integrated_edit_field114' ),
'Farmakologi' => array( 'integrated_edit_field115' ),
'Non_Farmakologi' => array( 'integrated_edit_field116' ),
'id_pasien' => array( 'integrated_edit_field117' ),
'id_user' => array( 'integrated_edit_field118' ),
'id_resep' => array( 'integrated_edit_field119' ),
'Nomor_Rm' => array( 'integrated_edit_field120' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105',
'integrated_edit_field106',
'integrated_edit_field107',
'integrated_edit_field108',
'integrated_edit_field109',
'integrated_edit_field110',
'integrated_edit_field111',
'integrated_edit_field112',
'integrated_edit_field113',
'integrated_edit_field114',
'integrated_edit_field115',
'integrated_edit_field116',
'integrated_edit_field117',
'integrated_edit_field118',
'integrated_edit_field119',
'integrated_edit_field120' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field34' => 'grid',
'integrated_edit_field35' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field37' => 'grid',
'integrated_edit_field38' => 'grid',
'integrated_edit_field39' => 'grid',
'integrated_edit_field40' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field52' => 'grid',
'integrated_edit_field53' => 'grid',
'integrated_edit_field54' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field58' => 'grid',
'integrated_edit_field59' => 'grid',
'integrated_edit_field60' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field62' => 'grid',
'integrated_edit_field63' => 'grid',
'integrated_edit_field64' => 'grid',
'integrated_edit_field65' => 'grid',
'integrated_edit_field66' => 'grid',
'integrated_edit_field67' => 'grid',
'integrated_edit_field68' => 'grid',
'integrated_edit_field69' => 'grid',
'integrated_edit_field70' => 'grid',
'integrated_edit_field71' => 'grid',
'integrated_edit_field72' => 'grid',
'integrated_edit_field73' => 'grid',
'integrated_edit_field74' => 'grid',
'integrated_edit_field75' => 'grid',
'integrated_edit_field76' => 'grid',
'integrated_edit_field77' => 'grid',
'integrated_edit_field78' => 'grid',
'integrated_edit_field79' => 'grid',
'integrated_edit_field80' => 'grid',
'integrated_edit_field81' => 'grid',
'integrated_edit_field82' => 'grid',
'integrated_edit_field83' => 'grid',
'integrated_edit_field84' => 'grid',
'integrated_edit_field85' => 'grid',
'integrated_edit_field86' => 'grid',
'integrated_edit_field87' => 'grid',
'integrated_edit_field88' => 'grid',
'integrated_edit_field89' => 'grid',
'integrated_edit_field90' => 'grid',
'integrated_edit_field91' => 'grid',
'integrated_edit_field92' => 'grid',
'integrated_edit_field93' => 'grid',
'integrated_edit_field94' => 'grid',
'integrated_edit_field95' => 'grid',
'integrated_edit_field96' => 'grid',
'integrated_edit_field97' => 'grid',
'integrated_edit_field98' => 'grid',
'integrated_edit_field99' => 'grid',
'integrated_edit_field100' => 'grid',
'integrated_edit_field101' => 'grid',
'integrated_edit_field102' => 'grid',
'integrated_edit_field103' => 'grid',
'integrated_edit_field104' => 'grid',
'integrated_edit_field105' => 'grid',
'integrated_edit_field106' => 'grid',
'integrated_edit_field107' => 'grid',
'integrated_edit_field108' => 'grid',
'integrated_edit_field109' => 'grid',
'integrated_edit_field110' => 'grid',
'integrated_edit_field111' => 'grid',
'integrated_edit_field112' => 'grid',
'integrated_edit_field113' => 'grid',
'integrated_edit_field114' => 'grid',
'integrated_edit_field115' => 'grid',
'integrated_edit_field116' => 'grid',
'integrated_edit_field117' => 'grid',
'integrated_edit_field118' => 'grid',
'integrated_edit_field119' => 'grid',
'integrated_edit_field120' => 'grid' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field88' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field89' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field90' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field91' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field92' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field93' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field94' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field95' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field96' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field97' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field98' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field99' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field100' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field101' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field102' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field103' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field104' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field105' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field106' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field107' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field108' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field109' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field110' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field111' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field112' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field113' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field114' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field115' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field116' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field117' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field118' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field119' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field120' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105',
'integrated_edit_field106',
'integrated_edit_field107',
'integrated_edit_field108',
'integrated_edit_field109',
'integrated_edit_field110',
'integrated_edit_field111',
'integrated_edit_field112',
'integrated_edit_field113',
'integrated_edit_field114',
'integrated_edit_field115',
'integrated_edit_field116',
'integrated_edit_field117',
'integrated_edit_field118',
'integrated_edit_field119',
'integrated_edit_field120' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105',
'integrated_edit_field106',
'integrated_edit_field107',
'integrated_edit_field108',
'integrated_edit_field109',
'integrated_edit_field110',
'integrated_edit_field111',
'integrated_edit_field112',
'integrated_edit_field113',
'integrated_edit_field114',
'integrated_edit_field115',
'integrated_edit_field116',
'integrated_edit_field117',
'integrated_edit_field118',
'integrated_edit_field119',
'integrated_edit_field120' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field52',
'integrated_edit_field53',
'integrated_edit_field54',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field58',
'integrated_edit_field59',
'integrated_edit_field60',
'integrated_edit_field61',
'integrated_edit_field62',
'integrated_edit_field63',
'integrated_edit_field64',
'integrated_edit_field65',
'integrated_edit_field66',
'integrated_edit_field67',
'integrated_edit_field68',
'integrated_edit_field69',
'integrated_edit_field70',
'integrated_edit_field71',
'integrated_edit_field72',
'integrated_edit_field73',
'integrated_edit_field74',
'integrated_edit_field75',
'integrated_edit_field76',
'integrated_edit_field77',
'integrated_edit_field78',
'integrated_edit_field79',
'integrated_edit_field80',
'integrated_edit_field81',
'integrated_edit_field82',
'integrated_edit_field83',
'integrated_edit_field84',
'integrated_edit_field85',
'integrated_edit_field86',
'integrated_edit_field87',
'integrated_edit_field88',
'integrated_edit_field89',
'integrated_edit_field90',
'integrated_edit_field91',
'integrated_edit_field92',
'integrated_edit_field93',
'integrated_edit_field94',
'integrated_edit_field95',
'integrated_edit_field96',
'integrated_edit_field97',
'integrated_edit_field98',
'integrated_edit_field99',
'integrated_edit_field100',
'integrated_edit_field101',
'integrated_edit_field102',
'integrated_edit_field103',
'integrated_edit_field104',
'integrated_edit_field105',
'integrated_edit_field106',
'integrated_edit_field107',
'integrated_edit_field108',
'integrated_edit_field109',
'integrated_edit_field110',
'integrated_edit_field111',
'integrated_edit_field112',
'integrated_edit_field113',
'integrated_edit_field114',
'integrated_edit_field115',
'integrated_edit_field116',
'integrated_edit_field117',
'integrated_edit_field118',
'integrated_edit_field119',
'integrated_edit_field120' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field' => array( 'field' => 'Keluhan_Utama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'Anamnesis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'Autoanamnesis',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'Alloanamnesis',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'Riwayat_gangguan_sekarang',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'Riwayat_gangguan_dahulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'Riwayat_gangguan_psikiatri',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'Riwayat_gangguan_medis',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'Riwayat_penggunaan_zat_psikoaktif',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'Riwayat_prenatal_dan_perinatal',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'Riwayat_masa_kanak_awal',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'Riwayat_masa_kanak_pertengahan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field12' => array( 'field' => 'Riwayat_masa_kanak_akhir_dan_remaja',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'Masa_Dewasa',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'Riwayat_pendidikan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field15' => array( 'field' => 'Riwayat_pekerjaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field16' => array( 'field' => 'Riwayat_pernikahan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field17' => array( 'field' => 'Riwayat_Agama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'Riwayat_Psikoseksual',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field19' => array( 'field' => 'Riwayat_aktivitas_sosial',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'Riwayat_hukum',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'Riwayat_keluarga',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field22' => array( 'field' => 'Genogram_keluarga',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'Situasi_kehidupan_sekarang',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'Persepsi_tentang_diri_dan_kehidupannya',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'Persepsi_keluarga_tentang_diri_pasien',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field26' => array( 'field' => 'Fantasi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'Penampilan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'Perilaku_dan_aktivitas_psikomotor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'Sikap_terhadap_pemeriksa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'Irama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field31' => array( 'field' => 'Kecepatan_bicara',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field32' => array( 'field' => 'Volume',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field33' => array( 'field' => 'Kelancaran',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field34' => array( 'field' => 'Mood',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field35' => array( 'field' => 'Afek',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field36' => array( 'field' => 'Keserasian',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field37' => array( 'field' => 'Auditorik',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field38' => array( 'field' => 'Visual',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field39' => array( 'field' => 'Taktil',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field40' => array( 'field' => 'Olfaktorik',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field41' => array( 'field' => 'Gustatorik',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field42' => array( 'field' => 'Ilusi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field43' => array( 'field' => 'Depersonalisasi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field44' => array( 'field' => 'Derealisasi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field45' => array( 'field' => 'Blocking',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field46' => array( 'field' => 'Assosiasi_Longgar',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field47' => array( 'field' => 'Inkoheren',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field48' => array( 'field' => 'Flight_of_Idea',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field49' => array( 'field' => 'Sirkumstansia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field50' => array( 'field' => 'Tangensial',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field51' => array( 'field' => 'Neologisme',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field52' => array( 'field' => 'Word_Salad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field53' => array( 'field' => 'Hendaya_Berbahasa',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field54' => array( 'field' => 'Produktivitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'Preokupasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'Waham_bizarre',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field57' => array( 'field' => 'Waham_sistemik',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field58' => array( 'field' => 'Waham_nihilistik',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field59' => array( 'field' => 'Waham_paranoid',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field60' => array( 'field' => 'Waham_kebesaran',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field61' => array( 'field' => 'Waham_kejaran',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field62' => array( 'field' => 'Waham_rujukan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field63' => array( 'field' => 'Waham_dikendalikan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field64' => array( 'field' => 'Thought_of_withdrawl',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field65' => array( 'field' => 'Thought_of_insertion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field66' => array( 'field' => 'Thought_of_broadcasting',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field67' => array( 'field' => 'Obsesi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field68' => array( 'field' => 'Kompulsif',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field69' => array( 'field' => 'Fobia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field70' => array( 'field' => 'Gagasan_untuk_bunuh_diri',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field71' => array( 'field' => 'Taraf_kesadaran_dan_kesiagaan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field72' => array( 'field' => 'Orieantasi_Waktu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field73' => array( 'field' => 'Orieantasi_Tempat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field74' => array( 'field' => 'Orieantasi_Orang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field75' => array( 'field' => 'Daya_ingat_Jangka_panjang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field76' => array( 'field' => 'Daya_ingat_Jangka_sedang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field77' => array( 'field' => 'Daya_ingat_Jangka_pendek',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field78' => array( 'field' => 'Daya_ingat_Jangka_segera',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field79' => array( 'field' => 'Konsentrasi_perhatian',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field80' => array( 'field' => 'Kemampuan_Membaca_Menulis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field81' => array( 'field' => 'Kemampuan_visuospasial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field82' => array( 'field' => 'Pikiran_abstrak',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field83' => array( 'field' => 'Inteligensia_dan_kemampuan_informasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field84' => array( 'field' => 'Kemampuan_mengendalikan_impuls',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field85' => array( 'field' => 'Daya_nilai_dan_tilikan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field86' => array( 'field' => 'Daya_nilai_sosial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field87' => array( 'field' => 'Uji_daya_nilai',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field88' => array( 'field' => 'Penilaian_Daya_Realita',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field89' => array( 'field' => 'Tilikan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field90' => array( 'field' => 'Taraf_dipercaya',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field91' => array( 'field' => 'Keadaan_Umum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field92' => array( 'field' => 'Kesadaran',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field93' => array( 'field' => 'Status_gizi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field94' => array( 'field' => 'Tekanan_Darah',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field95' => array( 'field' => 'Frekuensi_Nadi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field96' => array( 'field' => 'Frekuensi_Nafas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field97' => array( 'field' => 'Suhu',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field98' => array( 'field' => 'Mata_dan_THT',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field99' => array( 'field' => 'Mulut_dan_Gigi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field100' => array( 'field' => 'Thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field101' => array( 'field' => 'Abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field102' => array( 'field' => 'Extremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field103' => array( 'field' => 'Tanda_rangsang_Meningeal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field104' => array( 'field' => 'Motorik',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field105' => array( 'field' => 'Sensorik',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field106' => array( 'field' => 'Diagnosis_Axis',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field107' => array( 'field' => 'Organobiologi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field108' => array( 'field' => 'Psikologi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field109' => array( 'field' => 'Lingkungan_dan_sosial_ekonomi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field110' => array( 'field' => 'Quo_ad_Vitam',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field111' => array( 'field' => 'Quo_ad_Fungsionam',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field112' => array( 'field' => 'Quo_ad_Sanationam',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field113' => array( 'field' => 'Hal-hal_yang_mendukung',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field114' => array( 'field' => 'Hal-hal_yang_memberatkan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field115' => array( 'field' => 'Farmakologi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field116' => array( 'field' => 'Non_Farmakologi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field117' => array( 'field' => 'id_pasien',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field118' => array( 'field' => 'id_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true',
'users' => 'true' ) ),
'integrated_edit_field119' => array( 'field' => 'id_resep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field120' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>