<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_Jiwa' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Anamnesis' => array( 'totalsType' => '' ),
'Autoanamnesis' => array( 'totalsType' => '' ),
'Alloanamnesis' => array( 'totalsType' => '' ),
'Riwayat_gangguan_sekarang' => array( 'totalsType' => '' ),
'Riwayat_gangguan_dahulu' => array( 'totalsType' => '' ),
'Riwayat_gangguan_psikiatri' => array( 'totalsType' => '' ),
'Riwayat_gangguan_medis' => array( 'totalsType' => '' ),
'Riwayat_penggunaan_zat_psikoaktif' => array( 'totalsType' => '' ),
'Riwayat_prenatal_dan_perinatal' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_awal' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_pertengahan' => array( 'totalsType' => '' ),
'Riwayat_masa_kanak_akhir_dan_remaja' => array( 'totalsType' => '' ),
'Masa_Dewasa' => array( 'totalsType' => '' ),
'Riwayat_pendidikan' => array( 'totalsType' => '' ),
'Riwayat_pekerjaan' => array( 'totalsType' => '' ),
'Riwayat_pernikahan' => array( 'totalsType' => '' ),
'Riwayat_Agama' => array( 'totalsType' => '' ),
'Riwayat_Psikoseksual' => array( 'totalsType' => '' ),
'Riwayat_aktivitas_sosial' => array( 'totalsType' => '' ),
'Riwayat_hukum' => array( 'totalsType' => '' ),
'Riwayat_keluarga' => array( 'totalsType' => '' ),
'Genogram_keluarga' => array( 'totalsType' => '' ),
'Situasi_kehidupan_sekarang' => array( 'totalsType' => '' ),
'Persepsi_tentang_diri_dan_kehidupannya' => array( 'totalsType' => '' ),
'Persepsi_keluarga_tentang_diri_pasien' => array( 'totalsType' => '' ),
'Fantasi' => array( 'totalsType' => '' ),
'Penampilan' => array( 'totalsType' => '' ),
'Perilaku_dan_aktivitas_psikomotor' => array( 'totalsType' => '' ),
'Sikap_terhadap_pemeriksa' => array( 'totalsType' => '' ),
'Irama' => array( 'totalsType' => '' ),
'Kecepatan_bicara' => array( 'totalsType' => '' ),
'Volume' => array( 'totalsType' => '' ),
'Kelancaran' => array( 'totalsType' => '' ),
'Mood' => array( 'totalsType' => '' ),
'Afek' => array( 'totalsType' => '' ),
'Keserasian' => array( 'totalsType' => '' ),
'Auditorik' => array( 'totalsType' => '' ),
'Visual' => array( 'totalsType' => '' ),
'Taktil' => array( 'totalsType' => '' ),
'Olfaktorik' => array( 'totalsType' => '' ),
'Gustatorik' => array( 'totalsType' => '' ),
'Ilusi' => array( 'totalsType' => '' ),
'Depersonalisasi' => array( 'totalsType' => '' ),
'Derealisasi' => array( 'totalsType' => '' ),
'Blocking' => array( 'totalsType' => '' ),
'Assosiasi_Longgar' => array( 'totalsType' => '' ),
'Inkoheren' => array( 'totalsType' => '' ),
'Flight_of_Idea' => array( 'totalsType' => '' ),
'Sirkumstansia' => array( 'totalsType' => '' ),
'Tangensial' => array( 'totalsType' => '' ),
'Neologisme' => array( 'totalsType' => '' ),
'Word_Salad' => array( 'totalsType' => '' ),
'Hendaya_Berbahasa' => array( 'totalsType' => '' ),
'Produktivitas' => array( 'totalsType' => '' ),
'Preokupasi' => array( 'totalsType' => '' ),
'Waham_bizarre' => array( 'totalsType' => '' ),
'Waham_sistemik' => array( 'totalsType' => '' ),
'Waham_nihilistik' => array( 'totalsType' => '' ),
'Waham_paranoid' => array( 'totalsType' => '' ),
'Waham_kebesaran' => array( 'totalsType' => '' ),
'Waham_kejaran' => array( 'totalsType' => '' ),
'Waham_rujukan' => array( 'totalsType' => '' ),
'Waham_dikendalikan' => array( 'totalsType' => '' ),
'Thought_of_withdrawl' => array( 'totalsType' => '' ),
'Thought_of_insertion' => array( 'totalsType' => '' ),
'Thought_of_broadcasting' => array( 'totalsType' => '' ),
'Obsesi' => array( 'totalsType' => '' ),
'Kompulsif' => array( 'totalsType' => '' ),
'Fobia' => array( 'totalsType' => '' ),
'Gagasan_untuk_bunuh_diri' => array( 'totalsType' => '' ),
'Taraf_kesadaran_dan_kesiagaan' => array( 'totalsType' => '' ),
'Orieantasi_Waktu' => array( 'totalsType' => '' ),
'Orieantasi_Tempat' => array( 'totalsType' => '' ),
'Orieantasi_Orang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_panjang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_sedang' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_pendek' => array( 'totalsType' => '' ),
'Daya_ingat_Jangka_segera' => array( 'totalsType' => '' ),
'Konsentrasi_perhatian' => array( 'totalsType' => '' ),
'Kemampuan_Membaca_Menulis' => array( 'totalsType' => '' ),
'Kemampuan_visuospasial' => array( 'totalsType' => '' ),
'Pikiran_abstrak' => array( 'totalsType' => '' ),
'Inteligensia_dan_kemampuan_informasi' => array( 'totalsType' => '' ),
'Kemampuan_mengendalikan_impuls' => array( 'totalsType' => '' ),
'Daya_nilai_dan_tilikan' => array( 'totalsType' => '' ),
'Daya_nilai_sosial' => array( 'totalsType' => '' ),
'Uji_daya_nilai' => array( 'totalsType' => '' ),
'Penilaian_Daya_Realita' => array( 'totalsType' => '' ),
'Tilikan' => array( 'totalsType' => '' ),
'Taraf_dipercaya' => array( 'totalsType' => '' ),
'Keadaan_Umum' => array( 'totalsType' => '' ),
'Kesadaran' => array( 'totalsType' => '' ),
'Status_gizi' => array( 'totalsType' => '' ),
'Tekanan_Darah' => array( 'totalsType' => '' ),
'Frekuensi_Nadi' => array( 'totalsType' => '' ),
'Frekuensi_Nafas' => array( 'totalsType' => '' ),
'Suhu' => array( 'totalsType' => '' ),
'Mata_dan_THT' => array( 'totalsType' => '' ),
'Mulut_dan_Gigi' => array( 'totalsType' => '' ),
'Thorax' => array( 'totalsType' => '' ),
'Abdomen' => array( 'totalsType' => '' ),
'Extremitas' => array( 'totalsType' => '' ),
'Tanda_rangsang_Meningeal' => array( 'totalsType' => '' ),
'Motorik' => array( 'totalsType' => '' ),
'Sensorik' => array( 'totalsType' => '' ),
'Diagnosis_Axis' => array( 'totalsType' => '' ),
'Organobiologi' => array( 'totalsType' => '' ),
'Psikologi' => array( 'totalsType' => '' ),
'Lingkungan_dan_sosial_ekonomi' => array( 'totalsType' => '' ),
'Quo_ad_Vitam' => array( 'totalsType' => '' ),
'Quo_ad_Fungsionam' => array( 'totalsType' => '' ),
'Quo_ad_Sanationam' => array( 'totalsType' => '' ),
'Hal-hal_yang_mendukung' => array( 'totalsType' => '' ),
'Hal-hal_yang_memberatkan' => array( 'totalsType' => '' ),
'Farmakologi' => array( 'totalsType' => '' ),
'Non_Farmakologi' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'id_resep' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Kerja' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Abdomen',
'Tanggal_MRS',
'Kerja',
'Agama',
'Suku_Ras',
'Jenis Kelamin',
'Status_Perkawinan',
'Umur',
'Alamat',
'Nama',
'Id_Pasien1',
'email',
'username',
'name',
'id',
'Nomor_Rm',
'id_resep',
'id_user',
'id_pasien',
'Word_Salad',
'Waham_sistemik',
'Waham_rujukan',
'Waham_paranoid',
'Waham_nihilistik',
'Waham_kejaran',
'Waham_kebesaran',
'Waham_dikendalikan',
'Waham_bizarre',
'Volume',
'Visual',
'Uji_daya_nilai',
'Tilikan',
'Thought_of_withdrawl',
'Thought_of_insertion',
'Thought_of_broadcasting',
'Thorax',
'Tekanan_Darah',
'Taraf_kesadaran_dan_kesiagaan',
'Taraf_dipercaya',
'Tangensial',
'Tanda_rangsang_Meningeal',
'Taktil',
'Suhu',
'Status_gizi',
'Situasi_kehidupan_sekarang',
'Sirkumstansia',
'Sikap_terhadap_pemeriksa',
'Sensorik',
'Riwayat_prenatal_dan_perinatal',
'Riwayat_pernikahan',
'Riwayat_penggunaan_zat_psikoaktif',
'Riwayat_pendidikan',
'Riwayat_pekerjaan',
'Riwayat_masa_kanak_pertengahan',
'Riwayat_masa_kanak_awal',
'Riwayat_masa_kanak_akhir_dan_remaja',
'Riwayat_keluarga',
'Riwayat_hukum',
'Riwayat_gangguan_sekarang',
'Riwayat_gangguan_psikiatri',
'Riwayat_gangguan_medis',
'Riwayat_gangguan_dahulu',
'Riwayat_aktivitas_sosial',
'Riwayat_Psikoseksual',
'Riwayat_Agama',
'Quo_ad_Vitam',
'Quo_ad_Sanationam',
'Quo_ad_Fungsionam',
'Psikologi',
'Produktivitas',
'Preokupasi',
'Pikiran_abstrak',
'Persepsi_tentang_diri_dan_kehidupannya',
'Persepsi_keluarga_tentang_diri_pasien',
'Perilaku_dan_aktivitas_psikomotor',
'Penilaian_Daya_Realita',
'Penampilan',
'Orieantasi_Waktu',
'Orieantasi_Tempat',
'Orieantasi_Orang',
'Organobiologi',
'Olfaktorik',
'Obsesi',
'Non_Farmakologi',
'Neologisme',
'Mulut_dan_Gigi',
'Motorik',
'Mood',
'Mata_dan_THT',
'Masa_Dewasa',
'Lingkungan_dan_sosial_ekonomi',
'Konsentrasi_perhatian',
'Kompulsif',
'Keserasian',
'Kesadaran',
'Kemampuan_visuospasial',
'Kemampuan_mengendalikan_impuls',
'Kemampuan_Membaca_Menulis',
'Keluhan_Utama',
'Kelancaran',
'Kecepatan_bicara',
'Keadaan_Umum',
'Irama',
'Inteligensia_dan_kemampuan_informasi',
'Inkoheren',
'Ilusi',
'Hendaya_Berbahasa',
'Hal-hal_yang_mendukung',
'Hal-hal_yang_memberatkan',
'Gustatorik',
'Genogram_keluarga',
'Gagasan_untuk_bunuh_diri',
'Frekuensi_Nafas',
'Frekuensi_Nadi',
'Fobia',
'Flight_of_Idea',
'Farmakologi',
'Fantasi',
'Extremitas',
'Diagnosis_Axis',
'Derealisasi',
'Depersonalisasi',
'Daya_nilai_sosial',
'Daya_nilai_dan_tilikan',
'Daya_ingat_Jangka_segera',
'Daya_ingat_Jangka_sedang',
'Daya_ingat_Jangka_pendek',
'Daya_ingat_Jangka_panjang',
'Blocking',
'Autoanamnesis',
'Auditorik',
'Assosiasi_Longgar',
'Anamnesis',
'Alloanamnesis',
'Afek' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'simple_grid_field1',
'simple_grid_field' ),
'Nomor_Rm' => array( 'grid_field3',
'grid_field_label3' ),
'id' => array( 'grid_field',
'grid_field_label' ),
'name' => array( 'grid_field1',
'grid_field_label1' ),
'username' => array( 'grid_field2',
'grid_field_label2' ),
'email' => array( 'grid_field4',
'grid_field_label4' ),
'Id_Pasien1' => array( 'grid_field5',
'grid_field_label5' ),
'Nama' => array( 'grid_field6',
'grid_field_label6' ),
'Alamat' => array( 'grid_field7',
'grid_field_label7' ),
'Umur' => array( 'grid_field8',
'grid_field_label8' ),
'Status_Perkawinan' => array( 'grid_field9',
'grid_field_label9' ),
'Jenis Kelamin' => array( 'grid_field10',
'grid_field_label10' ),
'Suku_Ras' => array( 'grid_field11',
'grid_field_label11' ),
'Agama' => array( 'grid_field12',
'grid_field_label12' ),
'Kerja' => array( 'grid_field13',
'grid_field_label13' ),
'Tanggal_MRS' => array( 'grid_field14',
'grid_field_label14' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'grid_view',
'grid_checkbox_head',
'grid_checkbox',
'grid_field_label3',
'grid_field3',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13',
'grid_field_label14',
'grid_field14' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'grid_view' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label14' => 'grid',
'grid_field14' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field120' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field120' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label14' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field1',
'grid_field3',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field10',
'grid_field11',
'grid_field12',
'grid_field13',
'grid_field14' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'collapse_button' => array( 'collapse_button' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56',
'search_panel_field57',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60',
'search_panel_field61',
'search_panel_field62',
'search_panel_field63',
'search_panel_field64',
'search_panel_field65',
'search_panel_field66',
'search_panel_field67',
'search_panel_field68',
'search_panel_field69',
'search_panel_field70',
'search_panel_field71',
'search_panel_field72',
'search_panel_field73',
'search_panel_field74',
'search_panel_field75',
'search_panel_field76',
'search_panel_field77',
'search_panel_field78',
'search_panel_field79',
'search_panel_field80',
'search_panel_field81',
'search_panel_field82',
'search_panel_field83',
'search_panel_field84',
'search_panel_field85',
'search_panel_field86',
'search_panel_field87',
'search_panel_field88',
'search_panel_field89',
'search_panel_field90',
'search_panel_field91',
'search_panel_field92',
'search_panel_field93',
'search_panel_field94',
'search_panel_field95',
'search_panel_field96',
'search_panel_field97',
'search_panel_field98',
'search_panel_field99',
'search_panel_field100',
'search_panel_field101',
'search_panel_field102',
'search_panel_field103',
'search_panel_field104',
'search_panel_field105',
'search_panel_field106',
'search_panel_field107',
'search_panel_field108',
'search_panel_field109',
'search_panel_field110',
'search_panel_field111',
'search_panel_field112',
'search_panel_field113',
'search_panel_field114',
'search_panel_field115',
'search_panel_field116',
'search_panel_field117',
'search_panel_field118',
'search_panel_field119',
'search_panel_field120',
'search_panel_field121',
'search_panel_field122',
'search_panel_field123',
'search_panel_field124',
'search_panel_field125',
'search_panel_field126',
'search_panel_field127',
'search_panel_field128',
'search_panel_field129',
'search_panel_field130',
'search_panel_field131',
'search_panel_field132',
'search_panel_field133',
'search_panel_field134' ),
'logo' => array( 'logo1' ),
'grid_field_label' => array( 'simple_grid_field',
'grid_field_label3',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9',
'grid_field_label10',
'grid_field_label11',
'grid_field_label12',
'grid_field_label13',
'grid_field_label14' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'master_info' => array( 'master_info' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Utama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field120' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'name_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'username_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Id_Pasien1_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Nama_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Alamat_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Umur_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Status_Perkawinan_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Jenis_Kelamin_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Suku_Ras_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Agama_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'Kerja_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Tanggal_MRS_fieldheadercolumn' ),
'items' => array( 'grid_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'view_column' ),
'items' => array( 'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Utama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field120' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'name_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'username_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Id_Pasien1_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Nama_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Alamat_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Umur_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Status_Perkawinan_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Jenis_Kelamin_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Suku_Ras_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Agama_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'Kerja_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Tanggal_MRS_fieldcolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field120' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 18,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field120' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field120' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field120' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'view' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_view' ),
'columnName' => 'view' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'view' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_field120' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field120' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field120' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'name',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'name',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'username',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'username',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'Nama',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'Nama',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'Umur',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'Umur',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label10' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label11' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label12' ),
'field' => 'Agama',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'Agama',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label13' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label14' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field14' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'simple_grid_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'grid_view' => array( 'type' => 'grid_view' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field134',
'search_panel_field133',
'search_panel_field132',
'search_panel_field131',
'search_panel_field130',
'search_panel_field129',
'search_panel_field128',
'search_panel_field127',
'search_panel_field126',
'search_panel_field125',
'search_panel_field124',
'search_panel_field123',
'search_panel_field122',
'search_panel_field121',
'search_panel_field120',
'search_panel_field119',
'search_panel_field118',
'search_panel_field117',
'search_panel_field116',
'search_panel_field115',
'search_panel_field114',
'search_panel_field113',
'search_panel_field112',
'search_panel_field111',
'search_panel_field110',
'search_panel_field109',
'search_panel_field108',
'search_panel_field107',
'search_panel_field106',
'search_panel_field105',
'search_panel_field104',
'search_panel_field103',
'search_panel_field102',
'search_panel_field101',
'search_panel_field100',
'search_panel_field99',
'search_panel_field98',
'search_panel_field97',
'search_panel_field96',
'search_panel_field95',
'search_panel_field94',
'search_panel_field93',
'search_panel_field92',
'search_panel_field91',
'search_panel_field90',
'search_panel_field89',
'search_panel_field88',
'search_panel_field87',
'search_panel_field86',
'search_panel_field85',
'search_panel_field84',
'search_panel_field83',
'search_panel_field82',
'search_panel_field81',
'search_panel_field80',
'search_panel_field79',
'search_panel_field78',
'search_panel_field77',
'search_panel_field76',
'search_panel_field75',
'search_panel_field74',
'search_panel_field73',
'search_panel_field72',
'search_panel_field71',
'search_panel_field70',
'search_panel_field69',
'search_panel_field68',
'search_panel_field67',
'search_panel_field66',
'search_panel_field65',
'search_panel_field64',
'search_panel_field63',
'search_panel_field62',
'search_panel_field61',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field57',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Abdomen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'Afek',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'Alloanamnesis',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'Anamnesis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'Assosiasi_Longgar',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'Auditorik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'Autoanamnesis',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'Blocking',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'Daya_ingat_Jangka_panjang',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'Daya_ingat_Jangka_pendek',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'Daya_ingat_Jangka_sedang',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'Daya_ingat_Jangka_segera',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'Daya_nilai_dan_tilikan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'Daya_nilai_sosial',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'Depersonalisasi',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field15' => array( 'field' => 'Derealisasi',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field16' => array( 'field' => 'Diagnosis_Axis',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'Extremitas',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'Fantasi',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'Farmakologi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'Flight_of_Idea',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field21' => array( 'field' => 'Fobia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'Frekuensi_Nadi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'Frekuensi_Nafas',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'Gagasan_untuk_bunuh_diri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field25' => array( 'field' => 'Genogram_keluarga',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field26' => array( 'field' => 'Gustatorik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field27' => array( 'field' => 'Hal-hal_yang_memberatkan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'Hal-hal_yang_mendukung',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field29' => array( 'field' => 'Hendaya_Berbahasa',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field30' => array( 'field' => 'Ilusi',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field31' => array( 'field' => 'Inkoheren',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field32' => array( 'field' => 'Inteligensia_dan_kemampuan_informasi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'Irama',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field34' => array( 'field' => 'Keadaan_Umum',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field35' => array( 'field' => 'Kecepatan_bicara',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field36' => array( 'field' => 'Kelancaran',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field37' => array( 'field' => 'Keluhan_Utama',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field38' => array( 'field' => 'Kemampuan_Membaca_Menulis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'Kemampuan_mengendalikan_impuls',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'Kemampuan_visuospasial',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'Kesadaran',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'Keserasian',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field43' => array( 'field' => 'Kompulsif',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field44' => array( 'field' => 'Konsentrasi_perhatian',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'Lingkungan_dan_sosial_ekonomi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'Masa_Dewasa',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field47' => array( 'field' => 'Mata_dan_THT',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'Mood',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field49' => array( 'field' => 'Motorik',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'Mulut_dan_Gigi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field51' => array( 'field' => 'Neologisme',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field52' => array( 'field' => 'Non_Farmakologi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'Obsesi',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field54' => array( 'field' => 'Olfaktorik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field55' => array( 'field' => 'Organobiologi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'Orieantasi_Orang',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'Orieantasi_Tempat',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field58' => array( 'field' => 'Orieantasi_Waktu',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field59' => array( 'field' => 'Penampilan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'Penilaian_Daya_Realita',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'Perilaku_dan_aktivitas_psikomotor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field62' => array( 'field' => 'Persepsi_keluarga_tentang_diri_pasien',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field63' => array( 'field' => 'Persepsi_tentang_diri_dan_kehidupannya',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field64' => array( 'field' => 'Pikiran_abstrak',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field65' => array( 'field' => 'Preokupasi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field66' => array( 'field' => 'Produktivitas',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field67' => array( 'field' => 'Psikologi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field68' => array( 'field' => 'Quo_ad_Fungsionam',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field69' => array( 'field' => 'Quo_ad_Sanationam',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field70' => array( 'field' => 'Quo_ad_Vitam',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field71' => array( 'field' => 'Riwayat_Agama',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field72' => array( 'field' => 'Riwayat_Psikoseksual',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field73' => array( 'field' => 'Riwayat_aktivitas_sosial',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field74' => array( 'field' => 'Riwayat_gangguan_dahulu',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field75' => array( 'field' => 'Riwayat_gangguan_medis',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field76' => array( 'field' => 'Riwayat_gangguan_psikiatri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field77' => array( 'field' => 'Riwayat_gangguan_sekarang',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field78' => array( 'field' => 'Riwayat_hukum',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field79' => array( 'field' => 'Riwayat_keluarga',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field80' => array( 'field' => 'Riwayat_masa_kanak_akhir_dan_remaja',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field81' => array( 'field' => 'Riwayat_masa_kanak_awal',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field82' => array( 'field' => 'Riwayat_masa_kanak_pertengahan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field83' => array( 'field' => 'Riwayat_pekerjaan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field84' => array( 'field' => 'Riwayat_pendidikan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field85' => array( 'field' => 'Riwayat_penggunaan_zat_psikoaktif',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field86' => array( 'field' => 'Riwayat_pernikahan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field87' => array( 'field' => 'Riwayat_prenatal_dan_perinatal',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field88' => array( 'field' => 'Sensorik',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field89' => array( 'field' => 'Sikap_terhadap_pemeriksa',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field90' => array( 'field' => 'Sirkumstansia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field91' => array( 'field' => 'Situasi_kehidupan_sekarang',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field92' => array( 'field' => 'Status_gizi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field93' => array( 'field' => 'Suhu',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field94' => array( 'field' => 'Taktil',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field95' => array( 'field' => 'Tanda_rangsang_Meningeal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field96' => array( 'field' => 'Tangensial',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field97' => array( 'field' => 'Taraf_dipercaya',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field98' => array( 'field' => 'Taraf_kesadaran_dan_kesiagaan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field99' => array( 'field' => 'Tekanan_Darah',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field100' => array( 'field' => 'Thorax',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field101' => array( 'field' => 'Thought_of_broadcasting',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field102' => array( 'field' => 'Thought_of_insertion',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field103' => array( 'field' => 'Thought_of_withdrawl',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field104' => array( 'field' => 'Tilikan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field105' => array( 'field' => 'Uji_daya_nilai',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field106' => array( 'field' => 'Visual',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field107' => array( 'field' => 'Volume',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field108' => array( 'field' => 'Waham_bizarre',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field109' => array( 'field' => 'Waham_dikendalikan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field110' => array( 'field' => 'Waham_kebesaran',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field111' => array( 'field' => 'Waham_kejaran',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field112' => array( 'field' => 'Waham_nihilistik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field113' => array( 'field' => 'Waham_paranoid',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field114' => array( 'field' => 'Waham_rujukan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field115' => array( 'field' => 'Waham_sistemik',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field116' => array( 'field' => 'Word_Salad',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'logo1' => array( 'type' => 'logo' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Utama' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'search_panel_field117' => array( 'field' => 'id_pasien',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field118' => array( 'field' => 'id_user',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true',
'users' => 'true' ) ),
'search_panel_field119' => array( 'field' => 'id_resep',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field3' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'search_panel_field120' => array( 'field' => 'Nomor_Rm',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field121' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'grid_field1' => array( 'field' => 'name',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'name' ),
'search_panel_field122' => array( 'field' => 'name',
'type' => 'search_panel_field',
'required' => false ),
'grid_field2' => array( 'field' => 'username',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'username' ),
'search_panel_field123' => array( 'field' => 'username',
'type' => 'search_panel_field',
'required' => false ),
'grid_field4' => array( 'field' => 'email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'search_panel_field124' => array( 'field' => 'email',
'type' => 'search_panel_field',
'required' => false ),
'grid_field5' => array( 'field' => 'Id_Pasien1',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'Id_Pasien1' ),
'search_panel_field125' => array( 'field' => 'Id_Pasien1',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field6' => array( 'field' => 'Nama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'Nama' ),
'search_panel_field126' => array( 'field' => 'Nama',
'type' => 'search_panel_field',
'required' => false ),
'grid_field7' => array( 'field' => 'Alamat',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Alamat' ),
'search_panel_field127' => array( 'field' => 'Alamat',
'type' => 'search_panel_field',
'required' => false ),
'grid_field8' => array( 'field' => 'Umur',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'Umur' ),
'search_panel_field128' => array( 'field' => 'Umur',
'type' => 'search_panel_field',
'required' => false ),
'grid_field9' => array( 'field' => 'Status_Perkawinan',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Status_Perkawinan' ),
'search_panel_field129' => array( 'field' => 'Status_Perkawinan',
'type' => 'search_panel_field',
'required' => false ),
'grid_field10' => array( 'field' => 'Jenis Kelamin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'Jenis Kelamin' ),
'search_panel_field130' => array( 'field' => 'Jenis Kelamin',
'type' => 'search_panel_field',
'required' => false ),
'grid_field11' => array( 'field' => 'Suku_Ras',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'Suku_Ras' ),
'search_panel_field131' => array( 'field' => 'Suku_Ras',
'type' => 'search_panel_field',
'required' => false ),
'grid_field12' => array( 'field' => 'Agama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'Agama' ),
'search_panel_field132' => array( 'field' => 'Agama',
'type' => 'search_panel_field',
'required' => false ),
'grid_field13' => array( 'field' => 'Kerja',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'Kerja' ),
'search_panel_field133' => array( 'field' => 'Kerja',
'type' => 'search_panel_field',
'required' => false ),
'grid_field14' => array( 'field' => 'Tanggal_MRS',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label14' => array( 'type' => 'grid_field_label',
'field' => 'Tanggal_MRS' ),
'search_panel_field134' => array( 'field' => 'Tanggal_MRS',
'type' => 'search_panel_field',
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>