<?php
			$optionsArray = array( 'master' => array( 'users' => array( 'preview' => true ),
'identitas_pasien' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'edukasi',
'monitoring',
'terapi_nonmedikamentosa',
'terapi_medikamentosa',
'diagnosis_planning',
'diagnosis_banding',
'resume',
'diagnosis',
'nadi',
'pmrksaan_lab_pnunjang',
'tensi',
'keadaan_umum',
'kesadaran_gcs',
'ekstremitas',
'abdomen',
'thorax',
'leher',
'kepala',
'tb',
'bb',
'status_gizi',
'rr_x_menit',
'status_dermatologis',
'temp',
'rwyt_kebiasaan',
'rwyt_pengobatan',
'rwyt_dulu',
'rwyt_skrg',
'keluhan_tmbhan',
'keluhan_pertama',
'rwyt_alergi',
'rwyt_klg',
'prognosis',
'id_mhs',
'id_pasien',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'edukasi' => array( 'integrated_edit_field26' ),
'monitoring' => array( 'integrated_edit_field25' ),
'terapi_nonmedikamentosa' => array( 'integrated_edit_field24' ),
'terapi_medikamentosa' => array( 'integrated_edit_field23' ),
'diagnosis_planning' => array( 'integrated_edit_field22' ),
'diagnosis_banding' => array( 'integrated_edit_field21' ),
'resume' => array( 'integrated_edit_field20' ),
'diagnosis' => array( 'integrated_edit_field19' ),
'nadi' => array( 'integrated_edit_field18' ),
'pmrksaan_lab_pnunjang' => array( 'integrated_edit_field17' ),
'tensi' => array( 'integrated_edit_field13' ),
'keadaan_umum' => array( 'integrated_edit_field' ),
'kesadaran_gcs' => array( 'integrated_edit_field9' ),
'ekstremitas' => array( 'integrated_edit_field32' ),
'abdomen' => array( 'integrated_edit_field31' ),
'thorax' => array( 'integrated_edit_field30' ),
'leher' => array( 'integrated_edit_field29' ),
'kepala' => array( 'integrated_edit_field28' ),
'tb' => array( 'integrated_edit_field10' ),
'bb' => array( 'integrated_edit_field11' ),
'status_gizi' => array( 'integrated_edit_field12' ),
'rr_x_menit' => array( 'integrated_edit_field14' ),
'status_dermatologis' => array( 'integrated_edit_field15' ),
'temp' => array( 'integrated_edit_field16' ),
'rwyt_kebiasaan' => array( 'integrated_edit_field8' ),
'rwyt_pengobatan' => array( 'integrated_edit_field7' ),
'rwyt_dulu' => array( 'integrated_edit_field4' ),
'rwyt_skrg' => array( 'integrated_edit_field3' ),
'keluhan_tmbhan' => array( 'integrated_edit_field2' ),
'keluhan_pertama' => array( 'integrated_edit_field1' ),
'rwyt_alergi' => array( 'integrated_edit_field6' ),
'rwyt_klg' => array( 'integrated_edit_field5' ),
'prognosis' => array( 'integrated_edit_field27' ),
'id_mhs' => array( 'integrated_edit_field44' ),
'id_pasien' => array( 'integrated_edit_field45' ),
'Nomor_Rm' => array( 'integrated_edit_field33' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'integrated_edit_field44',
'integrated_edit_field33',
'master_info',
'tabs',
'integrated_edit_field45' ),
'section1' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'section2' => array( 'section',
'section1',
'section2',
'section3' ),
'section3' => array( 'integrated_edit_field20' ),
'section5' => array( 'integrated_edit_field19',
'integrated_edit_field21' ),
'section' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26' ),
'section4' => array( 'integrated_edit_field27' ),
'section6' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'section7' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'section8' => array( 'integrated_edit_field15' ),
'section9' => array( 'integrated_edit_field17' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field33' => 'grid',
'master_info' => 'grid',
'tabs' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field1' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field8' => 'section1',
'section' => 'section2',
'section1' => 'section2',
'section2' => 'section2',
'section3' => 'section2',
'integrated_edit_field20' => 'section3',
'integrated_edit_field19' => 'section5',
'integrated_edit_field21' => 'section5',
'integrated_edit_field22' => 'section',
'integrated_edit_field23' => 'section',
'integrated_edit_field24' => 'section',
'integrated_edit_field25' => 'section',
'integrated_edit_field26' => 'section',
'integrated_edit_field27' => 'section4',
'integrated_edit_field' => 'section6',
'integrated_edit_field9' => 'section6',
'integrated_edit_field10' => 'section6',
'integrated_edit_field11' => 'section6',
'integrated_edit_field13' => 'section6',
'integrated_edit_field12' => 'section6',
'integrated_edit_field18' => 'section6',
'integrated_edit_field14' => 'section6',
'integrated_edit_field16' => 'section6',
'integrated_edit_field28' => 'section7',
'integrated_edit_field29' => 'section7',
'integrated_edit_field30' => 'section7',
'integrated_edit_field31' => 'section7',
'integrated_edit_field32' => 'section7',
'integrated_edit_field15' => 'section8',
'integrated_edit_field17' => 'section9' ),
'itemLocations' => array( 'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'master_info' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c2' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c' ),
'section' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section2' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section9',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field13',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field28',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field1',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field27',
'integrated_edit_field33' ),
'section' => array( 'section2',
'section1',
'section',
'section3' ),
'tabs' => array( 'tabs' ),
'edit_field' => array( 'integrated_edit_field44',
'integrated_edit_field45' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'master_info',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1',
'section2',
'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 2,
'rowspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field44' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c3',
'items' => array( 'master_info',
'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field45' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section1',
'section2',
'section3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1,
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'kulit',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list',
'label' => array( 'type' => 0,
'text' => 'Kembali ke menu' ) ),
'add_cancel' => array( 'type' => 'add_cancel',
'buttonStyle' => 'danger',
'label' => array( 'type' => 0,
'text' => 'Batal' ) ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'label' => array( 'type' => 0,
'text' => 'Simpan' ) ),
'integrated_edit_field26' => array( 'field' => 'edukasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'monitoring',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'terapi_nonmedikamentosa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'terapi_medikamentosa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'diagnosis_planning',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'diagnosis_banding',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'resume',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'diagnosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'nadi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'pmrksaan_lab_pnunjang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'tensi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Status Dermatologis',
'type' => 0 ),
'location' => 'section8' ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Fisik',
'type' => 0 ),
'location' => 'section7' ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Umum',
'type' => 0 ),
'location' => 'section6' ),
'integrated_edit_field' => array( 'field' => 'keadaan_umum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'kesadaran_gcs',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'kepala',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'tb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tb',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'bb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'bb',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'status_gizi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'rr_x_menit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'status_dermatologis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'temp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kebiasaan',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_pengobatan',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_dulu',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_skrg',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_tmbhan',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_pertama',
'table' => 'interna',
'type' => 3 ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'SUBYEKTIF (ANAMNESA)',
'type' => 0 ),
array( 'text' => 'OBYEKTIF (PEMERIKSAAN)',
'type' => 0 ),
array( 'text' => 'RESUME',
'type' => 0 ),
array( 'text' => 'ASSESSMENT',
'type' => 0 ),
array( 'text' => 'PLANNING',
'type' => 0 ),
array( 'text' => 'PROGNOSIS',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section3',
'section5',
'section',
'section4' ) ),
'integrated_edit_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_alergi',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_klg',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field27' => array( 'field' => 'prognosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Laboratorium dan Penunjang Yang Lain',
'type' => 0 ),
'location' => 'section9' ),
'integrated_edit_field44' => array( 'field' => 'id_mhs',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field45' => array( 'field' => 'id_pasien',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'users' => 'true',
'identitas_pasien' => 'true' ) ),
'integrated_edit_field33' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4,
'pageWidth' => 'full' );
		?>