<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'rwyt_kebiasaan',
'prognosis',
'edukasi',
'monitoring',
'keluhan_pertama',
'keadaan_umum',
'keluhan_tmbhan',
'rwyt_skrg',
'terapi_nonmedikamentosa',
'terapi_medikamentosa',
'diagnosis_planning',
'diagnosis_banding',
'rwyt_klg',
'diagnosis',
'resume',
'pmrksaan_lab_pnunjang',
'status_dermatologis',
'ekstremitas',
'abdomen',
'rwyt_dulu',
'thorax',
'leher',
'kepala',
'temp',
'rr_x_menit',
'rwyt_alergi',
'nadi',
'status_gizi',
'tensi',
'bb',
'rwyt_pengobatan',
'tb',
'kesadaran_gcs',
'Jenis Kelamin',
'Tanggal_MRS',
'Umur',
'email',
'Nama',
'Agama',
'Kerja',
'username',
'Suku_Ras',
'Status_Perkawinan',
'Nomor_Rm',
'Alamat',
'name',
'id_mhs' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'rwyt_kebiasaan' => array( 'integrated_edit_field8' ),
'prognosis' => array( 'integrated_edit_field27' ),
'edukasi' => array( 'integrated_edit_field26' ),
'monitoring' => array( 'integrated_edit_field25' ),
'keluhan_pertama' => array( 'integrated_edit_field1' ),
'keadaan_umum' => array( 'integrated_edit_field' ),
'keluhan_tmbhan' => array( 'integrated_edit_field2' ),
'rwyt_skrg' => array( 'integrated_edit_field3' ),
'terapi_nonmedikamentosa' => array( 'integrated_edit_field24' ),
'terapi_medikamentosa' => array( 'integrated_edit_field23' ),
'diagnosis_planning' => array( 'integrated_edit_field22' ),
'diagnosis_banding' => array( 'integrated_edit_field21' ),
'rwyt_klg' => array( 'integrated_edit_field5' ),
'diagnosis' => array( 'integrated_edit_field19' ),
'resume' => array( 'integrated_edit_field20' ),
'pmrksaan_lab_pnunjang' => array( 'integrated_edit_field17' ),
'status_dermatologis' => array( 'integrated_edit_field15' ),
'ekstremitas' => array( 'integrated_edit_field32' ),
'abdomen' => array( 'integrated_edit_field31' ),
'rwyt_dulu' => array( 'integrated_edit_field4' ),
'thorax' => array( 'integrated_edit_field30' ),
'leher' => array( 'integrated_edit_field29' ),
'kepala' => array( 'integrated_edit_field28' ),
'temp' => array( 'integrated_edit_field16' ),
'rr_x_menit' => array( 'integrated_edit_field14' ),
'rwyt_alergi' => array( 'integrated_edit_field6' ),
'nadi' => array( 'integrated_edit_field18' ),
'status_gizi' => array( 'integrated_edit_field12' ),
'tensi' => array( 'integrated_edit_field13' ),
'bb' => array( 'integrated_edit_field11' ),
'rwyt_pengobatan' => array( 'integrated_edit_field7' ),
'tb' => array( 'integrated_edit_field10' ),
'kesadaran_gcs' => array( 'integrated_edit_field9' ),
'Jenis Kelamin' => array( 'integrated_edit_field46' ),
'Tanggal_MRS' => array( 'integrated_edit_field50' ),
'Umur' => array( 'integrated_edit_field42' ),
'email' => array( 'integrated_edit_field38' ),
'Nama' => array( 'integrated_edit_field40' ),
'Agama' => array( 'integrated_edit_field48' ),
'Kerja' => array( 'integrated_edit_field49' ),
'username' => array( 'integrated_edit_field37' ),
'Suku_Ras' => array( 'integrated_edit_field47' ),
'Status_Perkawinan' => array( 'integrated_edit_field43' ),
'Nomor_Rm' => array( 'integrated_edit_field33' ),
'Alamat' => array( 'integrated_edit_field41' ),
'name' => array( 'integrated_edit_field36' ),
'id_mhs' => array( 'integrated_edit_field44' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'integrated_edit_field44',
'master_info',
'section4',
'section5',
'tabs' ),
'section1' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'section2' => array( 'section',
'section1',
'section2',
'section3' ),
'section6' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'section7' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'section8' => array( 'integrated_edit_field15' ),
'section9' => array( 'integrated_edit_field17' ),
'section3' => array( 'integrated_edit_field20' ),
'section5' => array( 'integrated_edit_field19',
'integrated_edit_field21' ),
'section' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26' ),
'section4' => array( 'integrated_edit_field27' ),
'section10' => array( 'integrated_edit_field37',
'integrated_edit_field36',
'integrated_edit_field33',
'integrated_edit_field38' ),
'section11' => array( 'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field43',
'integrated_edit_field47',
'integrated_edit_field49',
'integrated_edit_field42',
'integrated_edit_field46',
'integrated_edit_field48',
'integrated_edit_field50' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field44' => 'grid',
'master_info' => 'grid',
'section4' => 'grid',
'section5' => 'grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field8' => 'section1',
'section' => 'section2',
'section1' => 'section2',
'section2' => 'section2',
'section3' => 'section2',
'integrated_edit_field' => 'section6',
'integrated_edit_field9' => 'section6',
'integrated_edit_field10' => 'section6',
'integrated_edit_field11' => 'section6',
'integrated_edit_field13' => 'section6',
'integrated_edit_field12' => 'section6',
'integrated_edit_field18' => 'section6',
'integrated_edit_field14' => 'section6',
'integrated_edit_field16' => 'section6',
'integrated_edit_field28' => 'section7',
'integrated_edit_field29' => 'section7',
'integrated_edit_field30' => 'section7',
'integrated_edit_field31' => 'section7',
'integrated_edit_field32' => 'section7',
'integrated_edit_field15' => 'section8',
'integrated_edit_field17' => 'section9',
'integrated_edit_field20' => 'section3',
'integrated_edit_field19' => 'section5',
'integrated_edit_field21' => 'section5',
'integrated_edit_field22' => 'section',
'integrated_edit_field23' => 'section',
'integrated_edit_field24' => 'section',
'integrated_edit_field25' => 'section',
'integrated_edit_field26' => 'section',
'integrated_edit_field27' => 'section4',
'integrated_edit_field37' => 'section10',
'integrated_edit_field36' => 'section10',
'integrated_edit_field33' => 'section10',
'integrated_edit_field38' => 'section10',
'integrated_edit_field40' => 'section11',
'integrated_edit_field41' => 'section11',
'integrated_edit_field43' => 'section11',
'integrated_edit_field47' => 'section11',
'integrated_edit_field49' => 'section11',
'integrated_edit_field42' => 'section11',
'integrated_edit_field46' => 'section11',
'integrated_edit_field48' => 'section11',
'integrated_edit_field50' => 'section11' ),
'itemLocations' => array( 'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c' ),
'master_info' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section5' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c' ),
'section' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section2' => array( 'location' => 'section2',
'cellId' => 'c' ),
'section3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section9',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field37' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field36' => array( 'location' => 'section10',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section10',
'cellId' => 'c' ),
'integrated_edit_field38' => array( 'location' => 'section10',
'cellId' => 'c' ),
'integrated_edit_field40' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field41' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field43' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field47' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field49' => array( 'location' => 'section11',
'cellId' => 'c1' ),
'integrated_edit_field42' => array( 'location' => 'section11',
'cellId' => 'c' ),
'integrated_edit_field46' => array( 'location' => 'section11',
'cellId' => 'c' ),
'integrated_edit_field48' => array( 'location' => 'section11',
'cellId' => 'c' ),
'integrated_edit_field50' => array( 'location' => 'section11',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'integrated_edit_field' => array( 'integrated_edit_field8',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field1',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field5',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field17',
'integrated_edit_field15',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field4',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field28',
'integrated_edit_field16',
'integrated_edit_field14',
'integrated_edit_field6',
'integrated_edit_field18',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field11',
'integrated_edit_field7',
'integrated_edit_field10',
'integrated_edit_field9',
'integrated_edit_field46',
'integrated_edit_field50',
'integrated_edit_field42',
'integrated_edit_field38',
'integrated_edit_field40',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field37',
'integrated_edit_field47',
'integrated_edit_field43',
'integrated_edit_field33',
'integrated_edit_field41',
'integrated_edit_field36' ),
'section' => array( 'section5',
'section4',
'section',
'section3',
'section2',
'section1' ),
'tabs' => array( 'tabs' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ),
'master_info' => array( 'master_info' ),
'edit_field' => array( 'integrated_edit_field44' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'master_info',
'section4',
'section5',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1',
'section2',
'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section9' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section10' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37',
'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33',
'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section11' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field43',
'integrated_edit_field47',
'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42',
'integrated_edit_field46',
'integrated_edit_field48',
'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1,
'rowspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1,
'rowspan' => 1 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field44' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c3',
'items' => array( 'master_info',
'section4',
'section5',
'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section1',
'section2',
'section3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field18',
'integrated_edit_field14',
'integrated_edit_field16' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section9' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'rowspan' => 1,
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25',
'integrated_edit_field26' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section10' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37',
'integrated_edit_field36' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33',
'integrated_edit_field38' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section11' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field43',
'integrated_edit_field47',
'integrated_edit_field49' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42',
'integrated_edit_field46',
'integrated_edit_field48',
'integrated_edit_field50' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'kulit',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list',
'label' => array( 'type' => 0,
'text' => 'Kembali ke menu' ) ),
'view_close' => array( 'type' => 'view_close',
'label' => array( 'type' => 0,
'text' => 'Tutup' ),
'buttonStyle' => 'warning' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array(  ) ),
'integrated_edit_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kebiasaan',
'table' => 'kulit',
'type' => 3 ) ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'Identitas Pasien',
'type' => 0 ),
'location' => 'section11' ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Informasi DM',
'type' => 0 ),
'location' => 'section10' ),
'integrated_edit_field27' => array( 'field' => 'prognosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'edukasi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'monitoring',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'SUBYEKTIF (ANAMNESA)',
'type' => 0 ),
array( 'text' => 'OBYEKTIF (PEMERIKSAAN)',
'type' => 0 ),
array( 'text' => 'RESUME',
'type' => 0 ),
array( 'text' => 'ASSESSMENT',
'type' => 0 ),
array( 'text' => 'PLANNING',
'type' => 0 ),
array( 'text' => 'PROGNOSIS',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section3',
'section5',
'section',
'section4' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Umum',
'type' => 0 ),
'location' => 'section6' ),
'integrated_edit_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_pertama',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field' => array( 'field' => 'keadaan_umum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_tmbhan',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_skrg',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field24' => array( 'field' => 'terapi_nonmedikamentosa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'terapi_medikamentosa',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'diagnosis_planning',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'diagnosis_banding',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_klg',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'diagnosis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'resume',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'pmrksaan_lab_pnunjang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Laboratorium dan Penunjang Yang Lain',
'type' => 0 ),
'location' => 'section9' ),
'integrated_edit_field15' => array( 'field' => 'status_dermatologis',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Status Dermatologis',
'type' => 0 ),
'location' => 'section8' ),
'integrated_edit_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_dulu',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field30' => array( 'field' => 'thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'kepala',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Fisik',
'type' => 0 ),
'location' => 'section7' ),
'integrated_edit_field16' => array( 'field' => 'temp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'rr_x_menit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_alergi',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field18' => array( 'field' => 'nadi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'status_gizi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'tensi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'bb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'bb',
'table' => 'kulit',
'type' => 3 ) ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'users' => 'true',
'identitas_pasien' => 'true' ) ),
'integrated_edit_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_pengobatan',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'tb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tb',
'table' => 'kulit',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'kesadaran_gcs',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'Umur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'Nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'Agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'Kerja',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'Alamat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'id_mhs',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>