<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'keadaan_umum',
'kesadaran_gcs',
'status_gizi',
'tensi',
'rr_x_menit',
'status_dermatologis',
'pmrksaan_lab_pnunjang',
'resume',
'diagnosis_banding',
'diagnosis_planning',
'terapi_medikamentosa',
'terapi_nonmedikamentosa',
'tb',
'bb',
'monitoring',
'edukasi',
'nadi',
'prognosis',
'temp',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'diagnosis',
'id_kulit',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'import_field1' ),
'keluhan_tmbhan' => array( 'import_field2' ),
'rwyt_skrg' => array( 'import_field3' ),
'rwyt_dulu' => array( 'import_field4' ),
'rwyt_klg' => array( 'import_field5' ),
'rwyt_alergi' => array( 'import_field6' ),
'rwyt_pengobatan' => array( 'import_field7' ),
'rwyt_kebiasaan' => array( 'import_field8' ),
'keadaan_umum' => array( 'import_field9' ),
'kesadaran_gcs' => array( 'import_field10' ),
'status_gizi' => array( 'import_field11' ),
'tensi' => array( 'import_field12' ),
'rr_x_menit' => array( 'import_field13' ),
'status_dermatologis' => array( 'import_field14' ),
'pmrksaan_lab_pnunjang' => array( 'import_field15' ),
'resume' => array( 'import_field16' ),
'diagnosis_banding' => array( 'import_field17' ),
'diagnosis_planning' => array( 'import_field18' ),
'terapi_medikamentosa' => array( 'import_field19' ),
'terapi_nonmedikamentosa' => array( 'import_field20' ),
'tb' => array( 'import_field21' ),
'bb' => array( 'import_field22' ),
'monitoring' => array( 'import_field23' ),
'edukasi' => array( 'import_field24' ),
'nadi' => array( 'import_field25' ),
'prognosis' => array( 'import_field26' ),
'temp' => array( 'import_field27' ),
'kepala' => array( 'import_field28' ),
'leher' => array( 'import_field29' ),
'thorax' => array( 'import_field30' ),
'abdomen' => array( 'import_field31' ),
'ekstremitas' => array( 'import_field32' ),
'diagnosis' => array( 'import_field42' ),
'id_kulit' => array( 'import_field' ),
'id_mhs' => array( 'import_field45' ),
'id_pasien' => array( 'import_field46' ),
'Nomor_Rm' => array( 'import_field33' ),
'id' => array( 'import_field34' ),
'name' => array( 'import_field35' ),
'username' => array( 'import_field36' ),
'email' => array( 'import_field37' ),
'Id_Pasien1' => array( 'import_field38' ),
'Nama' => array( 'import_field39' ),
'Alamat' => array( 'import_field40' ),
'Umur' => array( 'import_field41' ),
'Status_Perkawinan' => array( 'import_field43' ),
'Jenis Kelamin' => array( 'import_field44' ),
'Suku_Ras' => array( 'import_field47' ),
'Agama' => array( 'import_field48' ),
'Kerja' => array( 'import_field49' ),
'Tanggal_MRS' => array( 'import_field50' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field21',
'import_field22',
'import_field25',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field42',
'import_field',
'import_field45',
'import_field46',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field23',
'import_field24',
'import_field26',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field43',
'import_field44',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field25' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field42' => 'grid',
'import_field' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field26' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field42',
'import_field',
'import_field45',
'import_field46',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field43',
'import_field44',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field21',
'import_field22',
'import_field25',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field42',
'import_field',
'import_field45',
'import_field46',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field23',
'import_field24',
'import_field26',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field43',
'import_field44',
'import_field47',
'import_field48',
'import_field49',
'import_field50' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'rwyt_klg',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'keadaan_umum',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'kesadaran_gcs',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'status_gizi',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'tensi',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'rr_x_menit',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'status_dermatologis',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'pmrksaan_lab_pnunjang',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'resume',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'diagnosis_banding',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'diagnosis_planning',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'terapi_medikamentosa',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'terapi_nonmedikamentosa',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'tb',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'bb',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'monitoring',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'edukasi',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'nadi',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'prognosis',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'temp',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'kepala',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'leher',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'thorax',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'abdomen',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'ekstremitas',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'diagnosis',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'id_kulit',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'id_mhs',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Nomor_Rm',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'name',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'username',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'Id_Pasien1',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'Nama',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'Alamat',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'Umur',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'Status_Perkawinan',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'Jenis Kelamin',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'Suku_Ras',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'Agama',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'Kerja',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'Tanggal_MRS',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>