<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Nama',
'Keluhan_Utama',
'Keluhan_Tambahan',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Alergi',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Sosio_Ekonomi',
'Visus_OD_Kiri',
'Visus_OS_Kanan',
'Refraksi_OD_Kiri',
'Refraksi_OS_Kanan',
'Addisi_OD_Kiri',
'Addisi_OS_Kanan',
'Posisi_Bola_Mata_Kiri',
'Posisi_Bola_Mata_Kanan',
'Gerakan_Bola_Mata_Kiri',
'Gerakan_Bola_Mata_Kanan',
'Palpebra_Kiri',
'Palpebra_Kanan',
'Conjunctiva_Kiri',
'Conjunctiva_Kanan',
'Cornea_Kiri',
'Cornea_Kanan',
'COA_Kiri',
'COA_Kanan',
'Pupil_Kiri',
'Pupil_Kanan',
'Iris_Kiri',
'Iris_Kanan',
'Lensa_Kiri',
'Lensa_Kanan',
'Tekanan_Intra_Okuler_Kiri',
'Tekanan_Intra_Okuler_Kanan',
'Segment_Posterior_Kiri',
'Segment_Posterior_Kanan',
'Lapang_Pandang_Kiri',
'Lapang_Pandang_Kanan',
'Ishihara_Test_Kiri',
'Ishihara_Test_Kanan',
'Fluorescein_Tes_Kiri',
'Fluorescein_Test_Kanan',
'Sensibilitas_Kornea_Kiri',
'Sensibilitas_Kornea_Kanan',
'Schirmer_Test_Kiri',
'Schirmer_Test_Kanan',
'Hirschberg_Test_Kiri',
'Hirschberg_Test_Kanan',
'Cover_Test_Kiri',
'Cover_Test_Kanan',
'Cover_Uncover_Test_Kiri',
'Cover_Uncover_Test_Kanan',
'Penunjang_Lain',
'Daftar_Masalah',
'Rencana_Permulaan',
'Catatan_Kemajuan',
'Diagnosa_Diagnosa_Banding',
'Terapi',
'Prognosis',
'Komplikasi',
'Id_User',
'Id_Pasien',
'Nomor_Rm',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Pekerjaan',
'Tanggal_MRS',
'name',
'Id_Mata',
'id_pasien1',
'id',
'username',
'email',
'email_verified_at',
'password',
'two_factor_secret',
'two_factor_recovery_codes',
'level',
'remember_token',
'profile_photo_path',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Nama' => array( 'integrated_search_field' ),
'Keluhan_Utama' => array( 'integrated_search_field1' ),
'Keluhan_Tambahan' => array( 'integrated_search_field2' ),
'Riwayat_Penyakit_Sekarang' => array( 'integrated_search_field3' ),
'Riwayat_Penyakit_Dahulu' => array( 'integrated_search_field4' ),
'Riwayat_Penyakit_Keluarga' => array( 'integrated_search_field5' ),
'Riwayat_Alergi' => array( 'integrated_search_field6' ),
'Riwayat_Pengobatan' => array( 'integrated_search_field7' ),
'Riwayat_Kebiasaan' => array( 'integrated_search_field8' ),
'Riwayat_Sosio_Ekonomi' => array( 'integrated_search_field9' ),
'Visus_OD_Kiri' => array( 'integrated_search_field10' ),
'Visus_OS_Kanan' => array( 'integrated_search_field11' ),
'Refraksi_OD_Kiri' => array( 'integrated_search_field12' ),
'Refraksi_OS_Kanan' => array( 'integrated_search_field13' ),
'Addisi_OD_Kiri' => array( 'integrated_search_field14' ),
'Addisi_OS_Kanan' => array( 'integrated_search_field15' ),
'Posisi_Bola_Mata_Kiri' => array( 'integrated_search_field16' ),
'Posisi_Bola_Mata_Kanan' => array( 'integrated_search_field17' ),
'Gerakan_Bola_Mata_Kiri' => array( 'integrated_search_field18' ),
'Gerakan_Bola_Mata_Kanan' => array( 'integrated_search_field19' ),
'Palpebra_Kiri' => array( 'integrated_search_field20' ),
'Palpebra_Kanan' => array( 'integrated_search_field21' ),
'Conjunctiva_Kiri' => array( 'integrated_search_field22' ),
'Conjunctiva_Kanan' => array( 'integrated_search_field23' ),
'Cornea_Kiri' => array( 'integrated_search_field24' ),
'Cornea_Kanan' => array( 'integrated_search_field25' ),
'COA_Kiri' => array( 'integrated_search_field26' ),
'COA_Kanan' => array( 'integrated_search_field27' ),
'Pupil_Kiri' => array( 'integrated_search_field28' ),
'Pupil_Kanan' => array( 'integrated_search_field29' ),
'Iris_Kiri' => array( 'integrated_search_field30' ),
'Iris_Kanan' => array( 'integrated_search_field31' ),
'Lensa_Kiri' => array( 'integrated_search_field32' ),
'Lensa_Kanan' => array( 'integrated_search_field33' ),
'Tekanan_Intra_Okuler_Kiri' => array( 'integrated_search_field34' ),
'Tekanan_Intra_Okuler_Kanan' => array( 'integrated_search_field35' ),
'Segment_Posterior_Kiri' => array( 'integrated_search_field36' ),
'Segment_Posterior_Kanan' => array( 'integrated_search_field37' ),
'Lapang_Pandang_Kiri' => array( 'integrated_search_field38' ),
'Lapang_Pandang_Kanan' => array( 'integrated_search_field39' ),
'Ishihara_Test_Kiri' => array( 'integrated_search_field40' ),
'Ishihara_Test_Kanan' => array( 'integrated_search_field41' ),
'Fluorescein_Tes_Kiri' => array( 'integrated_search_field42' ),
'Fluorescein_Test_Kanan' => array( 'integrated_search_field43' ),
'Sensibilitas_Kornea_Kiri' => array( 'integrated_search_field44' ),
'Sensibilitas_Kornea_Kanan' => array( 'integrated_search_field45' ),
'Schirmer_Test_Kiri' => array( 'integrated_search_field46' ),
'Schirmer_Test_Kanan' => array( 'integrated_search_field47' ),
'Hirschberg_Test_Kiri' => array( 'integrated_search_field48' ),
'Hirschberg_Test_Kanan' => array( 'integrated_search_field49' ),
'Cover_Test_Kiri' => array( 'integrated_search_field50' ),
'Cover_Test_Kanan' => array( 'integrated_search_field51' ),
'Cover_Uncover_Test_Kiri' => array( 'integrated_search_field52' ),
'Cover_Uncover_Test_Kanan' => array( 'integrated_search_field53' ),
'Penunjang_Lain' => array( 'integrated_search_field54' ),
'Daftar_Masalah' => array( 'integrated_search_field55' ),
'Rencana_Permulaan' => array( 'integrated_search_field56' ),
'Catatan_Kemajuan' => array( 'integrated_search_field57' ),
'Diagnosa_Diagnosa_Banding' => array( 'integrated_search_field58' ),
'Terapi' => array( 'integrated_search_field59' ),
'Prognosis' => array( 'integrated_search_field60' ),
'Komplikasi' => array( 'integrated_search_field61' ),
'Id_User' => array( 'integrated_search_field62' ),
'Id_Pasien' => array( 'integrated_search_field63' ),
'Nomor_Rm' => array( 'integrated_search_field64' ),
'Alamat' => array( 'integrated_search_field65' ),
'Umur' => array( 'integrated_search_field66' ),
'Status_Perkawinan' => array( 'integrated_search_field67' ),
'Jenis Kelamin' => array( 'integrated_search_field68' ),
'Suku_Ras' => array( 'integrated_search_field69' ),
'Agama' => array( 'integrated_search_field70' ),
'Pekerjaan' => array( 'integrated_search_field71' ),
'Tanggal_MRS' => array( 'integrated_search_field72' ),
'name' => array( 'integrated_search_field73' ),
'Id_Mata' => array( 'integrated_search_field74' ),
'id_pasien1' => array( 'integrated_search_field75' ),
'id' => array( 'integrated_search_field76' ),
'username' => array( 'integrated_search_field77' ),
'email' => array( 'integrated_search_field78' ),
'email_verified_at' => array( 'integrated_search_field79' ),
'password' => array( 'integrated_search_field80' ),
'two_factor_secret' => array( 'integrated_search_field81' ),
'two_factor_recovery_codes' => array( 'integrated_search_field82' ),
'level' => array( 'integrated_search_field83' ),
'remember_token' => array( 'integrated_search_field84' ),
'profile_photo_path' => array( 'integrated_search_field85' ),
'created_at' => array( 'integrated_search_field86' ),
'updated_at' => array( 'integrated_search_field87' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid',
'integrated_search_field70' => 'grid',
'integrated_search_field71' => 'grid',
'integrated_search_field72' => 'grid',
'integrated_search_field73' => 'grid',
'integrated_search_field74' => 'grid',
'integrated_search_field75' => 'grid',
'integrated_search_field76' => 'grid',
'integrated_search_field77' => 'grid',
'integrated_search_field78' => 'grid',
'integrated_search_field79' => 'grid',
'integrated_search_field80' => 'grid',
'integrated_search_field81' => 'grid',
'integrated_search_field82' => 'grid',
'integrated_search_field83' => 'grid',
'integrated_search_field84' => 'grid',
'integrated_search_field85' => 'grid',
'integrated_search_field86' => 'grid',
'integrated_search_field87' => 'grid' ),
'itemLocations' => array( 'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field70' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field71' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field72' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field73' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field74' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field75' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field76' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field77' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field78' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field79' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field80' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field81' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field82' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field83' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field84' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field85' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field86' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field87' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69',
'integrated_search_field70',
'integrated_search_field71',
'integrated_search_field72',
'integrated_search_field73',
'integrated_search_field74',
'integrated_search_field75',
'integrated_search_field76',
'integrated_search_field77',
'integrated_search_field78',
'integrated_search_field79',
'integrated_search_field80',
'integrated_search_field81',
'integrated_search_field82',
'integrated_search_field83',
'integrated_search_field84',
'integrated_search_field85',
'integrated_search_field86',
'integrated_search_field87' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'Nama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'Riwayat_Penyakit_Sekarang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'Riwayat_Penyakit_Dahulu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'Riwayat_Penyakit_Keluarga',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'Riwayat_Alergi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'Riwayat_Pengobatan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'Riwayat_Kebiasaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'Riwayat_Sosio_Ekonomi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'Visus_OD_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'Visus_OS_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'Refraksi_OD_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'Refraksi_OS_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'Addisi_OD_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'Addisi_OS_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'Posisi_Bola_Mata_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'Posisi_Bola_Mata_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'Gerakan_Bola_Mata_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'Gerakan_Bola_Mata_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'Palpebra_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'Palpebra_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'Conjunctiva_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'Conjunctiva_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'Cornea_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'Cornea_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'COA_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'COA_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'Pupil_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'Pupil_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'Iris_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'Iris_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'Lensa_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'Lensa_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'Tekanan_Intra_Okuler_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'Tekanan_Intra_Okuler_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'Segment_Posterior_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'Segment_Posterior_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'Lapang_Pandang_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'Lapang_Pandang_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'Ishihara_Test_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'Ishihara_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'Fluorescein_Tes_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'Fluorescein_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'Sensibilitas_Kornea_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'Sensibilitas_Kornea_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'Schirmer_Test_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'Schirmer_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'Hirschberg_Test_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'Hirschberg_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'Cover_Test_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'Cover_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'Cover_Uncover_Test_Kiri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'Cover_Uncover_Test_Kanan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'Penunjang_Lain',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'Daftar_Masalah',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'Rencana_Permulaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'Catatan_Kemajuan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'Diagnosa_Diagnosa_Banding',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'Terapi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'Prognosis',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'Komplikasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'Id_User',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'Id_Pasien',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'Alamat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'Umur',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field70' => array( 'field' => 'Agama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field71' => array( 'field' => 'Pekerjaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field72' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field73' => array( 'field' => 'name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field74' => array( 'field' => 'Id_Mata',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field75' => array( 'field' => 'id_pasien1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field76' => array( 'field' => 'id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field77' => array( 'field' => 'username',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field78' => array( 'field' => 'email',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field79' => array( 'field' => 'email_verified_at',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field80' => array( 'field' => 'password',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field81' => array( 'field' => 'two_factor_secret',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field82' => array( 'field' => 'two_factor_recovery_codes',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field83' => array( 'field' => 'level',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field84' => array( 'field' => 'remember_token',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field85' => array( 'field' => 'profile_photo_path',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field86' => array( 'field' => 'created_at',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field87' => array( 'field' => 'updated_at',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>