<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'catatan_kemajuan' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'daftar_masalah' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'rencana_permulaan' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'master' => array( 'identitas_pasien' => array( 'preview' => true ),
'users' => array( 'preview' => false ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Id_Mata' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Keluhan_Tambahan' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Sekarang' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Dahulu' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Keluarga' => array( 'totalsType' => '' ),
'Riwayat_Alergi' => array( 'totalsType' => '' ),
'Riwayat_Pengobatan' => array( 'totalsType' => '' ),
'Riwayat_Kebiasaan' => array( 'totalsType' => '' ),
'Riwayat_Sosio_Ekonomi' => array( 'totalsType' => '' ),
'Visus_OD_Kiri' => array( 'totalsType' => '' ),
'Visus_OS_Kanan' => array( 'totalsType' => '' ),
'Refraksi_OD_Kiri' => array( 'totalsType' => '' ),
'Refraksi_OS_Kanan' => array( 'totalsType' => '' ),
'Addisi_OD_Kiri' => array( 'totalsType' => '' ),
'Addisi_OS_Kanan' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Palpebra_Kiri' => array( 'totalsType' => '' ),
'Palpebra_Kanan' => array( 'totalsType' => '' ),
'Conjunctiva_Kiri' => array( 'totalsType' => '' ),
'Conjunctiva_Kanan' => array( 'totalsType' => '' ),
'Cornea_Kiri' => array( 'totalsType' => '' ),
'Cornea_Kanan' => array( 'totalsType' => '' ),
'COA_Kiri' => array( 'totalsType' => '' ),
'COA_Kanan' => array( 'totalsType' => '' ),
'Pupil_Kiri' => array( 'totalsType' => '' ),
'Pupil_Kanan' => array( 'totalsType' => '' ),
'Iris_Kiri' => array( 'totalsType' => '' ),
'Iris_Kanan' => array( 'totalsType' => '' ),
'Lensa_Kiri' => array( 'totalsType' => '' ),
'Lensa_Kanan' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kiri' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kanan' => array( 'totalsType' => '' ),
'Segment_Posterior_Kiri' => array( 'totalsType' => '' ),
'Segment_Posterior_Kanan' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kiri' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kanan' => array( 'totalsType' => '' ),
'Ishihara_Test_Kiri' => array( 'totalsType' => '' ),
'Ishihara_Test_Kanan' => array( 'totalsType' => '' ),
'Fluorescein_Tes_Kiri' => array( 'totalsType' => '' ),
'Fluorescein_Test_Kanan' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kiri' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kanan' => array( 'totalsType' => '' ),
'Schirmer_Test_Kiri' => array( 'totalsType' => '' ),
'Schirmer_Test_Kanan' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kiri' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kanan' => array( 'totalsType' => '' ),
'Penunjang_Lain' => array( 'totalsType' => '' ),
'Daftar_Masalah' => array( 'totalsType' => '' ),
'Rencana_Permulaan' => array( 'totalsType' => '' ),
'Catatan_Kemajuan' => array( 'totalsType' => '' ),
'Diagnosa_Diagnosa_Banding' => array( 'totalsType' => '' ),
'Terapi' => array( 'totalsType' => '' ),
'Prognosis' => array( 'totalsType' => '' ),
'Komplikasi' => array( 'totalsType' => '' ),
'Id_User' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Pekerjaan' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'email_verified_at' => array( 'totalsType' => '' ),
'password' => array( 'totalsType' => '' ),
'two_factor_secret' => array( 'totalsType' => '' ),
'two_factor_recovery_codes' => array( 'totalsType' => '' ),
'level' => array( 'totalsType' => '' ),
'remember_token' => array( 'totalsType' => '' ),
'profile_photo_path' => array( 'totalsType' => '' ),
'created_at' => array( 'totalsType' => '' ),
'updated_at' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Tambahan',
'Keluhan_Utama',
'Nomor_Rm',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Pekerjaan',
'Tanggal_MRS',
'id',
'name',
'username',
'email',
'email_verified_at',
'password',
'two_factor_secret',
'two_factor_recovery_codes',
'level',
'remember_token',
'profile_photo_path',
'created_at',
'updated_at' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Addisi_OD_Kiri',
'updated_at',
'created_at',
'profile_photo_path',
'remember_token',
'level',
'two_factor_recovery_codes',
'two_factor_secret',
'password',
'email_verified_at',
'email',
'username',
'name',
'id',
'Tanggal_MRS',
'Pekerjaan',
'Agama',
'Suku_Ras',
'Jenis Kelamin',
'Status_Perkawinan',
'Umur',
'Alamat',
'Nama',
'Id_Pasien1',
'Nomor_Rm',
'Visus_OS_Kanan',
'Visus_OD_Kiri',
'Terapi',
'Tekanan_Intra_Okuler_Kiri',
'Tekanan_Intra_Okuler_Kanan',
'Sensibilitas_Kornea_Kiri',
'Sensibilitas_Kornea_Kanan',
'Segment_Posterior_Kiri',
'Segment_Posterior_Kanan',
'Schirmer_Test_Kiri',
'Schirmer_Test_Kanan',
'Riwayat_Sosio_Ekonomi',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Alergi',
'Rencana_Permulaan',
'Refraksi_OS_Kanan',
'Refraksi_OD_Kiri',
'Pupil_Kiri',
'Pupil_Kanan',
'Prognosis',
'Posisi_Bola_Mata_Kiri',
'Posisi_Bola_Mata_Kanan',
'Penunjang_Lain',
'Palpebra_Kiri',
'Palpebra_Kanan',
'Lensa_Kiri',
'Lensa_Kanan',
'Lapang_Pandang_Kiri',
'Lapang_Pandang_Kanan',
'Komplikasi',
'Keluhan_Utama',
'Keluhan_Tambahan',
'Ishihara_Test_Kiri',
'Ishihara_Test_Kanan',
'Iris_Kiri',
'Iris_Kanan',
'Hirschberg_Test_Kiri',
'Hirschberg_Test_Kanan',
'Gerakan_Bola_Mata_Kiri',
'Gerakan_Bola_Mata_Kanan',
'Fluorescein_Test_Kanan',
'Fluorescein_Tes_Kiri',
'Diagnosa_Diagnosa_Banding',
'Daftar_Masalah',
'Cover_Uncover_Test_Kiri',
'Cover_Uncover_Test_Kanan',
'Cover_Test_Kiri',
'Cover_Test_Kanan',
'Cornea_Kiri',
'Cornea_Kanan',
'Conjunctiva_Kiri',
'Conjunctiva_Kanan',
'Catatan_Kemajuan',
'COA_Kiri',
'COA_Kanan',
'Addisi_OS_Kanan' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Keluhan_Tambahan' => array( 'simple_grid_field2',
'simple_grid_field63' ),
'Keluhan_Utama' => array( 'simple_grid_field1',
'simple_grid_field' ),
'Nomor_Rm' => array( 'grid_field',
'grid_field_label' ),
'Id_Pasien1' => array( 'grid_field1',
'grid_field_label1' ),
'Nama' => array( 'grid_field2',
'grid_field_label2' ),
'Alamat' => array( 'grid_field3',
'grid_field_label3' ),
'Umur' => array( 'grid_field4',
'grid_field_label4' ),
'Status_Perkawinan' => array( 'grid_field5',
'grid_field_label5' ),
'Jenis Kelamin' => array( 'grid_field6',
'grid_field_label6' ),
'Suku_Ras' => array( 'grid_field7',
'grid_field_label7' ),
'Agama' => array( 'grid_field8',
'grid_field_label8' ),
'Pekerjaan' => array( 'grid_field9',
'grid_field_label9' ),
'Tanggal_MRS' => array( 'grid_field10',
'grid_field_label10' ),
'id' => array( 'grid_field11',
'grid_field_label11' ),
'name' => array( 'grid_field12',
'grid_field_label12' ),
'username' => array( 'grid_field13',
'grid_field_label13' ),
'email' => array( 'grid_field14',
'grid_field_label14' ),
'email_verified_at' => array( 'grid_field15',
'grid_field_label15' ),
'password' => array( 'grid_field16',
'grid_field_label16' ),
'two_factor_secret' => array( 'grid_field17',
'grid_field_label17' ),
'two_factor_recovery_codes' => array( 'grid_field18',
'grid_field_label18' ),
'level' => array( 'grid_field19',
'grid_field_label19' ),
'remember_token' => array( 'grid_field20',
'grid_field_label20' ),
'profile_photo_path' => array( 'grid_field21',
'grid_field_label21' ),
'created_at' => array( 'grid_field22',
'grid_field_label22' ),
'updated_at' => array( 'grid_field23',
'grid_field_label23' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'inline_add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field63',
'simple_grid_field2',
'grid_checkbox_head',
'grid_checkbox',
'grid_edit',
'grid_inline_cancel',
'grid_view',
'details_preview2',
'details_preview',
'details_preview1',
'grid_alldetails_link',
'grid_details_link',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13',
'grid_field_label14',
'grid_field14',
'grid_field_label15',
'grid_field15',
'grid_field_label16',
'grid_field16',
'grid_field_label17',
'grid_field17',
'grid_field_label18',
'grid_field18',
'grid_field_label19',
'grid_field19',
'grid_field_label20',
'grid_field20',
'grid_field_label21',
'grid_field21',
'grid_field_label22',
'grid_field22',
'grid_field_label23',
'grid_field23' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field2' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'details_preview2' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label14' => 'grid',
'grid_field14' => 'grid',
'grid_field_label15' => 'grid',
'grid_field15' => 'grid',
'grid_field_label16' => 'grid',
'grid_field16' => 'grid',
'grid_field_label17' => 'grid',
'grid_field17' => 'grid',
'grid_field_label18' => 'grid',
'grid_field18' => 'grid',
'grid_field_label19' => 'grid',
'grid_field19' => 'grid',
'grid_field_label20' => 'grid',
'grid_field20' => 'grid',
'grid_field_label21' => 'grid',
'grid_field21' => 'grid',
'grid_field_label22' => 'grid',
'grid_field22' => 'grid',
'grid_field_label23' => 'grid',
'grid_field23' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'grid_field_label14' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'grid_field_label15' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'grid_field_label16' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'grid_field_label17' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'grid_field_label18' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'grid_field_label19' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'grid_field_label20' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'grid_field_label21' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'grid_field_label22' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'grid_field_label23' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field2',
'simple_grid_field1',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field10',
'grid_field11',
'grid_field12',
'grid_field13',
'grid_field14',
'grid_field15',
'grid_field16',
'grid_field17',
'grid_field18',
'grid_field19',
'grid_field20',
'grid_field21',
'grid_field22',
'grid_field23' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56',
'search_panel_field57',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60',
'search_panel_field61',
'search_panel_field62',
'search_panel_field21',
'search_panel_field22',
'search_panel_field63',
'search_panel_field64',
'search_panel_field65',
'search_panel_field66',
'search_panel_field67',
'search_panel_field68',
'search_panel_field69',
'search_panel_field70',
'search_panel_field71',
'search_panel_field72',
'search_panel_field73',
'search_panel_field74',
'search_panel_field75',
'search_panel_field76',
'search_panel_field77',
'search_panel_field78',
'search_panel_field79',
'search_panel_field80',
'search_panel_field81',
'search_panel_field82',
'search_panel_field83',
'search_panel_field84' ),
'logo' => array( 'logo1' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_field_label' => array( 'simple_grid_field63',
'simple_grid_field',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9',
'grid_field_label10',
'grid_field_label11',
'grid_field_label12',
'grid_field_label13',
'grid_field_label14',
'grid_field_label15',
'grid_field_label16',
'grid_field_label17',
'grid_field_label18',
'grid_field_label19',
'grid_field_label20',
'grid_field_label21',
'grid_field_label22',
'grid_field_label23' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'master_info' => array( 'master_info' ),
'grid_details_link' => array( 'grid_details_link' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Utama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Tambahan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Id_Pasien1_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Nama_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Alamat_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Umur_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Status_Perkawinan_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Jenis_Kelamin_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Suku_Ras_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Agama_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Pekerjaan_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Tanggal_MRS_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'name_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'username_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'grid_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'email_verified_at_fieldheadercolumn' ),
'items' => array( 'grid_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'password_fieldheadercolumn' ),
'items' => array( 'grid_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'two_factor_secret_fieldheadercolumn' ),
'items' => array( 'grid_field_label17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'two_factor_recovery_codes_fieldheadercolumn' ),
'items' => array( 'grid_field_label18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'level_fieldheadercolumn' ),
'items' => array( 'grid_field_label19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'remember_token_fieldheadercolumn' ),
'items' => array( 'grid_field_label20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'profile_photo_path_fieldheadercolumn' ),
'items' => array( 'grid_field_label21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'created_at_fieldheadercolumn' ),
'items' => array( 'grid_field_label22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'updated_at_fieldheadercolumn' ),
'items' => array( 'grid_field_label23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'inline_cancel',
'view_column' ),
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Utama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Tambahan_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Id_Pasien1_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Nama_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Alamat_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Umur_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Status_Perkawinan_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Jenis_Kelamin_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Suku_Ras_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Agama_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Pekerjaan_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Tanggal_MRS_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'name_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'username_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'email_verified_at_fieldcolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'password_fieldcolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'two_factor_secret_fieldcolumn' ),
'items' => array( 'grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'two_factor_recovery_codes_fieldcolumn' ),
'items' => array( 'grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'level_fieldcolumn' ),
'items' => array( 'grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'remember_token_fieldcolumn' ),
'items' => array( 'grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'profile_photo_path_fieldcolumn' ),
'items' => array( 'grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'created_at_fieldcolumn' ),
'items' => array( 'grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'updated_at_fieldcolumn' ),
'items' => array( 'grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
26,
27,
28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview2',
'details_preview',
'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 18 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 19 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 20 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 21 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 22 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 23 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 24 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 25 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 26 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 27 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 28 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 29,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 29 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'Keluhan_Tambahan',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Keluhan_Tambahan',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview2',
'details_preview',
'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link' ),
'columnName' => 'details' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'Nama',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'Nama',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'Umur',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'Umur',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'Agama',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'Agama',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'Pekerjaan',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'Pekerjaan',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label10' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label11' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label12' ),
'field' => 'name',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'name',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label13' ),
'field' => 'username',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'username',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label14' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'grid_field14' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label15' ),
'field' => 'email_verified_at',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'grid_field15' ),
'field' => 'email_verified_at',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label16' ),
'field' => 'password',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'grid_field16' ),
'field' => 'password',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label17' ),
'field' => 'two_factor_secret',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'grid_field17' ),
'field' => 'two_factor_secret',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label18' ),
'field' => 'two_factor_recovery_codes',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'grid_field18' ),
'field' => 'two_factor_recovery_codes',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label19' ),
'field' => 'level',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'grid_field19' ),
'field' => 'level',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label20' ),
'field' => 'remember_token',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'grid_field20' ),
'field' => 'remember_token',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label21' ),
'field' => 'profile_photo_path',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'grid_field21' ),
'field' => 'profile_photo_path',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label22' ),
'field' => 'created_at',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'grid_field22' ),
'field' => 'created_at',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label23' ),
'field' => 'updated_at',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'grid_field23' ),
'field' => 'updated_at',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'simple_grid_field2' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field84',
'search_panel_field83',
'search_panel_field82',
'search_panel_field81',
'search_panel_field80',
'search_panel_field79',
'search_panel_field78',
'search_panel_field77',
'search_panel_field76',
'search_panel_field75',
'search_panel_field74',
'search_panel_field73',
'search_panel_field72',
'search_panel_field71',
'search_panel_field70',
'search_panel_field69',
'search_panel_field68',
'search_panel_field67',
'search_panel_field66',
'search_panel_field65',
'search_panel_field64',
'search_panel_field63',
'search_panel_field22',
'search_panel_field21',
'search_panel_field62',
'search_panel_field61',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field57',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Addisi_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'Addisi_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'COA_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'COA_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'Catatan_Kemajuan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'Conjunctiva_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'Conjunctiva_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'Cornea_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'Cornea_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field9' => array( 'field' => 'Cover_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'Cover_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'Cover_Uncover_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'Cover_Uncover_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'Daftar_Masalah',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'Diagnosa_Diagnosa_Banding',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field15' => array( 'field' => 'Fluorescein_Tes_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'Fluorescein_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'Gerakan_Bola_Mata_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field18' => array( 'field' => 'Gerakan_Bola_Mata_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'Hirschberg_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'Hirschberg_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'Iris_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field24' => array( 'field' => 'Iris_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field25' => array( 'field' => 'Ishihara_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'Ishihara_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field28' => array( 'field' => 'Keluhan_Utama',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field29' => array( 'field' => 'Komplikasi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'Lapang_Pandang_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'Lapang_Pandang_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'Lensa_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field33' => array( 'field' => 'Lensa_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field34' => array( 'field' => 'Palpebra_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field35' => array( 'field' => 'Palpebra_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field36' => array( 'field' => 'Penunjang_Lain',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'Posisi_Bola_Mata_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field38' => array( 'field' => 'Posisi_Bola_Mata_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field39' => array( 'field' => 'Prognosis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'Pupil_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field41' => array( 'field' => 'Pupil_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field42' => array( 'field' => 'Refraksi_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field43' => array( 'field' => 'Refraksi_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field44' => array( 'field' => 'Rencana_Permulaan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field45' => array( 'field' => 'Riwayat_Alergi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'Riwayat_Kebiasaan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'Riwayat_Pengobatan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'Riwayat_Penyakit_Dahulu',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'Riwayat_Penyakit_Keluarga',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'Riwayat_Penyakit_Sekarang',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field51' => array( 'field' => 'Riwayat_Sosio_Ekonomi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'Schirmer_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'Schirmer_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'Segment_Posterior_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field55' => array( 'field' => 'Segment_Posterior_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'Sensibilitas_Kornea_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'Sensibilitas_Kornea_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field58' => array( 'field' => 'Tekanan_Intra_Okuler_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field59' => array( 'field' => 'Tekanan_Intra_Okuler_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'Terapi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'Visus_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field62' => array( 'field' => 'Visus_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'logo1' => array( 'type' => 'logo' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Tambahan' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Utama' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'daftar_masalah' => true,
'rencana_permulaan' => true,
'catatan_kemajuan' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'daftar_masalah',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'rencana_permulaan',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'catatan_kemajuan',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'grid_field' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'search_panel_field21' => array( 'field' => 'Nomor_Rm',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'catatan_kemajuan',
'badge' => true,
'showCount' => true,
'hideIfNone' => false ),
'grid_field1' => array( 'field' => 'Id_Pasien1',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'Id_Pasien1' ),
'search_panel_field22' => array( 'field' => 'Id_Pasien1',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field2' => array( 'field' => 'Nama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'Nama' ),
'search_panel_field63' => array( 'field' => 'Nama',
'type' => 'search_panel_field',
'required' => false ),
'grid_field3' => array( 'field' => 'Alamat',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'Alamat' ),
'search_panel_field64' => array( 'field' => 'Alamat',
'type' => 'search_panel_field',
'required' => false ),
'grid_field4' => array( 'field' => 'Umur',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'Umur' ),
'search_panel_field65' => array( 'field' => 'Umur',
'type' => 'search_panel_field',
'required' => false ),
'grid_field5' => array( 'field' => 'Status_Perkawinan',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'Status_Perkawinan' ),
'search_panel_field66' => array( 'field' => 'Status_Perkawinan',
'type' => 'search_panel_field',
'required' => false ),
'grid_field6' => array( 'field' => 'Jenis Kelamin',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'Jenis Kelamin' ),
'search_panel_field67' => array( 'field' => 'Jenis Kelamin',
'type' => 'search_panel_field',
'required' => false ),
'grid_field7' => array( 'field' => 'Suku_Ras',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'Suku_Ras' ),
'search_panel_field68' => array( 'field' => 'Suku_Ras',
'type' => 'search_panel_field',
'required' => false ),
'grid_field8' => array( 'field' => 'Agama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'Agama' ),
'search_panel_field69' => array( 'field' => 'Agama',
'type' => 'search_panel_field',
'required' => false ),
'grid_field9' => array( 'field' => 'Pekerjaan',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'Pekerjaan' ),
'search_panel_field70' => array( 'field' => 'Pekerjaan',
'type' => 'search_panel_field',
'required' => false ),
'grid_field10' => array( 'field' => 'Tanggal_MRS',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'Tanggal_MRS' ),
'search_panel_field71' => array( 'field' => 'Tanggal_MRS',
'type' => 'search_panel_field',
'required' => false ),
'grid_field11' => array( 'field' => 'id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'search_panel_field72' => array( 'field' => 'id',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field12' => array( 'field' => 'name',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'name' ),
'search_panel_field73' => array( 'field' => 'name',
'type' => 'search_panel_field',
'required' => false ),
'grid_field13' => array( 'field' => 'username',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'username' ),
'search_panel_field74' => array( 'field' => 'username',
'type' => 'search_panel_field',
'required' => false ),
'grid_field14' => array( 'field' => 'email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label14' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'search_panel_field75' => array( 'field' => 'email',
'type' => 'search_panel_field',
'required' => false ),
'grid_field15' => array( 'field' => 'email_verified_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label15' => array( 'type' => 'grid_field_label',
'field' => 'email_verified_at' ),
'search_panel_field76' => array( 'field' => 'email_verified_at',
'type' => 'search_panel_field',
'required' => false ),
'grid_field16' => array( 'field' => 'password',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label16' => array( 'type' => 'grid_field_label',
'field' => 'password' ),
'search_panel_field77' => array( 'field' => 'password',
'type' => 'search_panel_field',
'required' => false ),
'grid_field17' => array( 'field' => 'two_factor_secret',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label17' => array( 'type' => 'grid_field_label',
'field' => 'two_factor_secret' ),
'search_panel_field78' => array( 'field' => 'two_factor_secret',
'type' => 'search_panel_field',
'required' => false ),
'grid_field18' => array( 'field' => 'two_factor_recovery_codes',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label18' => array( 'type' => 'grid_field_label',
'field' => 'two_factor_recovery_codes' ),
'search_panel_field79' => array( 'field' => 'two_factor_recovery_codes',
'type' => 'search_panel_field',
'required' => false ),
'grid_field19' => array( 'field' => 'level',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label19' => array( 'type' => 'grid_field_label',
'field' => 'level' ),
'search_panel_field80' => array( 'field' => 'level',
'type' => 'search_panel_field',
'required' => false ),
'grid_field20' => array( 'field' => 'remember_token',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label20' => array( 'type' => 'grid_field_label',
'field' => 'remember_token' ),
'search_panel_field81' => array( 'field' => 'remember_token',
'type' => 'search_panel_field',
'required' => false ),
'grid_field21' => array( 'field' => 'profile_photo_path',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label21' => array( 'type' => 'grid_field_label',
'field' => 'profile_photo_path' ),
'search_panel_field82' => array( 'field' => 'profile_photo_path',
'type' => 'search_panel_field',
'required' => false ),
'grid_field22' => array( 'field' => 'created_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label22' => array( 'type' => 'grid_field_label',
'field' => 'created_at' ),
'search_panel_field83' => array( 'field' => 'created_at',
'type' => 'search_panel_field',
'required' => false ),
'grid_field23' => array( 'field' => 'updated_at',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label23' => array( 'type' => 'grid_field_label',
'field' => 'updated_at' ),
'search_panel_field84' => array( 'field' => 'updated_at',
'type' => 'search_panel_field',
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>