<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'catatan_kemajuan' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'daftar_masalah' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'rencana_permulaan' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => false,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'master' => array( 'identitas_pasien' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'Id_Mata' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Keluhan_Tambahan' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Sekarang' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Dahulu' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Keluarga' => array( 'totalsType' => '' ),
'Riwayat_Alergi' => array( 'totalsType' => '' ),
'Riwayat_Pengobatan' => array( 'totalsType' => '' ),
'Riwayat_Kebiasaan' => array( 'totalsType' => '' ),
'Riwayat_Sosio_Ekonomi' => array( 'totalsType' => '' ),
'Visus_OD_Kiri' => array( 'totalsType' => '' ),
'Visus_OS_Kanan' => array( 'totalsType' => '' ),
'Refraksi_OD_Kiri' => array( 'totalsType' => '' ),
'Refraksi_OS_Kanan' => array( 'totalsType' => '' ),
'Addisi_OD_Kiri' => array( 'totalsType' => '' ),
'Addisi_OS_Kanan' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Palpebra_Kiri' => array( 'totalsType' => '' ),
'Palpebra_Kanan' => array( 'totalsType' => '' ),
'Conjunctiva_Kiri' => array( 'totalsType' => '' ),
'Conjunctiva_Kanan' => array( 'totalsType' => '' ),
'Cornea_Kiri' => array( 'totalsType' => '' ),
'Cornea_Kanan' => array( 'totalsType' => '' ),
'COA_Kiri' => array( 'totalsType' => '' ),
'COA_Kanan' => array( 'totalsType' => '' ),
'Pupil_Kiri' => array( 'totalsType' => '' ),
'Pupil_Kanan' => array( 'totalsType' => '' ),
'Iris_Kiri' => array( 'totalsType' => '' ),
'Iris_Kanan' => array( 'totalsType' => '' ),
'Lensa_Kiri' => array( 'totalsType' => '' ),
'Lensa_Kanan' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kiri' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kanan' => array( 'totalsType' => '' ),
'Segment_Posterior_Kiri' => array( 'totalsType' => '' ),
'Segment_Posterior_Kanan' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kiri' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kanan' => array( 'totalsType' => '' ),
'Ishihara_Test_Kiri' => array( 'totalsType' => '' ),
'Ishihara_Test_Kanan' => array( 'totalsType' => '' ),
'Fluorescein_Tes_Kiri' => array( 'totalsType' => '' ),
'Fluorescein_Test_Kanan' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kiri' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kanan' => array( 'totalsType' => '' ),
'Schirmer_Test_Kiri' => array( 'totalsType' => '' ),
'Schirmer_Test_Kanan' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kiri' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kanan' => array( 'totalsType' => '' ),
'Penunjang_Lain' => array( 'totalsType' => '' ),
'Daftar_Masalah' => array( 'totalsType' => '' ),
'Rencana_Permulaan' => array( 'totalsType' => '' ),
'Catatan_Kemajuan' => array( 'totalsType' => '' ),
'Diagnosa_Diagnosa_Banding' => array( 'totalsType' => '' ),
'Terapi' => array( 'totalsType' => '' ),
'Prognosis' => array( 'totalsType' => '' ),
'Komplikasi' => array( 'totalsType' => '' ),
'Id_User' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Addisi_OD_Kiri',
'Nomor_Rm',
'Visus_OS_Kanan',
'Visus_OD_Kiri',
'Terapi',
'Tekanan_Intra_Okuler_Kiri',
'Tekanan_Intra_Okuler_Kanan',
'Sensibilitas_Kornea_Kiri',
'Sensibilitas_Kornea_Kanan',
'Segment_Posterior_Kiri',
'Segment_Posterior_Kanan',
'Schirmer_Test_Kiri',
'Schirmer_Test_Kanan',
'Riwayat_Sosio_Ekonomi',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Alergi',
'Rencana_Permulaan',
'Refraksi_OS_Kanan',
'Refraksi_OD_Kiri',
'Pupil_Kiri',
'Pupil_Kanan',
'Prognosis',
'Posisi_Bola_Mata_Kiri',
'Posisi_Bola_Mata_Kanan',
'Penunjang_Lain',
'Palpebra_Kiri',
'Palpebra_Kanan',
'Lensa_Kiri',
'Lensa_Kanan',
'Lapang_Pandang_Kiri',
'Lapang_Pandang_Kanan',
'Komplikasi',
'Keluhan_Utama',
'Keluhan_Tambahan',
'Ishihara_Test_Kiri',
'Ishihara_Test_Kanan',
'Iris_Kiri',
'Iris_Kanan',
'Hirschberg_Test_Kiri',
'Hirschberg_Test_Kanan',
'Gerakan_Bola_Mata_Kiri',
'Gerakan_Bola_Mata_Kanan',
'Fluorescein_Test_Kanan',
'Fluorescein_Tes_Kiri',
'Diagnosa_Diagnosa_Banding',
'Daftar_Masalah',
'Cover_Uncover_Test_Kiri',
'Cover_Uncover_Test_Kanan',
'Cover_Test_Kiri',
'Cover_Test_Kanan',
'Cornea_Kiri',
'Cornea_Kanan',
'Conjunctiva_Kiri',
'Conjunctiva_Kanan',
'Catatan_Kemajuan',
'COA_Kiri',
'COA_Kanan',
'Addisi_OS_Kanan' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'simple_grid_field1',
'simple_grid_field' ),
'Nomor_Rm' => array( 'grid_field',
'grid_field_label' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'inline_add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field',
'simple_grid_field1',
'grid_checkbox_head',
'grid_checkbox',
'grid_edit',
'grid_inline_cancel',
'grid_view',
'details_preview2',
'details_preview',
'details_preview1',
'grid_alldetails_link',
'grid_field_label',
'grid_field' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field' => 'grid',
'simple_grid_field1' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'details_preview2' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field1',
'grid_field' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56',
'search_panel_field57',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60',
'search_panel_field61',
'search_panel_field62',
'search_panel_field21' ),
'logo' => array( 'logo1' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_field_label' => array( 'simple_grid_field',
'grid_field_label' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'master_info' => array( 'master_info' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Utama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'inline_cancel',
'view_column' ),
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Utama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview2',
'details_preview',
'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 5,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field2' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field2' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 5 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field2' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview2',
'details_preview',
'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ),
'columnName' => 'details' ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link' ),
'columnName' => 'details' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'simple_grid_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field21',
'search_panel_field62',
'search_panel_field61',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field57',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Addisi_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'Addisi_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'COA_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field3' => array( 'field' => 'COA_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'Catatan_Kemajuan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field5' => array( 'field' => 'Conjunctiva_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'Conjunctiva_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'Cornea_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'Cornea_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field9' => array( 'field' => 'Cover_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'Cover_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'Cover_Uncover_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'Cover_Uncover_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'Daftar_Masalah',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'Diagnosa_Diagnosa_Banding',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field15' => array( 'field' => 'Fluorescein_Tes_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'Fluorescein_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'Gerakan_Bola_Mata_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field18' => array( 'field' => 'Gerakan_Bola_Mata_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'Hirschberg_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'Hirschberg_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'Iris_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field24' => array( 'field' => 'Iris_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field25' => array( 'field' => 'Ishihara_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'Ishihara_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field28' => array( 'field' => 'Keluhan_Utama',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field29' => array( 'field' => 'Komplikasi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'Lapang_Pandang_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'Lapang_Pandang_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'Lensa_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field33' => array( 'field' => 'Lensa_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field34' => array( 'field' => 'Palpebra_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field35' => array( 'field' => 'Palpebra_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field36' => array( 'field' => 'Penunjang_Lain',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'Posisi_Bola_Mata_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field38' => array( 'field' => 'Posisi_Bola_Mata_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field39' => array( 'field' => 'Prognosis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'Pupil_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field41' => array( 'field' => 'Pupil_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field42' => array( 'field' => 'Refraksi_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field43' => array( 'field' => 'Refraksi_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field44' => array( 'field' => 'Rencana_Permulaan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field45' => array( 'field' => 'Riwayat_Alergi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'Riwayat_Kebiasaan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'Riwayat_Pengobatan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'Riwayat_Penyakit_Dahulu',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'Riwayat_Penyakit_Keluarga',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'Riwayat_Penyakit_Sekarang',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field51' => array( 'field' => 'Riwayat_Sosio_Ekonomi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'Schirmer_Test_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'Schirmer_Test_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'Segment_Posterior_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field55' => array( 'field' => 'Segment_Posterior_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'Sensibilitas_Kornea_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'Sensibilitas_Kornea_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field58' => array( 'field' => 'Tekanan_Intra_Okuler_Kanan',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field59' => array( 'field' => 'Tekanan_Intra_Okuler_Kiri',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'Terapi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'Visus_OD_Kiri',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field62' => array( 'field' => 'Visus_OS_Kanan',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'logo1' => array( 'type' => 'logo' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Utama' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'daftar_masalah' => true,
'rencana_permulaan' => true,
'catatan_kemajuan' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'daftar_masalah',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'rencana_permulaan',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'catatan_kemajuan',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'grid_field' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'search_panel_field21' => array( 'field' => 'Nomor_Rm',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>