<?php
			$optionsArray = array( 'totals' => array( 'Id_Mata' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Keluhan_Tambahan' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Sekarang' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Dahulu' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Keluarga' => array( 'totalsType' => '' ),
'Riwayat_Alergi' => array( 'totalsType' => '' ),
'Riwayat_Pengobatan' => array( 'totalsType' => '' ),
'Riwayat_Kebiasaan' => array( 'totalsType' => '' ),
'Riwayat_Sosio_Ekonomi' => array( 'totalsType' => '' ),
'Visus_OD_Kiri' => array( 'totalsType' => '' ),
'Visus_OS_Kanan' => array( 'totalsType' => '' ),
'Refraksi_OD_Kiri' => array( 'totalsType' => '' ),
'Refraksi_OS_Kanan' => array( 'totalsType' => '' ),
'Addisi_OD_Kiri' => array( 'totalsType' => '' ),
'Addisi_OS_Kanan' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Posisi_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kiri' => array( 'totalsType' => '' ),
'Gerakan_Bola_Mata_Kanan' => array( 'totalsType' => '' ),
'Palpebra_Kiri' => array( 'totalsType' => '' ),
'Palpebra_Kanan' => array( 'totalsType' => '' ),
'Conjunctiva_Kiri' => array( 'totalsType' => '' ),
'Conjunctiva_Kanan' => array( 'totalsType' => '' ),
'Cornea_Kiri' => array( 'totalsType' => '' ),
'Cornea_Kanan' => array( 'totalsType' => '' ),
'COA_Kiri' => array( 'totalsType' => '' ),
'COA_Kanan' => array( 'totalsType' => '' ),
'Pupil_Kiri' => array( 'totalsType' => '' ),
'Pupil_Kanan' => array( 'totalsType' => '' ),
'Iris_Kiri' => array( 'totalsType' => '' ),
'Iris_Kanan' => array( 'totalsType' => '' ),
'Lensa_Kiri' => array( 'totalsType' => '' ),
'Lensa_Kanan' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kiri' => array( 'totalsType' => '' ),
'Tekanan_Intra_Okuler_Kanan' => array( 'totalsType' => '' ),
'Segment_Posterior_Kiri' => array( 'totalsType' => '' ),
'Segment_Posterior_Kanan' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kiri' => array( 'totalsType' => '' ),
'Lapang_Pandang_Kanan' => array( 'totalsType' => '' ),
'Ishihara_Test_Kiri' => array( 'totalsType' => '' ),
'Ishihara_Test_Kanan' => array( 'totalsType' => '' ),
'Fluorescein_Tes_Kiri' => array( 'totalsType' => '' ),
'Fluorescein_Test_Kanan' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kiri' => array( 'totalsType' => '' ),
'Sensibilitas_Kornea_Kanan' => array( 'totalsType' => '' ),
'Schirmer_Test_Kiri' => array( 'totalsType' => '' ),
'Schirmer_Test_Kanan' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kiri' => array( 'totalsType' => '' ),
'Hirschberg_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Test_Kanan' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kiri' => array( 'totalsType' => '' ),
'Cover_Uncover_Test_Kanan' => array( 'totalsType' => '' ),
'Penunjang_Lain' => array( 'totalsType' => '' ),
'Daftar_Masalah' => array( 'totalsType' => '' ),
'Rencana_Permulaan' => array( 'totalsType' => '' ),
'Catatan_Kemajuan' => array( 'totalsType' => '' ),
'Diagnosa_Diagnosa_Banding' => array( 'totalsType' => '' ),
'Terapi' => array( 'totalsType' => '' ),
'Prognosis' => array( 'totalsType' => '' ),
'Komplikasi' => array( 'totalsType' => '' ),
'Id_User' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Keluhan_Tambahan',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Alergi',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Sosio_Ekonomi',
'Visus_OD_Kiri',
'Visus_OS_Kanan',
'Refraksi_OD_Kiri',
'Refraksi_OS_Kanan',
'Addisi_OD_Kiri',
'Addisi_OS_Kanan',
'Posisi_Bola_Mata_Kiri',
'Posisi_Bola_Mata_Kanan',
'Gerakan_Bola_Mata_Kiri',
'Gerakan_Bola_Mata_Kanan',
'Palpebra_Kiri',
'Palpebra_Kanan',
'Conjunctiva_Kiri',
'Conjunctiva_Kanan',
'Cornea_Kiri',
'Cornea_Kanan',
'COA_Kiri',
'COA_Kanan',
'Pupil_Kiri',
'Pupil_Kanan',
'Iris_Kiri',
'Iris_Kanan',
'Lensa_Kiri',
'Lensa_Kanan',
'Tekanan_Intra_Okuler_Kiri',
'Tekanan_Intra_Okuler_Kanan',
'Segment_Posterior_Kiri',
'Segment_Posterior_Kanan',
'Lapang_Pandang_Kiri',
'Lapang_Pandang_Kanan',
'Ishihara_Test_Kiri',
'Ishihara_Test_Kanan',
'Fluorescein_Tes_Kiri',
'Fluorescein_Test_Kanan',
'Sensibilitas_Kornea_Kiri',
'Sensibilitas_Kornea_Kanan',
'Schirmer_Test_Kiri',
'Schirmer_Test_Kanan',
'Hirschberg_Test_Kiri',
'Hirschberg_Test_Kanan',
'Cover_Test_Kiri',
'Cover_Test_Kanan',
'Cover_Uncover_Test_Kiri',
'Cover_Uncover_Test_Kanan',
'Penunjang_Lain',
'Daftar_Masalah',
'Rencana_Permulaan',
'Catatan_Kemajuan',
'Diagnosa_Diagnosa_Banding',
'Terapi',
'Prognosis',
'Komplikasi',
'Nomor_Rm' ),
'exportFields' => array( 'Keluhan_Utama',
'Keluhan_Tambahan',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Alergi',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Sosio_Ekonomi',
'Visus_OD_Kiri',
'Visus_OS_Kanan',
'Refraksi_OD_Kiri',
'Refraksi_OS_Kanan',
'Addisi_OD_Kiri',
'Addisi_OS_Kanan',
'Posisi_Bola_Mata_Kiri',
'Posisi_Bola_Mata_Kanan',
'Gerakan_Bola_Mata_Kiri',
'Gerakan_Bola_Mata_Kanan',
'Palpebra_Kiri',
'Palpebra_Kanan',
'Conjunctiva_Kiri',
'Conjunctiva_Kanan',
'Cornea_Kiri',
'Cornea_Kanan',
'COA_Kiri',
'COA_Kanan',
'Pupil_Kiri',
'Pupil_Kanan',
'Iris_Kiri',
'Iris_Kanan',
'Lensa_Kiri',
'Lensa_Kanan',
'Tekanan_Intra_Okuler_Kiri',
'Tekanan_Intra_Okuler_Kanan',
'Segment_Posterior_Kiri',
'Segment_Posterior_Kanan',
'Lapang_Pandang_Kiri',
'Lapang_Pandang_Kanan',
'Ishihara_Test_Kiri',
'Ishihara_Test_Kanan',
'Fluorescein_Tes_Kiri',
'Fluorescein_Test_Kanan',
'Sensibilitas_Kornea_Kiri',
'Sensibilitas_Kornea_Kanan',
'Schirmer_Test_Kiri',
'Schirmer_Test_Kanan',
'Hirschberg_Test_Kiri',
'Hirschberg_Test_Kanan',
'Cover_Test_Kiri',
'Cover_Test_Kanan',
'Cover_Uncover_Test_Kiri',
'Cover_Uncover_Test_Kanan',
'Penunjang_Lain',
'Daftar_Masalah',
'Rencana_Permulaan',
'Catatan_Kemajuan',
'Diagnosa_Diagnosa_Banding',
'Terapi',
'Prognosis',
'Komplikasi',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'export_field1' ),
'Keluhan_Tambahan' => array( 'export_field2' ),
'Riwayat_Penyakit_Sekarang' => array( 'export_field3' ),
'Riwayat_Penyakit_Dahulu' => array( 'export_field4' ),
'Riwayat_Penyakit_Keluarga' => array( 'export_field5' ),
'Riwayat_Alergi' => array( 'export_field6' ),
'Riwayat_Pengobatan' => array( 'export_field7' ),
'Riwayat_Kebiasaan' => array( 'export_field8' ),
'Riwayat_Sosio_Ekonomi' => array( 'export_field9' ),
'Visus_OD_Kiri' => array( 'export_field10' ),
'Visus_OS_Kanan' => array( 'export_field11' ),
'Refraksi_OD_Kiri' => array( 'export_field12' ),
'Refraksi_OS_Kanan' => array( 'export_field13' ),
'Addisi_OD_Kiri' => array( 'export_field14' ),
'Addisi_OS_Kanan' => array( 'export_field15' ),
'Posisi_Bola_Mata_Kiri' => array( 'export_field16' ),
'Posisi_Bola_Mata_Kanan' => array( 'export_field17' ),
'Gerakan_Bola_Mata_Kiri' => array( 'export_field18' ),
'Gerakan_Bola_Mata_Kanan' => array( 'export_field19' ),
'Palpebra_Kiri' => array( 'export_field20' ),
'Palpebra_Kanan' => array( 'export_field21' ),
'Conjunctiva_Kiri' => array( 'export_field22' ),
'Conjunctiva_Kanan' => array( 'export_field23' ),
'Cornea_Kiri' => array( 'export_field24' ),
'Cornea_Kanan' => array( 'export_field25' ),
'COA_Kiri' => array( 'export_field26' ),
'COA_Kanan' => array( 'export_field27' ),
'Pupil_Kiri' => array( 'export_field28' ),
'Pupil_Kanan' => array( 'export_field29' ),
'Iris_Kiri' => array( 'export_field30' ),
'Iris_Kanan' => array( 'export_field31' ),
'Lensa_Kiri' => array( 'export_field32' ),
'Lensa_Kanan' => array( 'export_field33' ),
'Tekanan_Intra_Okuler_Kiri' => array( 'export_field34' ),
'Tekanan_Intra_Okuler_Kanan' => array( 'export_field35' ),
'Segment_Posterior_Kiri' => array( 'export_field36' ),
'Segment_Posterior_Kanan' => array( 'export_field37' ),
'Lapang_Pandang_Kiri' => array( 'export_field38' ),
'Lapang_Pandang_Kanan' => array( 'export_field39' ),
'Ishihara_Test_Kiri' => array( 'export_field40' ),
'Ishihara_Test_Kanan' => array( 'export_field41' ),
'Fluorescein_Tes_Kiri' => array( 'export_field42' ),
'Fluorescein_Test_Kanan' => array( 'export_field43' ),
'Sensibilitas_Kornea_Kiri' => array( 'export_field44' ),
'Sensibilitas_Kornea_Kanan' => array( 'export_field45' ),
'Schirmer_Test_Kiri' => array( 'export_field46' ),
'Schirmer_Test_Kanan' => array( 'export_field47' ),
'Hirschberg_Test_Kiri' => array( 'export_field48' ),
'Hirschberg_Test_Kanan' => array( 'export_field49' ),
'Cover_Test_Kiri' => array( 'export_field50' ),
'Cover_Test_Kanan' => array( 'export_field51' ),
'Cover_Uncover_Test_Kiri' => array( 'export_field52' ),
'Cover_Uncover_Test_Kanan' => array( 'export_field53' ),
'Penunjang_Lain' => array( 'export_field54' ),
'Daftar_Masalah' => array( 'export_field55' ),
'Rencana_Permulaan' => array( 'export_field56' ),
'Catatan_Kemajuan' => array( 'export_field57' ),
'Diagnosa_Diagnosa_Banding' => array( 'export_field58' ),
'Terapi' => array( 'export_field59' ),
'Prognosis' => array( 'export_field60' ),
'Komplikasi' => array( 'export_field61' ),
'Nomor_Rm' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Riwayat_Penyakit_Sekarang',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Riwayat_Penyakit_Dahulu',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Riwayat_Penyakit_Keluarga',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Riwayat_Alergi',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Riwayat_Pengobatan',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Riwayat_Kebiasaan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Riwayat_Sosio_Ekonomi',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Visus_OD_Kiri',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Visus_OS_Kanan',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Refraksi_OD_Kiri',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Refraksi_OS_Kanan',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Addisi_OD_Kiri',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Addisi_OS_Kanan',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Posisi_Bola_Mata_Kiri',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Posisi_Bola_Mata_Kanan',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Gerakan_Bola_Mata_Kiri',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Gerakan_Bola_Mata_Kanan',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Palpebra_Kiri',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'Palpebra_Kanan',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Conjunctiva_Kiri',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Conjunctiva_Kanan',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Cornea_Kiri',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Cornea_Kanan',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'COA_Kiri',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'COA_Kanan',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Pupil_Kiri',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Pupil_Kanan',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Iris_Kiri',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'Iris_Kanan',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'Lensa_Kiri',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'Lensa_Kanan',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'Tekanan_Intra_Okuler_Kiri',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Tekanan_Intra_Okuler_Kanan',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'Segment_Posterior_Kiri',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'Segment_Posterior_Kanan',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'Lapang_Pandang_Kiri',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'Lapang_Pandang_Kanan',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'Ishihara_Test_Kiri',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'Ishihara_Test_Kanan',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'Fluorescein_Tes_Kiri',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'Fluorescein_Test_Kanan',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'Sensibilitas_Kornea_Kiri',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'Sensibilitas_Kornea_Kanan',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'Schirmer_Test_Kiri',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'Schirmer_Test_Kanan',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'Hirschberg_Test_Kiri',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'Hirschberg_Test_Kanan',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'Cover_Test_Kiri',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'Cover_Test_Kanan',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'Cover_Uncover_Test_Kiri',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'Cover_Uncover_Test_Kanan',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'Penunjang_Lain',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'Daftar_Masalah',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'Rencana_Permulaan',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'Catatan_Kemajuan',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'Diagnosa_Diagnosa_Banding',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'Terapi',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'Prognosis',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'Komplikasi',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'Nomor_Rm',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>