<?php
			$optionsArray = array( 'totals' => array( 'id_neurologi' => array( 'totalsType' => '' ),
'Keluhan Utama' => array( 'totalsType' => '' ),
'Keluhan Tambahan' => array( 'totalsType' => '' ),
'Riwayat Penyakit Sekarang' => array( 'totalsType' => '' ),
'Riwayat Penyakit Dahulu' => array( 'totalsType' => '' ),
'Riwayat Penyakit Keluarga' => array( 'totalsType' => '' ),
'Riwayat Alergi' => array( 'totalsType' => '' ),
'Riwayat Pengobatan' => array( 'totalsType' => '' ),
'Riwayat Kebiasaan' => array( 'totalsType' => '' ),
'Riwayat Psiko Sosial Ekonomi' => array( 'totalsType' => '' ),
'Pemeriksaan Fisik' => array( 'totalsType' => '' ),
'Status Psikiatri Singkat' => array( 'totalsType' => '' ),
'Status Neurologis' => array( 'totalsType' => '' ),
'PEMERIKSAAN KHUSUS' => array( 'totalsType' => '' ),
'Pemeriksaan Penunjang' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'nomor_rm' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Kerja' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_neurologi',
'Keluhan Utama',
'Keluhan Tambahan',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Riwayat Psiko Sosial Ekonomi',
'Pemeriksaan Fisik',
'Status Psikiatri Singkat',
'Status Neurologis',
'PEMERIKSAAN KHUSUS',
'Pemeriksaan Penunjang',
'id_pasien',
'id_user',
'nomor_rm',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'exportFields' => array( 'Keluhan Utama',
'Keluhan Tambahan',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Riwayat Psiko Sosial Ekonomi',
'Pemeriksaan Fisik',
'Status Psikiatri Singkat',
'Status Neurologis',
'PEMERIKSAAN KHUSUS',
'Pemeriksaan Penunjang',
'id_pasien',
'id_user',
'nomor_rm',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS',
'id_neurologi' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_neurologi' => array( 'export_field' ),
'Keluhan Utama' => array( 'export_field1' ),
'Keluhan Tambahan' => array( 'export_field2' ),
'Riwayat Penyakit Sekarang' => array( 'export_field3' ),
'Riwayat Penyakit Dahulu' => array( 'export_field4' ),
'Riwayat Penyakit Keluarga' => array( 'export_field5' ),
'Riwayat Alergi' => array( 'export_field6' ),
'Riwayat Pengobatan' => array( 'export_field7' ),
'Riwayat Kebiasaan' => array( 'export_field8' ),
'Riwayat Psiko Sosial Ekonomi' => array( 'export_field9' ),
'Pemeriksaan Fisik' => array( 'export_field10' ),
'Status Psikiatri Singkat' => array( 'export_field11' ),
'Status Neurologis' => array( 'export_field12' ),
'PEMERIKSAAN KHUSUS' => array( 'export_field13' ),
'Pemeriksaan Penunjang' => array( 'export_field14' ),
'id_pasien' => array( 'export_field15' ),
'id_user' => array( 'export_field16' ),
'nomor_rm' => array( 'export_field17' ),
'name' => array( 'export_field19' ),
'username' => array( 'export_field20' ),
'email' => array( 'export_field21' ),
'Id_Pasien1' => array( 'export_field22' ),
'Nama' => array( 'export_field23' ),
'Alamat' => array( 'export_field24' ),
'Umur' => array( 'export_field25' ),
'Status_Perkawinan' => array( 'export_field26' ),
'Jenis Kelamin' => array( 'export_field27' ),
'Suku_Ras' => array( 'export_field28' ),
'Agama' => array( 'export_field29' ),
'Kerja' => array( 'export_field30' ),
'Tanggal_MRS' => array( 'export_field31' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_neurologi',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Keluhan Utama',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Keluhan Tambahan',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Riwayat Penyakit Sekarang',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Riwayat Penyakit Dahulu',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Riwayat Penyakit Keluarga',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Riwayat Alergi',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Riwayat Pengobatan',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Riwayat Kebiasaan',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Riwayat Psiko Sosial Ekonomi',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Pemeriksaan Fisik',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Status Psikiatri Singkat',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Status Neurologis',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'PEMERIKSAAN KHUSUS',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Pemeriksaan Penunjang',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'id_pasien',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'id_user',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'nomor_rm',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'name',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'username',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'Id_Pasien1',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'Nama',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'Alamat',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'Umur',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'Status_Perkawinan',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Jenis Kelamin',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Suku_Ras',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'Agama',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'Kerja',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'Tanggal_MRS',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>