<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Id_obstetri',
'Riwayat Penyakit Sekarang',
'Riwayat Penyakit Dahulu',
'Riwayat Penyakit Keluarga',
'Riwayat Alergi',
'Riwayat Pengobatan',
'Riwayat Kebiasaan',
'Riwayat haid',
'Riwayat pernikahan',
'Riwayat Sosial Ekonomi',
'Riwayat persalinan',
'Riwayat menyusui',
'Riwayat imunisasi',
'Riwayat Keluarga Berencana',
'PEMERIKSAA FISIK  UMUM',
'PEMERIKSAAN  OBSTETRI/GINEKOLOGI',
'PEMERIKSAAN PENUNJANG',
'DIAGNOSIS',
'RENCANA TATALAKSANA/ USULAN PEMERIKSAAN',
'KONSELING',
'ANAMNESIS',
'id_pasien',
'id_user',
'nomor_rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Id_obstetri' => array( 'import_field' ),
'Riwayat Penyakit Sekarang' => array( 'import_field3' ),
'Riwayat Penyakit Dahulu' => array( 'import_field4' ),
'Riwayat Penyakit Keluarga' => array( 'import_field5' ),
'Riwayat Alergi' => array( 'import_field6' ),
'Riwayat Pengobatan' => array( 'import_field7' ),
'Riwayat Kebiasaan' => array( 'import_field8' ),
'Riwayat haid' => array( 'import_field9' ),
'Riwayat pernikahan' => array( 'import_field10' ),
'Riwayat Sosial Ekonomi' => array( 'import_field11' ),
'Riwayat persalinan' => array( 'import_field12' ),
'Riwayat menyusui' => array( 'import_field13' ),
'Riwayat imunisasi' => array( 'import_field14' ),
'Riwayat Keluarga Berencana' => array( 'import_field15' ),
'PEMERIKSAA FISIK  UMUM' => array( 'import_field16' ),
'PEMERIKSAAN  OBSTETRI/GINEKOLOGI' => array( 'import_field17' ),
'PEMERIKSAAN PENUNJANG' => array( 'import_field18' ),
'DIAGNOSIS' => array( 'import_field19' ),
'RENCANA TATALAKSANA/ USULAN PEMERIKSAAN' => array( 'import_field20' ),
'KONSELING' => array( 'import_field21' ),
'ANAMNESIS' => array( 'import_field22' ),
'id_pasien' => array( 'import_field1' ),
'id_user' => array( 'import_field2' ),
'nomor_rm' => array( 'import_field23' ),
'id' => array( 'import_field24' ),
'name' => array( 'import_field25' ),
'username' => array( 'import_field26' ),
'email' => array( 'import_field27' ),
'Id_Pasien1' => array( 'import_field28' ),
'Nama' => array( 'import_field29' ),
'Alamat' => array( 'import_field30' ),
'Umur' => array( 'import_field31' ),
'Status_Perkawinan' => array( 'import_field32' ),
'Jenis Kelamin' => array( 'import_field33' ),
'Suku_Ras' => array( 'import_field34' ),
'Agama' => array( 'import_field35' ),
'Kerja' => array( 'import_field36' ),
'Tanggal_MRS' => array( 'import_field37' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field1',
'import_field2',
'import_field23',
'import_field',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field23' => 'grid',
'import_field' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field1',
'import_field2',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field1',
'import_field2',
'import_field23',
'import_field',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Id_obstetri',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Riwayat Penyakit Sekarang',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Riwayat Penyakit Dahulu',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Riwayat Penyakit Keluarga',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Riwayat Alergi',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Riwayat Pengobatan',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Riwayat Kebiasaan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Riwayat haid',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Riwayat pernikahan',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Riwayat Sosial Ekonomi',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Riwayat persalinan',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Riwayat menyusui',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Riwayat imunisasi',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Riwayat Keluarga Berencana',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'PEMERIKSAA FISIK  UMUM',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'PEMERIKSAAN  OBSTETRI/GINEKOLOGI',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'PEMERIKSAAN PENUNJANG',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'DIAGNOSIS',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'RENCANA TATALAKSANA/ USULAN PEMERIKSAAN',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'KONSELING',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'ANAMNESIS',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'id_user',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'nomor_rm',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'id',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'name',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'username',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'email',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Id_Pasien1',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'Nama',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'Alamat',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'Umur',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'Status_Perkawinan',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'Jenis Kelamin',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'Suku_Ras',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Agama',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'Kerja',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'Tanggal_MRS',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>