<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_kelahiran',
'rwyt_tumbuh_kembang',
'rwyt_sos',
'kesan_umum',
'imt',
'tanda_vital',
'pmrksaan_pnunjang_lab',
'pmrksaan_pnunjang_radiologi',
'rwyt_imunisasi',
'pmrksaan_pnunjang_lain',
'tb',
'bb',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'id_pediatri',
'id_mhs',
'id_pasien',
'Nomor_Rm' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'keluhan_pertama' => array( 'import_field1' ),
'keluhan_tmbhan' => array( 'import_field2' ),
'rwyt_skrg' => array( 'import_field3' ),
'rwyt_dulu' => array( 'import_field4' ),
'rwyt_klg' => array( 'import_field5' ),
'rwyt_alergi' => array( 'import_field6' ),
'rwyt_pengobatan' => array( 'import_field7' ),
'rwyt_kebiasaan' => array( 'import_field8' ),
'rwyt_kelahiran' => array( 'import_field9' ),
'rwyt_tumbuh_kembang' => array( 'import_field10' ),
'rwyt_sos' => array( 'import_field11' ),
'kesan_umum' => array( 'import_field12' ),
'imt' => array( 'import_field13' ),
'tanda_vital' => array( 'import_field14' ),
'pmrksaan_pnunjang_lab' => array( 'import_field15' ),
'pmrksaan_pnunjang_radiologi' => array( 'import_field16' ),
'rwyt_imunisasi' => array( 'import_field17' ),
'pmrksaan_pnunjang_lain' => array( 'import_field18' ),
'tb' => array( 'import_field21' ),
'bb' => array( 'import_field22' ),
'kepala' => array( 'import_field28' ),
'leher' => array( 'import_field29' ),
'thorax' => array( 'import_field30' ),
'abdomen' => array( 'import_field31' ),
'ekstremitas' => array( 'import_field32' ),
'id_pediatri' => array( 'import_field' ),
'id_mhs' => array( 'import_field45' ),
'id_pasien' => array( 'import_field46' ),
'Nomor_Rm' => array( 'import_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field11',
'import_field17',
'import_field21',
'import_field22',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field',
'import_field45',
'import_field46',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field18',
'import_field19' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field11' => 'grid',
'import_field17' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field21',
'import_field22',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field',
'import_field45',
'import_field46',
'import_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field11',
'import_field17',
'import_field21',
'import_field22',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field',
'import_field45',
'import_field46',
'import_field9',
'import_field10',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field18',
'import_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'rwyt_klg',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'rwyt_kelahiran',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'rwyt_tumbuh_kembang',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'rwyt_sos',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'kesan_umum',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'imt',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'tanda_vital',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'rwyt_imunisasi',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'tb',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'bb',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'kepala',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'leher',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'thorax',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'abdomen',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'ekstremitas',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'id_pediatri',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'id_mhs',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'id_pasien',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Nomor_Rm',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>