<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'daftar_masalah_pediatri' => array( 'displayPreview' => 1,
'previewPageId' => 'list1' ) ),
'fields' => array( 'gridFields' => array( 'rwyt_kebiasaan',
'Tanggal_MRS',
'Kerja',
'Agama',
'Suku_Ras',
'Jenis Kelamin',
'Status_Perkawinan',
'Umur',
'Alamat',
'Nama',
'email',
'username',
'name',
'pmrksaan_pnunjang_radiologi',
'pmrksaan_pnunjang_lain',
'pmrksaan_pnunjang_lab',
'ekstremitas',
'abdomen',
'thorax',
'leher',
'kepala',
'bb',
'tb',
'tanda_vital',
'kesan_umum',
'rwyt_sos',
'rwyt_pengobatan',
'rwyt_klg',
'rwyt_alergi',
'keluhan_tmbhan',
'rwyt_tumbuh_kembang',
'keluhan_pertama',
'rwyt_kelahiran',
'rwyt_imunisasi',
'rwyt_dulu',
'Nomor_Rm',
'rwyt_skrg',
'imt' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'rwyt_kebiasaan' => array( 'integrated_edit_field8' ),
'Tanggal_MRS' => array( 'integrated_edit_field37' ),
'Kerja' => array( 'integrated_edit_field36' ),
'Agama' => array( 'integrated_edit_field35' ),
'Suku_Ras' => array( 'integrated_edit_field34' ),
'Jenis Kelamin' => array( 'integrated_edit_field33' ),
'Status_Perkawinan' => array( 'integrated_edit_field27' ),
'Umur' => array( 'integrated_edit_field26' ),
'Alamat' => array( 'integrated_edit_field25' ),
'Nama' => array( 'integrated_edit_field24' ),
'email' => array( 'integrated_edit_field23' ),
'username' => array( 'integrated_edit_field22' ),
'name' => array( 'integrated_edit_field21' ),
'pmrksaan_pnunjang_radiologi' => array( 'integrated_edit_field18' ),
'pmrksaan_pnunjang_lain' => array( 'integrated_edit_field19' ),
'pmrksaan_pnunjang_lab' => array( 'integrated_edit_field17' ),
'ekstremitas' => array( 'integrated_edit_field32' ),
'abdomen' => array( 'integrated_edit_field31' ),
'thorax' => array( 'integrated_edit_field30' ),
'leher' => array( 'integrated_edit_field29' ),
'kepala' => array( 'integrated_edit_field28' ),
'bb' => array( 'integrated_edit_field11' ),
'tb' => array( 'integrated_edit_field10' ),
'tanda_vital' => array( 'integrated_edit_field16' ),
'kesan_umum' => array( 'integrated_edit_field14' ),
'rwyt_sos' => array( 'integrated_edit_field13' ),
'rwyt_pengobatan' => array( 'integrated_edit_field7' ),
'rwyt_klg' => array( 'integrated_edit_field5' ),
'rwyt_alergi' => array( 'integrated_edit_field6' ),
'keluhan_tmbhan' => array( 'integrated_edit_field2' ),
'rwyt_tumbuh_kembang' => array( 'integrated_edit_field12' ),
'keluhan_pertama' => array( 'integrated_edit_field1' ),
'rwyt_kelahiran' => array( 'integrated_edit_field' ),
'rwyt_imunisasi' => array( 'integrated_edit_field9' ),
'rwyt_dulu' => array( 'integrated_edit_field4' ),
'Nomor_Rm' => array( 'integrated_edit_field20' ),
'rwyt_skrg' => array( 'integrated_edit_field3' ),
'imt' => array( 'integrated_edit_field15' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'prev',
'next',
'hamburger' ),
'grid' => array( 'master_info',
'section2',
'section3',
'tabs' ),
'section1' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field15',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field',
'integrated_edit_field12',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field13' ),
'section2' => array( 'section',
'section1' ),
'section6' => array( 'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'section7' => array( 'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ),
'section' => array( 'details_preview' ),
'section3' => array( 'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field20',
'integrated_edit_field23' ),
'section4' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'prev' => 'below-grid',
'next' => 'below-grid',
'hamburger' => 'below-grid',
'master_info' => 'grid',
'section2' => 'grid',
'section3' => 'grid',
'tabs' => 'grid',
'integrated_edit_field1' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field15' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field13' => 'section1',
'section' => 'section2',
'section1' => 'section2',
'integrated_edit_field14' => 'section6',
'integrated_edit_field16' => 'section6',
'integrated_edit_field10' => 'section6',
'integrated_edit_field11' => 'section6',
'integrated_edit_field28' => 'section6',
'integrated_edit_field29' => 'section6',
'integrated_edit_field30' => 'section6',
'integrated_edit_field31' => 'section6',
'integrated_edit_field32' => 'section6',
'integrated_edit_field17' => 'section7',
'integrated_edit_field19' => 'section7',
'integrated_edit_field18' => 'section7',
'details_preview' => 'section',
'integrated_edit_field21' => 'section3',
'integrated_edit_field22' => 'section3',
'integrated_edit_field20' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field24' => 'section4',
'integrated_edit_field25' => 'section4',
'integrated_edit_field26' => 'section4',
'integrated_edit_field27' => 'section4',
'integrated_edit_field33' => 'section4',
'integrated_edit_field34' => 'section4',
'integrated_edit_field35' => 'section4',
'integrated_edit_field36' => 'section4',
'integrated_edit_field37' => 'section4' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c' ),
'section' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'section1' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field14' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field17' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'details_preview' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field20' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field35' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field36' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field37' => array( 'location' => 'section4',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field8',
'integrated_edit_field37',
'integrated_edit_field36',
'integrated_edit_field35',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field17',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field30',
'integrated_edit_field29',
'integrated_edit_field28',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field16',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field7',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field2',
'integrated_edit_field12',
'integrated_edit_field1',
'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field20',
'integrated_edit_field3',
'integrated_edit_field15' ),
'section' => array( 'section3',
'section2',
'section1',
'section' ),
'details_preview' => array( 'details_preview' ),
'next' => array( 'next' ),
'prev' => array( 'prev' ),
'tabs' => array( 'tabs' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'section2',
'section3',
'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field15',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21',
'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20',
'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'prev',
'next',
'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c4',
'colspan' => 1,
'rowspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'master_info',
'section2',
'section3',
'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field15',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field9',
'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'left' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'section1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14',
'integrated_edit_field16',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21',
'integrated_edit_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20',
'integrated_edit_field23' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field33' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'pediatri',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_kebiasaan',
'table' => 'pediatri',
'type' => 3 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Identitas Pasien',
'type' => 0 ),
'location' => 'section4' ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Informasi DM',
'type' => 0 ),
'location' => 'section3' ),
'integrated_edit_field37' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field36' => array( 'field' => 'Kerja',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'Agama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'Umur',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'Alamat',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'Nama',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'username',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'daftar_masalah_pediatri',
'items' => array(  ),
'popup' => false,
'pageId' => 'list1' ),
'integrated_edit_field18' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Penunjang',
'type' => 0 ),
'location' => 'section7' ),
'integrated_edit_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'thorax',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'leher',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'kepala',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'bb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'bb',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'tb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tb',
'table' => 'pediatri',
'type' => 3 ) ),
'next' => array( 'type' => 'next' ),
'prev' => array( 'type' => 'prev' ),
'integrated_edit_field16' => array( 'field' => 'tanda_vital',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'kesan_umum',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Pemeriksaan Umum',
'type' => 0 ),
'location' => 'section6' ),
'integrated_edit_field13' => array( 'field' => 'rwyt_sos',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_sos',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_pengobatan',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_klg',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_alergi',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_tmbhan',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'rwyt_tumbuh_kembang',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'keluhan_pertama',
'table' => 'interna',
'type' => 3 ) ),
'integrated_edit_field' => array( 'field' => 'rwyt_kelahiran',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'ANAMNESA',
'type' => 0 ),
array( 'text' => 'PEMERIKSAAN',
'type' => 0 ),
array( 'text' => 'DAFTAR MASALAH',
'type' => 0 ) ),
'locations' => array( 'section1',
'section2',
'section' ) ),
'integrated_edit_field9' => array( 'field' => 'rwyt_imunisasi',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_imunisasi',
'table' => 'pediatri',
'type' => 3 ) ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'integrated_edit_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_dulu',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field20' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rwyt_skrg',
'table' => 'pediatri',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'imt',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>