<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_pediatri',
'keluhan_pertama',
'keluhan_tmbhan',
'rwyt_skrg',
'rwyt_dulu',
'rwyt_klg',
'rwyt_alergi',
'rwyt_pengobatan',
'rwyt_kebiasaan',
'rwyt_kelahiran',
'rwyt_tumbuh_kembang',
'rwyt_sos',
'kesan_umum',
'imt',
'tanda_vital',
'pmrksaan_pnunjang_lab',
'pmrksaan_pnunjang_radiologi',
'rwyt_imunisasi',
'pmrksaan_pnunjang_lain',
'tb',
'bb',
'kepala',
'leher',
'thorax',
'abdomen',
'ekstremitas',
'id_mhs',
'id_pasien',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_pediatri' => array( 'integrated_search_field' ),
'keluhan_pertama' => array( 'integrated_search_field1' ),
'keluhan_tmbhan' => array( 'integrated_search_field2' ),
'rwyt_skrg' => array( 'integrated_search_field3' ),
'rwyt_dulu' => array( 'integrated_search_field4' ),
'rwyt_klg' => array( 'integrated_search_field5' ),
'rwyt_alergi' => array( 'integrated_search_field6' ),
'rwyt_pengobatan' => array( 'integrated_search_field7' ),
'rwyt_kebiasaan' => array( 'integrated_search_field8' ),
'rwyt_kelahiran' => array( 'integrated_search_field9' ),
'rwyt_tumbuh_kembang' => array( 'integrated_search_field10' ),
'rwyt_sos' => array( 'integrated_search_field11' ),
'kesan_umum' => array( 'integrated_search_field12' ),
'imt' => array( 'integrated_search_field13' ),
'tanda_vital' => array( 'integrated_search_field14' ),
'pmrksaan_pnunjang_lab' => array( 'integrated_search_field15' ),
'pmrksaan_pnunjang_radiologi' => array( 'integrated_search_field16' ),
'rwyt_imunisasi' => array( 'integrated_search_field17' ),
'pmrksaan_pnunjang_lain' => array( 'integrated_search_field18' ),
'tb' => array( 'integrated_search_field21' ),
'bb' => array( 'integrated_search_field22' ),
'kepala' => array( 'integrated_search_field28' ),
'leher' => array( 'integrated_search_field29' ),
'thorax' => array( 'integrated_search_field30' ),
'abdomen' => array( 'integrated_search_field31' ),
'ekstremitas' => array( 'integrated_search_field32' ),
'id_mhs' => array( 'integrated_search_field45' ),
'id_pasien' => array( 'integrated_search_field46' ),
'Nomor_Rm' => array( 'integrated_search_field19' ),
'id' => array( 'integrated_search_field20' ),
'name' => array( 'integrated_search_field23' ),
'username' => array( 'integrated_search_field24' ),
'email' => array( 'integrated_search_field25' ),
'Id_Pasien1' => array( 'integrated_search_field26' ),
'Nama' => array( 'integrated_search_field27' ),
'Alamat' => array( 'integrated_search_field33' ),
'Umur' => array( 'integrated_search_field34' ),
'Status_Perkawinan' => array( 'integrated_search_field35' ),
'Jenis Kelamin' => array( 'integrated_search_field36' ),
'Suku_Ras' => array( 'integrated_search_field37' ),
'Agama' => array( 'integrated_search_field38' ),
'Kerja' => array( 'integrated_search_field39' ),
'Tanggal_MRS' => array( 'integrated_search_field40' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field11',
'integrated_search_field17',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid' ),
'itemLocations' => array( 'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field11',
'integrated_search_field17',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field11',
'integrated_search_field17',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'id_pediatri',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'keluhan_pertama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'keluhan_tmbhan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'rwyt_skrg',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'rwyt_dulu',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'rwyt_klg',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'rwyt_alergi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'rwyt_pengobatan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'rwyt_kebiasaan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'rwyt_kelahiran',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'rwyt_tumbuh_kembang',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'rwyt_sos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'kesan_umum',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'imt',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'tanda_vital',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'pmrksaan_pnunjang_lab',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'pmrksaan_pnunjang_radiologi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'rwyt_imunisasi',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'pmrksaan_pnunjang_lain',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'tb',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'bb',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'kepala',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'leher',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'thorax',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'abdomen',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'ekstremitas',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'id_mhs',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'id_pasien',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'Nomor_Rm',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'username',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'email',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'Id_Pasien1',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'Nama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'Alamat',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'Umur',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'Status_Perkawinan',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'Jenis Kelamin',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'Suku_Ras',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'Agama',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'Kerja',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'Tanggal_MRS',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>