<?php
			$optionsArray = array( 'totals' => array( 'id' => array( 'totalsType' => '' ),
'od_spheris' => array( 'totalsType' => '' ),
'od_cylindris' => array( 'totalsType' => '' ),
'od_axis' => array( 'totalsType' => '' ),
'addisi_od' => array( 'totalsType' => '' ),
'os_spheris' => array( 'totalsType' => '' ),
'os_cylindris' => array( 'totalsType' => '' ),
'os_axis' => array( 'totalsType' => '' ),
'addis_os' => array( 'totalsType' => '' ),
'jarak_pupil' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id',
'od_spheris',
'od_cylindris',
'od_axis',
'addisi_od',
'os_spheris',
'os_cylindris',
'os_axis',
'addis_os',
'jarak_pupil',
'id_pasien' ),
'exportFields' => array( 'id',
'od_spheris',
'od_cylindris',
'od_axis',
'addisi_od',
'os_spheris',
'os_cylindris',
'os_axis',
'addis_os',
'jarak_pupil',
'id_pasien' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id' => array( 'export_field' ),
'od_spheris' => array( 'export_field1' ),
'od_cylindris' => array( 'export_field2' ),
'od_axis' => array( 'export_field3' ),
'addisi_od' => array( 'export_field4' ),
'os_spheris' => array( 'export_field5' ),
'os_cylindris' => array( 'export_field6' ),
'os_axis' => array( 'export_field7' ),
'addis_os' => array( 'export_field8' ),
'jarak_pupil' => array( 'export_field9' ),
'id_pasien' => array( 'export_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'od_spheris',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'od_cylindris',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'od_axis',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'addisi_od',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'os_spheris',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'os_cylindris',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'os_axis',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'addis_os',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'jarak_pupil',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'id_pasien',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>