<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'master' => array( 'identitas_pasien' => array( 'preview' => true ),
'users' => array( 'preview' => false ) ),
'totals' => array( 'id_tht' => array( 'totalsType' => '' ),
'Keluhan_Utama' => array( 'totalsType' => '' ),
'Keluhan_Tambahan' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Sekarang' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Dahulu' => array( 'totalsType' => '' ),
'Riwayat_Alergi' => array( 'totalsType' => '' ),
'Riwayat_Penyakit_Keluarga' => array( 'totalsType' => '' ),
'Riwayat_Pengobatan' => array( 'totalsType' => '' ),
'Riwayat_Kebiasaan' => array( 'totalsType' => '' ),
'Riwayat_Sosial_Ekonomi' => array( 'totalsType' => '' ),
'Pem_Umum' => array( 'totalsType' => '' ),
'Tanda_Vital' => array( 'totalsType' => '' ),
'Kepala' => array( 'totalsType' => '' ),
'Leher' => array( 'totalsType' => '' ),
'Telinga' => array( 'totalsType' => '' ),
'Hidung' => array( 'totalsType' => '' ),
'Mulut' => array( 'totalsType' => '' ),
'Epipharynx' => array( 'totalsType' => '' ),
'Larynx' => array( 'totalsType' => '' ),
'Diagnosa_Banding' => array( 'totalsType' => '' ),
'Laboratorium' => array( 'totalsType' => '' ),
'Radiologi' => array( 'totalsType' => '' ),
'Lain_lain' => array( 'totalsType' => '' ),
'Diagnosa' => array( 'totalsType' => '' ),
'Diagnosa_2' => array( 'totalsType' => '' ),
'Diagnosa_3' => array( 'totalsType' => '' ),
'Diagnosa_4' => array( 'totalsType' => '' ),
'Diagnosa_5' => array( 'totalsType' => '' ),
'Terapi_Farmakologi' => array( 'totalsType' => '' ),
'Terapi_Non_Farmakologi' => array( 'totalsType' => '' ),
'Edukasi' => array( 'totalsType' => '' ),
'id_pasien' => array( 'totalsType' => '' ),
'id_user' => array( 'totalsType' => '' ),
'Nomor_Rm' => array( 'totalsType' => '' ),
'id' => array( 'totalsType' => '' ),
'name' => array( 'totalsType' => '' ),
'username' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'Id_Pasien1' => array( 'totalsType' => '' ),
'Nama' => array( 'totalsType' => '' ),
'Alamat' => array( 'totalsType' => '' ),
'Umur' => array( 'totalsType' => '' ),
'Status_Perkawinan' => array( 'totalsType' => '' ),
'Jenis Kelamin' => array( 'totalsType' => '' ),
'Suku_Ras' => array( 'totalsType' => '' ),
'Agama' => array( 'totalsType' => '' ),
'Kerja' => array( 'totalsType' => '' ),
'Tanggal_MRS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Keluhan_Utama',
'Keluhan_Tambahan',
'Riwayat_Penyakit_Sekarang',
'Riwayat_Penyakit_Dahulu',
'Riwayat_Alergi',
'Riwayat_Penyakit_Keluarga',
'Riwayat_Pengobatan',
'Riwayat_Kebiasaan',
'Riwayat_Sosial_Ekonomi',
'Pem_Umum',
'Tanda_Vital',
'Kepala',
'Leher',
'Telinga',
'Hidung',
'Mulut',
'Epipharynx',
'Larynx',
'Diagnosa_Banding',
'Laboratorium',
'Radiologi',
'Lain_lain',
'Diagnosa',
'Terapi_Farmakologi',
'Terapi_Non_Farmakologi',
'Edukasi',
'Diagnosa_2',
'Diagnosa_3',
'Diagnosa_4',
'Diagnosa_5',
'Nomor_Rm',
'id',
'name',
'username',
'email',
'Id_Pasien1',
'Nama',
'Alamat',
'Umur',
'Status_Perkawinan',
'Jenis Kelamin',
'Suku_Ras',
'Agama',
'Kerja',
'Tanggal_MRS' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Keluhan_Utama' => array( 'simple_grid_field1',
'simple_grid_field45' ),
'Keluhan_Tambahan' => array( 'simple_grid_field2',
'simple_grid_field46' ),
'Riwayat_Penyakit_Sekarang' => array( 'simple_grid_field3',
'simple_grid_field47' ),
'Riwayat_Penyakit_Dahulu' => array( 'simple_grid_field4',
'simple_grid_field48' ),
'Riwayat_Alergi' => array( 'simple_grid_field5',
'simple_grid_field49' ),
'Riwayat_Penyakit_Keluarga' => array( 'simple_grid_field6',
'simple_grid_field50' ),
'Riwayat_Pengobatan' => array( 'simple_grid_field7',
'simple_grid_field51' ),
'Riwayat_Kebiasaan' => array( 'simple_grid_field8',
'simple_grid_field52' ),
'Riwayat_Sosial_Ekonomi' => array( 'simple_grid_field9',
'simple_grid_field53' ),
'Pem_Umum' => array( 'simple_grid_field10',
'simple_grid_field54' ),
'Tanda_Vital' => array( 'simple_grid_field11',
'simple_grid_field55' ),
'Kepala' => array( 'simple_grid_field12',
'simple_grid_field56' ),
'Leher' => array( 'simple_grid_field13',
'simple_grid_field57' ),
'Telinga' => array( 'simple_grid_field14',
'simple_grid_field58' ),
'Hidung' => array( 'simple_grid_field15',
'simple_grid_field59' ),
'Mulut' => array( 'simple_grid_field16',
'simple_grid_field60' ),
'Epipharynx' => array( 'simple_grid_field17',
'simple_grid_field61' ),
'Larynx' => array( 'simple_grid_field18',
'simple_grid_field62' ),
'Diagnosa_Banding' => array( 'simple_grid_field19',
'simple_grid_field63' ),
'Laboratorium' => array( 'simple_grid_field20',
'simple_grid_field64' ),
'Radiologi' => array( 'simple_grid_field21',
'simple_grid_field65' ),
'Lain_lain' => array( 'simple_grid_field22',
'simple_grid_field66' ),
'Diagnosa' => array( 'simple_grid_field23',
'simple_grid_field67' ),
'Terapi_Farmakologi' => array( 'simple_grid_field24',
'simple_grid_field68' ),
'Terapi_Non_Farmakologi' => array( 'simple_grid_field25',
'simple_grid_field69' ),
'Edukasi' => array( 'simple_grid_field26',
'simple_grid_field70' ),
'Diagnosa_2' => array( 'simple_grid_field',
'simple_grid_field71' ),
'Diagnosa_3' => array( 'simple_grid_field27',
'simple_grid_field72' ),
'Diagnosa_4' => array( 'simple_grid_field28',
'simple_grid_field73' ),
'Diagnosa_5' => array( 'simple_grid_field29',
'simple_grid_field74' ),
'Nomor_Rm' => array( 'simple_grid_field30',
'simple_grid_field75' ),
'id' => array( 'simple_grid_field31',
'simple_grid_field76' ),
'name' => array( 'simple_grid_field32',
'simple_grid_field77' ),
'username' => array( 'simple_grid_field33',
'simple_grid_field78' ),
'email' => array( 'simple_grid_field34',
'simple_grid_field79' ),
'Id_Pasien1' => array( 'simple_grid_field35',
'simple_grid_field80' ),
'Nama' => array( 'simple_grid_field36',
'simple_grid_field81' ),
'Alamat' => array( 'simple_grid_field37',
'simple_grid_field82' ),
'Umur' => array( 'simple_grid_field38',
'simple_grid_field83' ),
'Status_Perkawinan' => array( 'simple_grid_field39',
'simple_grid_field84' ),
'Jenis Kelamin' => array( 'simple_grid_field40',
'simple_grid_field85' ),
'Suku_Ras' => array( 'simple_grid_field41',
'simple_grid_field86' ),
'Agama' => array( 'simple_grid_field42',
'simple_grid_field87' ),
'Kerja' => array( 'simple_grid_field43',
'simple_grid_field88' ),
'Tanggal_MRS' => array( 'simple_grid_field44',
'simple_grid_field89' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'print_pdf',
'master_info' ),
'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field45',
'simple_grid_field1',
'simple_grid_field46',
'simple_grid_field2',
'simple_grid_field47',
'simple_grid_field3',
'simple_grid_field48',
'simple_grid_field4',
'simple_grid_field49',
'simple_grid_field5',
'simple_grid_field50',
'simple_grid_field6',
'simple_grid_field51',
'simple_grid_field7',
'simple_grid_field52',
'simple_grid_field8',
'simple_grid_field53',
'simple_grid_field9',
'simple_grid_field54',
'simple_grid_field10',
'simple_grid_field55',
'simple_grid_field11',
'simple_grid_field56',
'simple_grid_field12',
'simple_grid_field57',
'simple_grid_field13',
'simple_grid_field58',
'simple_grid_field14',
'simple_grid_field59',
'simple_grid_field15',
'simple_grid_field60',
'simple_grid_field16',
'simple_grid_field61',
'simple_grid_field17',
'simple_grid_field62',
'simple_grid_field18',
'simple_grid_field63',
'simple_grid_field19',
'simple_grid_field64',
'simple_grid_field20',
'simple_grid_field65',
'simple_grid_field21',
'simple_grid_field66',
'simple_grid_field22',
'simple_grid_field67',
'simple_grid_field23',
'simple_grid_field68',
'simple_grid_field24',
'simple_grid_field69',
'simple_grid_field25',
'simple_grid_field70',
'simple_grid_field26',
'simple_grid_field71',
'simple_grid_field',
'simple_grid_field72',
'simple_grid_field27',
'simple_grid_field73',
'simple_grid_field28',
'simple_grid_field74',
'simple_grid_field29',
'simple_grid_field75',
'simple_grid_field30',
'simple_grid_field76',
'simple_grid_field31',
'simple_grid_field77',
'simple_grid_field32',
'simple_grid_field78',
'simple_grid_field33',
'simple_grid_field79',
'simple_grid_field34',
'simple_grid_field80',
'simple_grid_field35',
'simple_grid_field81',
'simple_grid_field36',
'simple_grid_field82',
'simple_grid_field37',
'simple_grid_field83',
'simple_grid_field38',
'simple_grid_field84',
'simple_grid_field39',
'simple_grid_field85',
'simple_grid_field40',
'simple_grid_field86',
'simple_grid_field41',
'simple_grid_field87',
'simple_grid_field42',
'simple_grid_field88',
'simple_grid_field43',
'simple_grid_field89',
'simple_grid_field44' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pdf' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'simple_grid_field45' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field44' => 'grid' ),
'itemLocations' => array( 'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'print_pdf' => array( 'print_pdf' ),
'master_info' => array( 'master_info' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44' ),
'grid_field_label' => array( 'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Utama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Keluhan_Tambahan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Penyakit_Sekarang_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Penyakit_Dahulu_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Alergi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Penyakit_Keluarga_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Pengobatan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Kebiasaan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'Riwayat_Sosial_Ekonomi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'Pem_Umum_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'Tanda_Vital_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Kepala_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Leher_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Telinga_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Hidung_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'Mulut_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'Epipharynx_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Larynx_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_Banding_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'Laboratorium_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'Radiologi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'Lain_lain_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'Terapi_Farmakologi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'Terapi_Non_Farmakologi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'Edukasi_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_3_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_4_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'Diagnosa_5_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'Nomor_Rm_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'name_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'Id_Pasien1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'Nama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'Alamat_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'Umur_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'Status_Perkawinan_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'Jenis_Kelamin_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'Suku_Ras_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'Agama_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'Kerja_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'Tanggal_MRS_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Utama_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Keluhan_Tambahan_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Penyakit_Sekarang_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Penyakit_Dahulu_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Alergi_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Penyakit_Keluarga_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Pengobatan_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Kebiasaan_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'Riwayat_Sosial_Ekonomi_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'Pem_Umum_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'Tanda_Vital_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Kepala_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Leher_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Telinga_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Hidung_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'Mulut_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'Epipharynx_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Larynx_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_Banding_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'Laboratorium_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'Radiologi_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'Lain_lain_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'Terapi_Farmakologi_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'Terapi_Non_Farmakologi_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'Edukasi_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_2_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_3_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_4_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'Diagnosa_5_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'Nomor_Rm_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'id_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'name_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'username_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'email_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'Id_Pasien1_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'Nama_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'Alamat_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'Umur_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'Status_Perkawinan_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'Jenis_Kelamin_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'Suku_Ras_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'Agama_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'Kerja_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'Tanggal_MRS_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 45,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Keluhan_Utama',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'Keluhan_Tambahan',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Keluhan_Tambahan',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'Riwayat_Penyakit_Sekarang',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Riwayat_Penyakit_Sekarang',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'Riwayat_Penyakit_Dahulu',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Riwayat_Penyakit_Dahulu',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'Riwayat_Alergi',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Riwayat_Alergi',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'Riwayat_Penyakit_Keluarga',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'Riwayat_Penyakit_Keluarga',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'Riwayat_Pengobatan',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'Riwayat_Pengobatan',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'Riwayat_Kebiasaan',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'Riwayat_Kebiasaan',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'Riwayat_Sosial_Ekonomi',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'Riwayat_Sosial_Ekonomi',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'Pem_Umum',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'Pem_Umum',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'Tanda_Vital',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'Tanda_Vital',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'Kepala',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Kepala',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'Leher',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'Leher',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'Telinga',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'Telinga',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'Hidung',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'Hidung',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'Mulut',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'Mulut',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'Epipharynx',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'Epipharynx',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'Larynx',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'Larynx',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'Diagnosa_Banding',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'Diagnosa_Banding',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'Laboratorium',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'Laboratorium',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'Radiologi',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'Radiologi',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'Lain_lain',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'Lain_lain',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'Diagnosa',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'Diagnosa',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'Terapi_Farmakologi',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'Terapi_Farmakologi',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'Terapi_Non_Farmakologi',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'Terapi_Non_Farmakologi',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'Edukasi',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'Edukasi',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'Diagnosa_2',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Diagnosa_2',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'Diagnosa_3',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'Diagnosa_3',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'Diagnosa_4',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'Diagnosa_4',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'Diagnosa_5',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'Diagnosa_5',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'Nomor_Rm',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'id',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'id',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'name',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'name',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'username',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'username',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'email',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'email',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'Id_Pasien1',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'Nama',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'Nama',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'Alamat',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'Umur',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'Umur',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'Status_Perkawinan',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'Jenis Kelamin',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'Suku_Ras',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'Agama',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'Agama',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'Kerja',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'Tanggal_MRS',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'identitas_pasien' => 'true' ) ),
'simple_grid_field1' => array( 'field' => 'Keluhan_Utama',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Utama' ),
'simple_grid_field2' => array( 'field' => 'Keluhan_Tambahan',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'Keluhan_Tambahan' ),
'simple_grid_field3' => array( 'field' => 'Riwayat_Penyakit_Sekarang',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Penyakit_Sekarang' ),
'simple_grid_field4' => array( 'field' => 'Riwayat_Penyakit_Dahulu',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Penyakit_Dahulu' ),
'simple_grid_field5' => array( 'field' => 'Riwayat_Alergi',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Alergi' ),
'simple_grid_field6' => array( 'field' => 'Riwayat_Penyakit_Keluarga',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Penyakit_Keluarga' ),
'simple_grid_field7' => array( 'field' => 'Riwayat_Pengobatan',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Pengobatan' ),
'simple_grid_field8' => array( 'field' => 'Riwayat_Kebiasaan',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Kebiasaan' ),
'simple_grid_field9' => array( 'field' => 'Riwayat_Sosial_Ekonomi',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'Riwayat_Sosial_Ekonomi' ),
'simple_grid_field10' => array( 'field' => 'Pem_Umum',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'Pem_Umum' ),
'simple_grid_field11' => array( 'field' => 'Tanda_Vital',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'Tanda_Vital' ),
'simple_grid_field12' => array( 'field' => 'Kepala',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'Kepala' ),
'simple_grid_field13' => array( 'field' => 'Leher',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'Leher' ),
'simple_grid_field14' => array( 'field' => 'Telinga',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'Telinga' ),
'simple_grid_field15' => array( 'field' => 'Hidung',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'Hidung' ),
'simple_grid_field16' => array( 'field' => 'Mulut',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'Mulut' ),
'simple_grid_field17' => array( 'field' => 'Epipharynx',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'Epipharynx' ),
'simple_grid_field18' => array( 'field' => 'Larynx',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'Larynx' ),
'simple_grid_field19' => array( 'field' => 'Diagnosa_Banding',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa_Banding' ),
'simple_grid_field20' => array( 'field' => 'Laboratorium',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'Laboratorium' ),
'simple_grid_field21' => array( 'field' => 'Radiologi',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'Radiologi' ),
'simple_grid_field22' => array( 'field' => 'Lain_lain',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'Lain_lain' ),
'simple_grid_field23' => array( 'field' => 'Diagnosa',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa' ),
'simple_grid_field24' => array( 'field' => 'Terapi_Farmakologi',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'Terapi_Farmakologi' ),
'simple_grid_field25' => array( 'field' => 'Terapi_Non_Farmakologi',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'Terapi_Non_Farmakologi' ),
'simple_grid_field26' => array( 'field' => 'Edukasi',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'Edukasi' ),
'simple_grid_field' => array( 'field' => 'Diagnosa_2',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa_2' ),
'simple_grid_field27' => array( 'field' => 'Diagnosa_3',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa_3' ),
'simple_grid_field28' => array( 'field' => 'Diagnosa_4',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa_4' ),
'simple_grid_field29' => array( 'field' => 'Diagnosa_5',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'Diagnosa_5' ),
'simple_grid_field30' => array( 'field' => 'Nomor_Rm',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'Nomor_Rm' ),
'simple_grid_field31' => array( 'field' => 'id',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'id' ),
'simple_grid_field32' => array( 'field' => 'name',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'name' ),
'simple_grid_field33' => array( 'field' => 'username',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'username' ),
'simple_grid_field34' => array( 'field' => 'email',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'email' ),
'simple_grid_field35' => array( 'field' => 'Id_Pasien1',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'Id_Pasien1' ),
'simple_grid_field36' => array( 'field' => 'Nama',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'Nama' ),
'simple_grid_field37' => array( 'field' => 'Alamat',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'Alamat' ),
'simple_grid_field38' => array( 'field' => 'Umur',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'Umur' ),
'simple_grid_field39' => array( 'field' => 'Status_Perkawinan',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'Status_Perkawinan' ),
'simple_grid_field40' => array( 'field' => 'Jenis Kelamin',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'Jenis Kelamin' ),
'simple_grid_field41' => array( 'field' => 'Suku_Ras',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'Suku_Ras' ),
'simple_grid_field42' => array( 'field' => 'Agama',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'Agama' ),
'simple_grid_field43' => array( 'field' => 'Kerja',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'Kerja' ),
'simple_grid_field44' => array( 'field' => 'Tanggal_MRS',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'Tanggal_MRS' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>