<?php
$dalTableandrologi = array();
$dalTableandrologi["id_andrologi"] = array("type"=>20,"varname"=>"id_andrologi", "name" => "id_andrologi");
$dalTableandrologi["lama_perkawinan_1"] = array("type"=>201,"varname"=>"lama_perkawinan_1", "name" => "lama_perkawinan_1");
$dalTableandrologi["lama_perkawinan_2"] = array("type"=>201,"varname"=>"lama_perkawinan_2", "name" => "lama_perkawinan_2");
$dalTableandrologi["lama_perkawinan_3"] = array("type"=>201,"varname"=>"lama_perkawinan_3", "name" => "lama_perkawinan_3");
$dalTableandrologi["anak_perkawinan_1"] = array("type"=>201,"varname"=>"anak_perkawinan_1", "name" => "anak_perkawinan_1");
$dalTableandrologi["anak_perkawinan_2"] = array("type"=>201,"varname"=>"anak_perkawinan_2", "name" => "anak_perkawinan_2");
$dalTableandrologi["anak_perkawinan_3"] = array("type"=>201,"varname"=>"anak_perkawinan_3", "name" => "anak_perkawinan_3");
$dalTableandrologi["Libido"] = array("type"=>201,"varname"=>"Libido", "name" => "Libido");
$dalTableandrologi["Frekwensi_koitus"] = array("type"=>201,"varname"=>"Frekwensi_koitus", "name" => "Frekwensi_koitus");
$dalTableandrologi["Dispareuni"] = array("type"=>201,"varname"=>"Dispareuni", "name" => "Dispareuni");
$dalTableandrologi["Orgasmus"] = array("type"=>201,"varname"=>"Orgasmus", "name" => "Orgasmus");
$dalTableandrologi["Reflux_Post_Coital"] = array("type"=>201,"varname"=>"Reflux_Post_Coital", "name" => "Reflux_Post_Coital");
$dalTableandrologi["Ejakulasi_Dini"] = array("type"=>201,"varname"=>"Ejakulasi_Dini", "name" => "Ejakulasi_Dini");
$dalTableandrologi["Ejakulasi_Nocturnal"] = array("type"=>201,"varname"=>"Ejakulasi_Nocturnal", "name" => "Ejakulasi_Nocturnal");
$dalTableandrologi["Ejakulasi_Nyeri"] = array("type"=>201,"varname"=>"Ejakulasi_Nyeri", "name" => "Ejakulasi_Nyeri");
$dalTableandrologi["Puber"] = array("type"=>201,"varname"=>"Puber", "name" => "Puber");
$dalTableandrologi["Masturbasi"] = array("type"=>201,"varname"=>"Masturbasi", "name" => "Masturbasi");
$dalTableandrologi["Koitus_pranikah"] = array("type"=>201,"varname"=>"Koitus_pranikah", "name" => "Koitus_pranikah");
$dalTableandrologi["Lain_lain"] = array("type"=>201,"varname"=>"Lain_lain", "name" => "Lain_lain");
$dalTableandrologi["Peny_Hub_Seksual"] = array("type"=>201,"varname"=>"Peny_Hub_Seksual", "name" => "Peny_Hub_Seksual");
$dalTableandrologi["Hernia"] = array("type"=>201,"varname"=>"Hernia", "name" => "Hernia");
$dalTableandrologi["Hidrokel"] = array("type"=>201,"varname"=>"Hidrokel", "name" => "Hidrokel");
$dalTableandrologi["Trauma"] = array("type"=>201,"varname"=>"Trauma", "name" => "Trauma");
$dalTableandrologi["Kelainan_bawaan"] = array("type"=>201,"varname"=>"Kelainan_bawaan", "name" => "Kelainan_bawaan");
$dalTableandrologi["Penyakit_Paru_kronis"] = array("type"=>201,"varname"=>"Penyakit_Paru_kronis", "name" => "Penyakit_Paru_kronis");
$dalTableandrologi["Penyakit_hidung_kronis"] = array("type"=>201,"varname"=>"Penyakit_hidung_kronis", "name" => "Penyakit_hidung_kronis");
$dalTableandrologi["Tuberkulosa"] = array("type"=>201,"varname"=>"Tuberkulosa", "name" => "Tuberkulosa");
$dalTableandrologi["Diabetes_mellitus"] = array("type"=>201,"varname"=>"Diabetes_mellitus", "name" => "Diabetes_mellitus");
$dalTableandrologi["Gondongan_parotitis"] = array("type"=>201,"varname"=>"Gondongan_parotitis", "name" => "Gondongan_parotitis");
$dalTableandrologi["Penyakit_Saraf"] = array("type"=>201,"varname"=>"Penyakit_Saraf", "name" => "Penyakit_Saraf");
$dalTableandrologi["Panas_dlm_6_bln"] = array("type"=>201,"varname"=>"Panas_dlm_6_bln", "name" => "Panas_dlm_6_bln");
$dalTableandrologi["Status_keluarga"] = array("type"=>201,"varname"=>"Status_keluarga", "name" => "Status_keluarga");
$dalTableandrologi["Saudara_kandung_suami"] = array("type"=>201,"varname"=>"Saudara_kandung_suami", "name" => "Saudara_kandung_suami");
$dalTableandrologi["Saudara_kandung_istri"] = array("type"=>201,"varname"=>"Saudara_kandung_istri", "name" => "Saudara_kandung_istri");
$dalTableandrologi["Lingkungan_sosial"] = array("type"=>201,"varname"=>"Lingkungan_sosial", "name" => "Lingkungan_sosial");
$dalTableandrologi["Pekerjaan"] = array("type"=>201,"varname"=>"Pekerjaan", "name" => "Pekerjaan");
$dalTableandrologi["Keluarga"] = array("type"=>201,"varname"=>"Keluarga", "name" => "Keluarga");
$dalTableandrologi["Rokok"] = array("type"=>201,"varname"=>"Rokok", "name" => "Rokok");
$dalTableandrologi["Alkohol"] = array("type"=>201,"varname"=>"Alkohol", "name" => "Alkohol");
$dalTableandrologi["Obat"] = array("type"=>201,"varname"=>"Obat", "name" => "Obat");
$dalTableandrologi["Celana ketat"] = array("type"=>201,"varname"=>"Celana_ketat", "name" => "Celana ketat");
$dalTableandrologi["Bahan_kimia"] = array("type"=>201,"varname"=>"Bahan_kimia", "name" => "Bahan_kimia");
$dalTableandrologi["KU"] = array("type"=>201,"varname"=>"KU", "name" => "KU");
$dalTableandrologi["TB"] = array("type"=>201,"varname"=>"TB", "name" => "TB");
$dalTableandrologi["CM"] = array("type"=>201,"varname"=>"CM", "name" => "CM");
$dalTableandrologi["BB"] = array("type"=>201,"varname"=>"BB", "name" => "BB");
$dalTableandrologi["KG"] = array("type"=>201,"varname"=>"KG", "name" => "KG");
$dalTableandrologi["Tensi"] = array("type"=>201,"varname"=>"Tensi", "name" => "Tensi");
$dalTableandrologi["Pertumbuhan_distribusi_rambut"] = array("type"=>201,"varname"=>"Pertumbuhan_distribusi_rambut", "name" => "Pertumbuhan_distribusi_rambut");
$dalTableandrologi["Kumis"] = array("type"=>201,"varname"=>"Kumis", "name" => "Kumis");
$dalTableandrologi["Jenggot"] = array("type"=>201,"varname"=>"Jenggot", "name" => "Jenggot");
$dalTableandrologi["Mata"] = array("type"=>201,"varname"=>"Mata", "name" => "Mata");
$dalTableandrologi["Hidung"] = array("type"=>201,"varname"=>"Hidung", "name" => "Hidung");
$dalTableandrologi["Leher"] = array("type"=>201,"varname"=>"Leher", "name" => "Leher");
$dalTableandrologi["Dada"] = array("type"=>201,"varname"=>"Dada", "name" => "Dada");
$dalTableandrologi["ginecomastia"] = array("type"=>201,"varname"=>"ginecomastia", "name" => "ginecomastia");
$dalTableandrologi["PERUT"] = array("type"=>201,"varname"=>"PERUT", "name" => "PERUT");
$dalTableandrologi["INGUINAL"] = array("type"=>201,"varname"=>"INGUINAL", "name" => "INGUINAL");
$dalTableandrologi["kubitus (valganus / varus)"] = array("type"=>201,"varname"=>"kubitus__valganus___varus_", "name" => "kubitus (valganus / varus)");
$dalTableandrologi["Rentangan tangan"] = array("type"=>201,"varname"=>"Rentangan_tangan", "name" => "Rentangan tangan");
$dalTableandrologi[" Rambut axilla"] = array("type"=>201,"varname"=>"_Rambut_axilla", "name" => " Rambut axilla");
$dalTableandrologi["Cor"] = array("type"=>201,"varname"=>"Cor", "name" => "Cor");
$dalTableandrologi["Hepar"] = array("type"=>201,"varname"=>"Hepar", "name" => "Hepar");
$dalTableandrologi["Pulmo"] = array("type"=>201,"varname"=>"Pulmo", "name" => "Pulmo");
$dalTableandrologi["Lien"] = array("type"=>201,"varname"=>"Lien", "name" => "Lien");
$dalTableandrologi["Penis"] = array("type"=>201,"varname"=>"Penis", "name" => "Penis");
$dalTableandrologi["Muara_Urethra"] = array("type"=>201,"varname"=>"Muara_Urethra", "name" => "Muara_Urethra");
$dalTableandrologi["Skrotum"] = array("type"=>201,"varname"=>"Skrotum", "name" => "Skrotum");
$dalTableandrologi["Pubis"] = array("type"=>201,"varname"=>"Pubis", "name" => "Pubis");
$dalTableandrologi["Pola_Pubis"] = array("type"=>201,"varname"=>"Pola_Pubis", "name" => "Pola_Pubis");
$dalTableandrologi["Interna_Kanan"] = array("type"=>201,"varname"=>"Interna_Kanan", "name" => "Interna_Kanan");
$dalTableandrologi["Interna_Kiri"] = array("type"=>201,"varname"=>"Interna_Kiri", "name" => "Interna_Kiri");
$dalTableandrologi["Posisi_Testis"] = array("type"=>201,"varname"=>"Posisi_Testis", "name" => "Posisi_Testis");
$dalTableandrologi["Volume"] = array("type"=>201,"varname"=>"Volume", "name" => "Volume");
$dalTableandrologi["Konsistensi"] = array("type"=>201,"varname"=>"Konsistensi", "name" => "Konsistensi");
$dalTableandrologi["Nyeri"] = array("type"=>201,"varname"=>"Nyeri", "name" => "Nyeri");
$dalTableandrologi["VAS_DEFERENS"] = array("type"=>201,"varname"=>"VAS_DEFERENS", "name" => "VAS_DEFERENS");
$dalTableandrologi["FUNICULUS"] = array("type"=>201,"varname"=>"FUNICULUS", "name" => "FUNICULUS");
$dalTableandrologi["EPIDIDYMIS_Ukuran"] = array("type"=>201,"varname"=>"EPIDIDYMIS_Ukuran", "name" => "EPIDIDYMIS_Ukuran");
$dalTableandrologi["EPIDIDYMIS_Konsistensi"] = array("type"=>201,"varname"=>"EPIDIDYMIS_Konsistensi", "name" => "EPIDIDYMIS_Konsistensi");
$dalTableandrologi["EPIDIDYMIS_Kistik"] = array("type"=>201,"varname"=>"EPIDIDYMIS_Kistik", "name" => "EPIDIDYMIS_Kistik");
$dalTableandrologi["EPIDIDYMIS_Nyeri"] = array("type"=>201,"varname"=>"EPIDIDYMIS_Nyeri", "name" => "EPIDIDYMIS_Nyeri");
$dalTableandrologi["EPIDIDYMIS_Permukaan"] = array("type"=>201,"varname"=>"EPIDIDYMIS_Permukaan", "name" => "EPIDIDYMIS_Permukaan");
$dalTableandrologi["VARIKOKEL"] = array("type"=>201,"varname"=>"VARIKOKEL", "name" => "VARIKOKEL");
$dalTableandrologi["Prostat"] = array("type"=>201,"varname"=>"Prostat", "name" => "Prostat");
$dalTableandrologi["V_Seminalis"] = array("type"=>201,"varname"=>"V_Seminalis", "name" => "V_Seminalis");
$dalTableandrologi["lab_ke"] = array("type"=>201,"varname"=>"lab_ke", "name" => "lab_ke");
$dalTableandrologi["lab_tgl"] = array("type"=>201,"varname"=>"lab_tgl", "name" => "lab_tgl");
$dalTableandrologi["no_reg_lab"] = array("type"=>201,"varname"=>"no_reg_lab", "name" => "no_reg_lab");
$dalTableandrologi["kesan_lab"] = array("type"=>201,"varname"=>"kesan_lab", "name" => "kesan_lab");
$dalTableandrologi["Diagnosis_Banding"] = array("type"=>201,"varname"=>"Diagnosis_Banding", "name" => "Diagnosis_Banding");
$dalTableandrologi["Rencana"] = array("type"=>201,"varname"=>"Rencana", "name" => "Rencana");
$dalTableandrologi["id_pasien"] = array("type"=>20,"varname"=>"id_pasien", "name" => "id_pasien");
$dalTableandrologi["id_user"] = array("type"=>20,"varname"=>"id_user", "name" => "id_user");
$dalTableandrologi["Nomor_Rm"] = array("type"=>200,"varname"=>"Nomor_Rm", "name" => "Nomor_Rm");
	$dalTableandrologi["id_andrologi"]["key"]=true;

$dal_info["newrm_at_localhost__andrologi"] = &$dalTableandrologi;
?>